### ISSUE TITLE
lambda/promtail: lambda/promtail fails to send logs with "panic: invalid label name"

### ISSUE THREAD

**Issue by spedersen-emailage** [grafana/loki#11005]
**Describe the bug**

The newest version of lambda-promtail (since Oct. 9) fails to send logs with a "panic: invalid label name" error.

**To Reproduce**

1. Send logs using latest version of lambda-promtail from https://github.com/grafana/loki/commit/ec54c723ebbeeda88000dde188d539ecfe05dad8.

**Expected behavior**

I expect lambda-promtail to send logs. ;-)

**Environment:**
 - Infrastructure: AWS Lambda
 - Deployment tool: Docker
 
**Screenshots, Promtail config, or terminal output**

Lambda logs:

```
2023-10-20T13:30:59.331-07:00	START RequestId: <REQUEST_ID_REMOVED> Version: $LATEST
2023-10-20T13:30:59.350-07:00	RequestId: <REQUEST_ID_REMOVED> Error: Runtime exited with error: exit status 2 Runtime.ExitError
2023-10-20T13:30:59.350-07:00	END RequestId: <REQUEST_ID_REMOVED>
2023-10-20T13:30:59.350-07:00	REPORT RequestId: <REQUEST_ID_REMOVED> Duration: 152.42 ms Billed Duration: 153 ms Memory Size: 128 MB Max Memory Used: 6 MB
2023-10-20T13:31:05.890-07:00	write address: https://logs-prod3.grafana.net/loki/api/v1/push
2023-10-20T13:31:05.909-07:00	extra labels: {appname="aws-grafana-forwarder", env="dev", region="us-west-2"}
2023-10-20T13:31:05.911-07:00	panic: invalid label name
2023-10-20T13:31:05.911-07:00	goroutine 1 [running]:
2023-10-20T13:31:05.911-07:00	main.setupArguments()
2023-10-20T13:31:05.911-07:00	/src/lambda-promtail/lambda-promtail/main.go:66 +0x47d
2023-10-20T13:31:05.911-07:00	main.main()
2023-10-20T13:31:05.911-07:00	/src/lambda-promtail/lambda-promtail/main.go:241 +0x13
```

I believe it's related to this feature update: [feat(lambda/promtail): support dropping labels] (https://github.com/grafana/loki/commit/ec54c723ebbeeda88000dde188d539ecfe05dad8)

Note: We do not use the new `DROP_LABELS` environment variable. 

The source of the panic error is [`getDropLabels()`](https://github.com/grafana/loki/blob/6948c4a179a0b7763aab76d5fd34e67d9fffbf3a/tools/lambda-promtail/lambda-promtail/main.go#L137); it doesn't look like it can handle blank/null values, but I don't know Go so I can't say with certainty.

**Comment by spedersen-emailage** [comment]
Thanks @hainenber !

**Comment by spedersen-emailage** [comment]
I can confirm this resolves the issue. Thanks!
