### ISSUE TITLE
Promtail: concurrent map read and map write

### ISSUE THREAD

**Issue by VitaliiBabii** [grafana/loki#11065]
**Describe the bug**
After adding new label scrape config promtail failed to consume Azure Event Hub with error like 
"concurrent map read and map write".

**To Reproduce**

1. Started Loki 2.9.2  in simple scalable mode 
2. Started Promtail 2.9.2 as deamonset
3.  Try to scrape logs from Azure Event hub without any extra labels and after some time add new label by config like:
`      - job_name: azure_event_hub_t4e_logs
        azure_event_hubs:
          group_id: {{ .Values.azureEventHubT4EFuncLogs.consumerGroupId }}
          fully_qualified_namespace: {{ .Values.azureEventHubT4EFuncLogs.namespaceName }}
          connection_string: {{ .Values.azureEventHubT4EFuncLogs.connectionString }}
          event_hubs:
            - {{ .Values.azureEventHubT4EFuncLogs.eventHubName }}
          labels:
            event_hub: {{ .Values.azureEventHubT4EFuncLogs.eventHubName }}
          use_incoming_timestamp: true
        pipeline_stages:
        - json:
            expressions:
              time: "time"
        - timestamp:
            source: time
            format: RFC3339Nano
        - match:
            selector: '{event_hub="projt4epushvasmetric-functionapp-logs"} |~ ".*AppRoleName.*"'
            action: keep
            stages:
            - json:
                expressions:
                  func_name: "AppRoleName"
            - labels:
                func_name:
        relabel_configs:
          - action: replace
            source_labels:
              - __azure_event_hubs_category
            target_label: category`

After this promtail fails with error:
`fatal error: concurrent map iteration and map write

goroutine 325 [running]:
github.com/grafana/loki/clients/pkg/logentry/stages.(*Pipeline).Run.func1({0xc005a821b0, {0xc0056916e0, {{0x243d580, 0xedccd696d, 0x5ca80c0}, {0xc0057a0a00, 0x4ea}, {0x0, 0x0, 0x0}}}})
        /src/loki/clients/pkg/logentry/stages/pipeline.go:118 +0x7e
github.com/grafana/loki/clients/pkg/logentry/stages.RunWith.func1()
        /src/loki/clients/pkg/logentry/stages/pipeline.go:71 +0x135
created by github.com/grafana/loki/clients/pkg/logentry/stages.RunWith in goroutine 306
        /src/loki/clients/pkg/logentry/stages/pipeline.go:68 +0x90`

**Expected behavior**
No any errors after adding new label to log entries. All works just fine. New label added to logs

**Environment:**
 - Infrastructure: Azure AKS
 - Deployment tool: Helm

[promtail-trace.txt](https://github.com/grafana/loki/files/13187037/promtail-trace.txt)

**Comment by VitaliiBabii** [comment]
Will really appreciate if someone take a look ASAP. Looks like simple logical mistake in code. But I'm not familiar with code base and can't do quick fix by myself(

**Comment by VitaliiBabii** [comment]
Is there any updates regarding this bug? I see some MR. When user's can expect release with the fix ?
Thanks:)

**Comment by JStickler** [comment]
Promtail is end of life (EOL) as of March 2, 2026. No future support or updates will be provided. All future feature development will occur in [Grafana Alloy](https://github.com/grafana/alloy).
