### ISSUE TITLE
Sometimes when I query the data on grafana, the loki process will crash.

### ISSUE THREAD

**Issue by wuzhihui1123** [grafana/loki#1253]
Sometimes when I query the data on grafana, the loki process will crash.

The following is the error message
```
level=info ts=2019-11-13T09:34:35.70122933Z caller=table_manager.go:409 msg="provisioned throughput on table, skipping" table=index_2427 read=0 write=0
level=info ts=2019-11-13T09:34:35.70124583Z caller=table_manager.go:409 msg="provisioned throughput on table, skipping" table=index_2428 read=0 write=0
unexpected fault address 0x7f70768ddbbf
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f70768ddbbf pc=0x402232]
goroutine 10593890 [running]:
runtime.throw(0x1772a05, 0x5)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0b5694068 sp=0xc0b5694038 pc=0x42f602
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc0b5694098 sp=0xc0b5694068 pc=0x444c8e
cmpbody()
        /usr/local/go/src/internal/bytealg/compare_amd64.s:85 +0xa2 fp=0xc0b56940a0 sp=0xc0b5694098 pc=0x402232
bytes.Compare(...)
        /usr/local/go/src/bytes/bytes.go:27
github.com/cortexproject/cortex/pkg/chunk/util.(*filteringBatchIter).Next(0xc0b2207300, 0x1a2cb80)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/util/util.go:95 +0x16c fp=0xc0b5694110 sp=0xc0b56940a0 pc=0xeb11bc
github.com/cortexproject/cortex/pkg/chunk.(*store).lookupEntriesByQueries.func1(0xc0945c4060, 0xa, 0xc077a68cc0, 0x37, 0x0, 0x0, 0x0, 0xc0945c43a0, 0x9, 0x9, ...)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go:446 +0xa3 fp=0xc0b56941e8 sp=0xc0b5694110 pc=0xe00c03
github.com/cortexproject/cortex/pkg/chunk/util.QueryFilter.func1(0xc0945c4060, 0xa, 0xc077a68cc0, 0x37, 0x0, 0x0, 0x0, 0xc0945c43a0, 0x9, 0x9, ...)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/util/util.go:113 +0xe5 fp=0xc0b5694290 sp=0xc0b56941e8 pc=0xeb1d05
github.com/cortexproject/cortex/pkg/chunk/storage.(*cachingIndexClient).QueryPages(0xc000094cc0, 0x1a3f640, 0xc02c208780, 0xc0a080e000, 0x1ea3, 0x1f24, 0xc0aa4c0960, 0x0, 0x0)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/caching_index_client.go:175 +0xe8c fp=0xc0b5694bb0 sp=0xc0b5694290 pc=0x129873c
github.com/cortexproject/cortex/pkg/chunk.(*store).lookupEntriesByQueries(0xc0001b8000, 0x1a3f640, 0xc02c208780, 0xc0a080e000, 0x1ea3, 0x1f24, 0xc03f0879e0, 0x1f, 0xc047a23000, 0x1f, ...)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go:443 +0x107 fp=0xc0b5694c60 sp=0xc0b5694bb0 pc=0xddb997
github.com/cortexproject/cortex/pkg/chunk.(*seriesStore).lookupChunksBySeries(0xc0001b8000, 0x1a3f640, 0xc02c208780, 0x16dc9a00839, 0x16e641ed03a, 0x1771c15, 0x4, 0xc000daa000, 0xfd, 0x5cb, ...)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/series_store.go:360 +0x5e9 fp=0xc0b5694dd0 sp=0xc0b5694c60 pc=0xdf95a9
github.com/cortexproject/cortex/pkg/chunk.(*seriesStore).LabelNamesForMetricName(0xc0001b8000, 0x1a3f640, 0xc0368508d0, 0x1771c15, 0x4, 0x16dc9a00839, 0x16e641ed03a, 0x1771d89, 0x4, 0x0, ...)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/series_store.go:203 +0x5b6 fp=0xc0b5694fd0 sp=0xc0b5694dd0 pc=0xdf6ab6
github.com/cortexproject/cortex/pkg/chunk.compositeStore.LabelNamesForMetricName.func1(0x16dc9a00839, 0x16e641ed03a, 0x1a504a0, 0xc0001b8000, 0x15ad880, 0x25d1030)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:119 +0xa6 fp=0xc0b5695088 sp=0xc0b5694fd0 pc=0xe016d6
github.com/cortexproject/cortex/pkg/chunk.compositeStore.forStores(0xc00000d860, 0x1, 0x1, 0x16dc9a00839, 0x16e641ed03a, 0xc0b5695190, 0xc07e8d3ba0, 0xc065844e00)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:194 +0x1e0 fp=0xc0b5695138 sp=0xc0b5695088 pc=0xddfff0
github.com/cortexproject/cortex/pkg/chunk.compositeStore.LabelNamesForMetricName(0xc00000d860, 0x1, 0x1, 0x1a3f600, 0xc043fbac00, 0x1771c15, 0x4, 0x16dc9a00839, 0x16e641ed03a, 0x1771d89, ...)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:118 +0x113 fp=0xc0b56951e0 sp=0xc0b5695138 pc=0xddfb53
github.com/cortexproject/cortex/pkg/chunk.(*CompositeStore).LabelNamesForMetricName(0xc00000d880, 0x1a3f600, 0xc043fbac00, 0x1771c15, 0x4, 0x16dc9a00839, 0x16e641ed03a, 0x1771d89, 0x4, 0xc03ab05e90, ...)
        <autogenerated>:1 +0xca fp=0xc0b5695270 sp=0xc0b56951e0 pc=0xe07eea
github.com/grafana/loki/pkg/storage.(*store).LabelNamesForMetricName(0xc000080380, 0x1a3f600, 0xc043fbac00, 0x1771c15, 0x4, 0x16dc9a00839, 0x16e641ed03a, 0x1771d89, 0x4, 0x0, ...)
        <autogenerated>:1 +0xaf fp=0xc0b56952f0 sp=0xc0b5695270 pc=0x13327cf
github.com/grafana/loki/pkg/querier.(*Querier).Label(0xc000162840, 0x1a3f640, 0xc03ab05e90, 0xc03ab05ec0, 0x0, 0x0, 0x0)
        /src/loki/pkg/querier/querier.go:212 +0x6c6 fp=0xc0b5695420 sp=0xc0b56952f0 pc=0x1338156
github.com/grafana/loki/pkg/querier.(*Querier).LabelHandler(0xc000162840, 0x1a30e40, 0xc07e8d3b00, 0xc0b679ce00)
        /src/loki/pkg/querier/http.go:117 +0x97 fp=0xc0b5695518 sp=0xc0b5695420 pc=0x1334887
github.com/grafana/loki/pkg/querier.(*Querier).LabelHandler-fm(0x1a30e40, 0xc07e8d3b00, 0xc0b679ce00)
        /src/loki/pkg/querier/http.go:110 +0x48 fp=0xc0b5695548 sp=0xc0b5695518 pc=0x1342fe8
net/http.HandlerFunc.ServeHTTP(0xc000098f50, 0x1a30e40, 0xc07e8d3b00, 0xc0b679ce00)
        /usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc0b5695570 sp=0xc0b5695548 pc=0x762be4
github.com/grafana/loki/pkg/loki.glob..func1.1(0x1a30e40, 0xc07e8d3b00, 0xc0b679cd00)
        /src/loki/pkg/loki/fake_auth.go:18 +0x1ac fp=0xc0b5695608 sp=0xc0b5695570 pc=0x1341d8c
net/http.HandlerFunc.ServeHTTP(0xc00000df00, 0x1a30e40, 0xc07e8d3b00, 0xc0b679cd00)
        /usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc0b5695630 sp=0xc0b5695608 pc=0x762be4
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000e6150, 0x1a30e40, 0xc07e8d3b00, 0xc0b679cd00)
        /src/loki/vendor/github.com/gorilla/mux/mux.go:162 +0x104 fp=0xc0b5695798 sp=0xc0b5695630 pc=0xa56584
github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x1a30e00, 0xc000ee5800, 0xc0b679cb00)
        /src/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:49 +0x16b fp=0xc0b5695850 sp=0xc0b5695798 pc=0xa6206b
net/http.HandlerFunc.ServeHTTP(0xc000157020, 0x1a30e00, 0xc000ee5800, 0xc0b679cb00)
        /usr/local/go/src/net/http/server.go:2007 +0x44 fp=0xc0b5695878 sp=0xc0b5695850 pc=0x762be4
[snip]
```

**Comment by cyriltovena** [comment]
This is a label query crashing should never happen what version of loki are you using and how is your config please

**Comment by Anchal-kansal** [comment]
I am facing a similar issue with one of my loki ingester pod, are there any insights available on this issue?
