### ISSUE TITLE
getting-started docker compose file has error upon starting

### ISSUE THREAD

**Issue by paul1r** [grafana/loki#13065]
**Describe the bug**
When starting docker-compose using the files in `examples/getting-started`, there is an error

```
ts=2024-05-29T06:44:56.887806714Z level=warn msg="could not transfer logs" component_path=/ component_id=loki.source.docker.flog_scrape target=docker/39b515f95b20876a207d1a6b773340322a7be345d5f1d726ded6e6765473b459 written=0 container=39b515f95b20876a207d1a6b773340322a7be345d5f1d726ded6e6765473b459 err="context canceled"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x39e1a70]

goroutine 425 [running]:
github.com/grafana/alloy/internal/component/loki/source/docker/internal/dockertarget.(*Target).Stop(0x4002478480)
	/src/alloy/internal/component/loki/source/docker/internal/dockertarget/target.go:238 +0x20
github.com/grafana/alloy/internal/component/loki/source/docker.(*tailer).Run(0x40024d5460, {0x8717cd0, 0x40024ae640})
	/src/alloy/internal/component/loki/source/docker/runner.go:116 +0x260
github.com/grafana/alloy/internal/runner.(*Runner[...]).ApplyTasks.func2()
	/src/alloy/internal/runner/runner.go:166 +0x98
created by github.com/grafana/alloy/internal/runner.(*Runner[...]).ApplyTasks in goroutine 188
	/src/alloy/internal/runner/runner.go:163 +0x490
```

**To Reproduce**
1. Change to `examples/getting-started`
2. Run `docker compose up`
3. Observe error in the alloy container

**Expected behavior**
No errors

**Environment:**
Chip: M1
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
Docker version 25.0.5, build 5dc9bcc

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by paul1r** [comment]
@rea1shane , I was able to track down the issue, and it has been [reported](https://github.com/grafana/killercoda/issues/4) (and fixed).

We've [adjusted](https://github.com/grafana/loki/pull/13062) the docker file appropriately a couple of hours ago, so you can either pull the latest version, or adjust the alloy image on [this](https://github.com/grafana/loki/blob/main/examples/getting-started/docker-compose.yaml#L49) line to `image: grafana/alloy:v1.0.0`
