### ISSUE TITLE
Processign integer values in fluent-plugin-grafana-loki fails on `gsub`

### ISSUE THREAD

**Issue by Horkyze** [grafana/loki#1378]
**Describe the bug**
The fluentd output plugin is having trouble processing integer values. As seen here:

```
2019-12-06 11:26:54 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `gsub' for 200:Integer"
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-grafana-loki-1.2.5/lib/fluent/plugin/out_loki.rb:198:in `block in format_labels'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-grafana-loki-1.2.5/lib/fluent/plugin/out_loki.rb:198:in `each'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-grafana-loki-1.2.5/lib/fluent/plugin/out_loki.rb:198:in `format_labels'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-grafana-loki-1.2.5/lib/fluent/plugin/out_loki.rb:210:in `block in payload_builder'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-grafana-loki-1.2.5/lib/fluent/plugin/out_loki.rb:204:in `each'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-grafana-loki-1.2.5/lib/fluent/plugin/out_loki.rb:204:in `payload_builder'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-grafana-loki-1.2.5/lib/fluent/plugin/out_loki.rb:180:in `generic_to_loki'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-grafana-loki-1.2.5/lib/fluent/plugin/out_loki.rb:126:in `write'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:1125:in `try_flush'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:1431:in `flush_thread_run'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
today at 12:26 PM    2019-12-06 11:26:54 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.7.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
today at 12:26 PM  2019-12-06 11:26:54 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_3fa84a5f8bd8/59907521b3aaf626d9008a633c4aab46.log
today at 12:27 PM  2019-12-06 11:27:06 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `gsub' for 200:Integer"
```

This line is probably causing error:
https://github.com/grafana/loki/blob/master/fluentd/fluent-plugin-grafana-loki/lib/fluent/plugin/out_loki.rb#L198

When I remove the integer label `OriginStatus`, it works just fine.

**To Reproduce**
My fluentd config:
```
  <match traefik.**>
    @type loki
    url "https://loki.example.net"
    username "loki"
    password "PassWord"
    extra_labels {"logs":"traefik"}
    <label>
      BackendName
    </label>
    <label> 
      RequestHost
    </label>
    <label> 
      OriginStatus   # this is the integer value
    </label>
    <label> 
      ClientHost
    </label>
    line_format json
    flush_interval 10s
    flush_at_shutdown true
    buffer_chunk_limit 1m
  </match>
```
Loki: `v1.1.0`
flunetd-plugin:  `1.2.5 - December 05, 2019 (14 KB) `

**Expected behavior**
Expecting the fluent plugin to process integer values as well, not only strings.
It can convert the integers to strings, for example.

**Environment:**
 - Infrastructure:  bare-metal, docker

**Comment by cyriltovena** [comment]
@tarokkk Do you want to take care of this ?
