### ISSUE TITLE
Promtail 3.2.0 crash on docker with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lluisd** [grafana/loki#14405]
**Describe the bug**
On starting Promtail 3.2.0 I get this error, it was working fine with previous version.

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x2bf5735]
goroutine 132 [running]:
github.com/prometheus/prometheus/discovery/moby.(*DockerDiscovery).refresh(0xc000894440, {0x47b79d0, 0xc0007b3950})
	/src/loki/vendor/github.com/prometheus/prometheus/discovery/moby/docker.go:284 +0xcd5
github.com/prometheus/prometheus/discovery/refresh.(*Discovery).refresh(0xc00065bf20, {0x47b79d0, 0xc0007b3950})
	/src/loki/vendor/github.com/prometheus/prometheus/discovery/refresh/refresh.go:112 +0xcf
github.com/prometheus/prometheus/discovery/refresh.(*Discovery).Run(0xc00065bf20, {0x47b79d0, 0xc0007b3950}, 0xc000312900)
	/src/loki/vendor/github.com/prometheus/prometheus/discovery/refresh/refresh.go:68 +0x66
created by github.com/prometheus/prometheus/discovery.(*Manager).startProvider in goroutine 1
	/src/loki/vendor/github.com/prometheus/prometheus/discovery/manager.go:302 +0x2ec`

I use that docker-compose for Promtail

`version: "3.9"

services:
  promtail:
    image: grafana/promtail:3.2.0
    container_name: promtail
    command: 
      - '--config.file=/etc/promtail/promtail-config.yaml'
    volumes:
      - /volume1/docker/grafana/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - loki_net
    ports:
      - 9030:9030
      
networks:
  loki_net:
    name: loki_net
    external: true`

and that promtail configuration:
`server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9030
  enable_runtime_reload: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

- job_name: container_logs
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 1m
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
    - target_label: 'instance' 
      replacement: 'ds920'
      
- job_name: container_logs_nuc
  docker_sd_configs:
    - host: tcp://192.168.0.161:2375
      refresh_interval: 1m
      host_networking_host: 192.168.0.161
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
    - target_label: 'instance' 
      replacement: 'nuc'
        
- job_name: container_logs_minipc
  docker_sd_configs:
    - host: tcp://192.168.0.162:2375
      refresh_interval: 1m
      host_networking_host: 192.168.0.162
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
    - target_label: 'instance' 
      replacement: 'minipc'
`

**Environment:**
 - Promtail & loki dockers with 3.2.0 version

**Comment by efficks** [comment]
I got the same problem and for now, rolled back to 3.1.1 to fix the issue.

**Comment by jmooo** [comment]
Same issue on v3.2.1, rolled back to v3.1.1 and that still works

**Comment by pgassmann** [comment]
@jmooo  @efficks do you use Docker Swarm? it seems to only crash on the hosts which are in a docker swarm cluster. I did not investigate thoroughly to verify that suspicion.

**Comment by lluisd** [comment]
@pgassmann I don't use Docker Swarm, I don't know if the new 3.3.0 version will still have same problem

**Comment by NicatorBa** [comment]
@lluisd the problem still exists with 3.3.0

**Comment by bullshit** [comment]
Does sombody testet it with v3.3.1

**Comment by LXGaming** [comment]
This is a bug in prometheus which has since been fixed https://github.com/prometheus/prometheus/pull/14654, promtail needs to be updated to use the new version.

**Comment by Chriz42** [comment]
tested with 3.3.2 and  updated my docker scrape config with  match_first_network: false as mentioned [here](https://github.com/prometheus/prometheus/issues/14647#issuecomment-2283592417)

**Comment by janvojt** [comment]
I still encountered this in 3.3.2.

**Comment by adebrouvier** [comment]
3.4.2 works for me as well

**Comment by lluisd** [comment]
anyway I migrated to Grafana Alloy by using the migration tool since Promtail is now deprecated. Good feelings with Grafana Alloy, with Promtail I have many issues with my Synology NAS were docker starts to be unresponsive after the start/stop of the Promtail docker.

**Comment by JStickler** [comment]
Promtail is end of life (EOL) as of March 2, 2026. No future support or updates will be provided. All future feature development will occur in [Grafana Alloy](https://github.com/grafana/alloy).
