### ISSUE TITLE
Repeated read on a failed websocket cause by tailer.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1509]
**Describe the bug**
A panic happened when I rolled out new queriers.

**To Reproduce**

I've just rolled out a new version of our querier. (latest)

**Expected behavior**
no panic

**Screenshots, Promtail config, or terminal output**
```

2020-01-13 10:14:12 | querier-5d9b5f7bd4-5tlsh | panic: repeated read on failed websocket connection
-- | -- | --
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | /src/loki/pkg/querier/http.go:186 +0x4fe
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | created by github.com/grafana/loki/pkg/querier.(*Querier).TailHandler
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | /src/loki/pkg/querier/http.go:188 +0x40
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | github.com/grafana/loki/pkg/querier.(*Querier).TailHandler.func4(0xc0017d3b80, 0xc00067c480)
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | /src/loki/vendor/github.com/gorilla/websocket/conn.go:1028 +0x2f
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0017d3b80, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x1d72f60, 0xc002201bd0)
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | /src/loki/vendor/github.com/gorilla/websocket/conn.go:967 +0x353
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | github.com/gorilla/websocket.(*Conn).NextReader(0xc0017d3b80, 0xffffffffffffffff, 0x0, 0x0, 0x1d72f60, 0xc002201bd0)
  |   | 2020-01-13 10:14:12 | querier-5d9b5f7bd4-gkx6p | goroutine 1029 [running]:


```

**Comment by sandlis** [comment]
Fixed by #1511
