### ISSUE TITLE
panic on GET /loki/api/v1/labels in fresh install with loki-stack

### ISSUE THREAD

**Issue by victorhaggqvist** [grafana/loki#1599]
**Describe the bug**

Panic when setting up the loki datasource in grafana, which I believe queries loki with `GET /loki/api/v1/labels` on save.

```
2020-01-26 21:38:41.471971 I | http: panic serving 10.244.1.90:58206: runtime error: invalid memory address or nil pointer dereference
goroutine 418 [running]:
net/http.(*conn).serve.func1(0xc0009da500)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x178e880, 0x2a88b90)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cortexproject/cortex/pkg/chunk.(*store).lookupChunksByMetricName(0xc0000d2000, 0x1dad4a0, 0xc000a49da0, 0x1a2135b, 0x4, 0x16fe3c1b8ed, 0x16fe3cae0bf, 0x0, 0x0, 0x0, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go:355 +0x72d
github.com/cortexproject/cortex/pkg/chunk.(*store).LabelNamesForMetricName(0xc0000d2000, 0x1dad4a0, 0xc000a49da0, 0x1a2135b, 0x4, 0x16fe3c1b8ed, 0x16fe3cae0bf, 0x1a214cf, 0x4, 0x0, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go:231 +0x44a
github.com/cortexproject/cortex/pkg/chunk.compositeStore.LabelNamesForMetricName.func1(0x16fe3c1b8ed, 0x16fe3cae0bf, 0x1dc1580, 0xc0000d2000, 0x1, 0x0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:119 +0x95
github.com/cortexproject/cortex/pkg/chunk.compositeStore.forStores(0xc00000d180, 0x1, 0x1, 0x16fe3c1b8ed, 0x16fe3cae0bf, 0xc00036b1c8, 0x7f2464290008, 0x0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:194 +0x1e0
github.com/cortexproject/cortex/pkg/chunk.compositeStore.LabelNamesForMetricName(0xc00000d180, 0x1, 0x1, 0x1dad460, 0xc0004a0840, 0x1a2135b, 0x4, 0x16fe3c1b8ed, 0x16fe3cae0bf, 0x1a214cf, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:118 +0x12a
github.com/grafana/loki/pkg/querier.(*Querier).Label(0xc0000af0e0, 0x1dad4a0, 0xc000a48e10, 0xc000a48ea0, 0x0, 0x0, 0x0)
	/src/loki/pkg/querier/querier.go:205 +0x6d0
github.com/grafana/loki/pkg/querier.(*Querier).LabelHandler(0xc0000af0e0, 0x1d9d920, 0xc0001b0bc0, 0xc000635b00)
	/src/loki/pkg/querier/http.go:135 +0x86
net/http.HandlerFunc.ServeHTTP(0xc0001c2f20, 0x1d9d920, 0xc0001b0bc0, 0xc000635b00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/grafana/loki/pkg/querier.NewPrepopulateMiddleware.func1.1(0x1d9d920, 0xc0001b0bc0, 0xc000635b00)
	/src/loki/pkg/querier/http.go:300 +0xfd
net/http.HandlerFunc.ServeHTTP(0xc0000a2780, 0x1d9d920, 0xc0001b0bc0, 0xc000635b00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/grafana/loki/pkg/loki.glob..func1.1(0x1d9d920, 0xc0001b0bc0, 0xc000635a00)
	/src/loki/pkg/loki/fake_auth.go:18 +0x1ac
net/http.HandlerFunc.ServeHTTP(0xc0000a27a0, 0x1d9d920, 0xc0001b0bc0, 0xc000635a00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002163c0, 0x1d9d920, 0xc0001b0bc0, 0xc000635800)
	/src/loki/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x1d9d8e0, 0xc000633200, 0xc000635800)
	/src/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:49 +0x16b
net/http.HandlerFunc.ServeHTTP(0xc0001c5e00, 0x1d9d8e0, 0xc000633200, 0xc000635800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/weaveworks/common/middleware.Log.Wrap.func1(0x1da5460, 0xc0003d6690, 0xc000635800)
	/src/loki/vendor/github.com/weaveworks/common/middleware/logging.go:41 +0x1a6
net/http.HandlerFunc.ServeHTTP(0xc0001c5e30, 0x1da5460, 0xc0003d6690, 0xc000635800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x1da3720, 0xc0009fc0e0, 0xc000635600)
	/src/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:140 +0x5fb
net/http.HandlerFunc.ServeHTTP(0xc0001c5e90, 0x1da3720, 0xc0009fc0e0, 0xc000635600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/weaveworks/common/middleware.Tracer.Wrap.func2(0x1da3720, 0xc0009fc0e0, 0xc000635600)
	/src/loki/vendor/github.com/weaveworks/common/middleware/http_tracing.go:39 +0x8c
net/http.HandlerFunc.ServeHTTP(0xc0001c5ec0, 0x1da3720, 0xc0009fc0e0, 0xc000635600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0001621c0, 0x1da3720, 0xc0009fc0e0, 0xc000635600)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0009da500, 0x1dad3e0, 0xc0006330c0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
```

Blocks are written to object_store (minio), thus there should be data to query

**To Reproduce**
1. Started Loki with loki-stack
2. Blocks are flushed to minio
3. `curl http://loki.example.com/loki/api/v1/labels` results in panic

**Expected behavior**
labels returned

**Environment:**
 - Infrastructure: Kubernetes: 1.17.2
 - Deployment tool: helm: chart: loki-stack-0.27.0 loki: v1.3.0

**Screenshots, Promtail config, or terminal output**
loki-stack helm values:

```yaml
loki:
  enabled: true
  extraArgs:
    log.level: debug
  config:
    schema_config:
      configs:
      - from: 2018-04-15
        store: boltdb
        object_store: s3
    storage_config:
      aws:
        s3: http://redacted:redacted@minio.example.com:9000/loki
        s3forcepathstyle: true

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false
```

**Comment by cyriltovena** [comment]
You don't have a schema version, so it defaults to v1 which doesn't support what we use.

Although let's keep this open we should not panic. :/

```
  schema_config:
    configs:
    - from: 2018-04-15
      store: boltdb
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 168h
```

I set it to `v11` for faster label queries, doesn't use aws for them, but if that doesn't work well use `v10`.

And you can switch like this you need to add a new config with a new date to tomorrow, or just wipe all data and that will work.

**Comment by victorhaggqvist** [comment]
I see, thanks. Adding that does indeed make it work, must have omitted that part copying things around.
