### ISSUE TITLE
runtime error when using azure storage account

### ISSUE THREAD

**Issue by abelal83** [grafana/loki#1623]
**Describe the bug**
Azure storage account used for chunks, this seems to work fine however when querying with grafana loki crashes with the following

```
panic: runtime error: slice bounds out of range [:1324139] with capacity 512000

goroutine 124897 [running]:
github.com/Azure/azure-storage-blob-go/azblob.downloadBlobToBuffer.func1(0x0, 0x14346b, 0x1dad3e0, 0xc0069def40, 0x7c6701, 0xc004040101)
        /src/loki/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:225 +0x49f
github.com/Azure/azure-storage-blob-go/azblob.DoBatchTransfer.func2(0xc038fbaf60, 0xc03ffd3fa8)
        /src/loki/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:335 +0x50
github.com/Azure/azure-storage-blob-go/azblob.DoBatchTransfer.func1(0xc038fbaf60, 0xc03d205ce0)
        /src/loki/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:319 +0x3f
created by github.com/Azure/azure-storage-blob-go/azblob.DoBatchTransfer
        /src/loki/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:317 +0x21f
```

**To Reproduce**
1. Started Loki v1.3.0
3. Attempting to query Loki as using grafana results in panic

**Expected behavior**
Loki should not panic

**Environment:**
 - Infrastructure: Azure Kubernetes
 - Deployment tool: helm

Additionally when testing loki datasource in grafana these errors are produced. Moving chunks to cassandra or attached disk works with no issues.
```
ts=2020-02-03T15:57:47.109675892Z caller=spanlogger.go:37 org_id=fake trace_id=732f4846eac594fa method=SeriesStore.lookupLabelNamesByChunks level=error msg=FetchChunks err="invalid chunk checksum"
level=warn ts=2020-02-03T15:57:47.109975895Z caller=logging.go:49 traceID=732f4846eac594fa msg="GET /api/prom/label?start=1580744865811000000 (500) 1.251334635s Response: \"invalid chunk checksum\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.9; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/6.5.2; X-Forwarded-For: 213.133.153.253, 10.21.35.227, 10.21.35.227; X-Grafana-Nocache: true; X-Grafana-Org-Id: 1; X-Original-Uri: /api/datasources/proxy/12/api/prom/label?start=1580744865811000000; X-Real-Ip: 213.133.153.253; X-Request-Id: 69c7cae37263724f2082c2c3b47b8a8e; X-Scheme: https; "
```

**Comment by abelal83** [comment]
so I've managed to get past that issue by deleting blob container, cassandara database and starting over again but now facing a completely different issue. When adding Loki as a datasource it errors with this message

```
evel=warn ts=2020-02-03T16:48:36.297033571Z caller=logging.go:49 traceID=62226147e61c0b58 msg="GET /api/prom/label?start=1580744914667000000&end=1580748514667000000 (500) 1.429085366s Response: \"invalid chunk checksum\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.9; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/6.5.2; X-Forwarded-For: 213.133.153.253, 10.21.36.57, 10.21.36.57; X-Grafana-Org-Id: 1; X-Original-Uri: /api/datasources/proxy/13/api/prom/label?start=1580744914667000000&end=1580748514667000000; X-Real-Ip: 213.133.153.253; X-Request-Id: 8ca2cc38a82505e578bb68d48cbba873; X-Scheme: https; "
```

Any ideas?

**Comment by AdieOlami** [comment]
Hi @abelal83 are you able to find a way around this?
