### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by arats-io** [grafana/loki#1679]
**Describe the bug**
invalid memory address or nil pointer dereference

**To Reproduce**
1. Started Loki in Docker Compose
2. Configured to use AWS S3 & DynamoDb
3. Push operation over REST API with: Labels[CreationTime:1581510766494, CustomIdx1:filter, EventType:MISL_ERROR, Id:02831853-ce05-4c03-a027-d1ef0626abfb, Message:NEW Can't read data Filter 1 - 02831853-ce05-4c03-a027-d1ef0626abfb, NodeId:1/main, Sender:MISL Severity:ERROR, SystemId:30000, __name__:event]; Streams=["test"])]

**Expected behavior**
To not fail on push.

**Environment:**
 - Infrastructure: laptop

**Configuration:**
auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 10000
  register_instrumentation: false
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 0
  log_level: "debug"

querier:
  query_timeout: 3m
  tail_max_duration: 1h
  extra_query_delay: 30s
  query_ingesters_within: 10s
  engine:
    timeout: 3m
    max_look_back_period: 30s

ingester_client:
  pool_config:
    health_check_ingesters: true
    client_cleanup_period: 15s
  remote_timeout: 30s
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: true
    rate_limit: 0
    rate_limit_burst: 0
    backoff_on_ratelimits: false
    backoff_config:
      minbackoff: 100ms
      maxbackoff: 10s
      maxretries: 10

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
        prefix: "collectors/"
      heartbeat_timeout: 1m
      replication_factor: 1
    num_tokens: 128
    heartbeat_period: 5s
    min_ready_duration: 1m
    normalise_tokens: false
    join_after: 0s
    final_sleep: 30s
  max_transfer_retries: 10
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  chunk_block_size: 262144
  chunk_target_size: 10
  chunk_encoding: gzip
  flush_op_timeout: 10s
  flush_check_period: 30s
  sync_period: 1
  sync_min_utilization: 0.5
  max_returned_stream_errors: 10
  concurrent_flushes: 16
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2018-04-15
      store: aws
      object_store: s3
      schema: v11
      index:
        prefix: loki_monitoring_index
        period: 2160h
storage_config:
  aws:
    s3: s3://eu-central-1/dev-loki-server-bucket
    dynamodbconfig:
      dynamodb: dynamodb://eu-central-1
      apilimit: 2.0
      throttlelimit: 10.0

limits_config:
  ingestion_rate_strategy: "local"
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30
  reject_old_samples: true
  reject_old_samples_max_age: 336h
  creation_grace_period: 10m
  enforce_metric_name: true
  max_streams_per_user: 10000
  max_global_streams_per_user: 0
  max_chunks_per_query: 2000000
  max_query_length: 0
  max_query_parallelism: 14
  cardinality_limit: 100000
  max_streams_matchers_per_query: 1000

chunk_store_config:
  chunk_cache_config:
    enable_fifocache: true
    defaul_validity: 1h
    fifocache:
      size: 9000
      validity: 1h
  write_dedupe_cache_config:
    enable_fifocache: true
    defaul_validity: 1h
    fifocache:
      size: 9000
      validity: 1h
  cache_lookups_older_than: 1h
  max_look_back_period: 2160h

table_manager:
  throughput_updates_disabled: false
  retention_deletes_enabled: true
  retention_period: 2160h
  dynamodb_poll_interval: 2m
  creation_grace_period: 10m
  index_tables_provisioning:
    provisioned_throughput_on_demand_mode: true
    provisioned_write_throughput: 50
    provisioned_read_throughput: 5
    inactive_throughput_on_demand_mode: true
    inactive_write_throughput: 5
    inactive_read_throughput: 50
    write_scale:
      enabled: false
      min_capacity: 50
      max_capacity: 100
      out_cooldown: 1800
      in_cooldown: 1800
      target: 80

**Screenshots, Promtail config, or terminal output**
loki_1      | level=debug ts=2020-02-12T12:32:54.946697Z caller=schema_config.go:464 msg="Table is Active" tableName=loki_monitoring_index203 provisionedRead=5 provisionedWrite=50 useOnDemandMode=true useWriteAutoScale=false useReadAutoScale=false
loki_1      | level=info ts=2020-02-12T12:32:54.9468035Z caller=table_manager.go:220 msg="synching tables" expected_tables=2
loki_1      | panic: runtime error: invalid memory address or nil pointer dereference
loki_1      | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf657c7]
loki_1      |
loki_1      | goroutine 277 [running]:
loki_1      | go.(*struct { github.com/grafana/loki/pkg/logproto.PusherClient; github.com/grafana/loki/pkg/logproto.QuerierClient; github.com/grafana/loki/pkg/logproto.IngesterClient; google.golang.org/grpc/health/grpc_health_v1.HealthClient; io.Closer }).Check(0xc000f3e870, 0x1daf640, 0xc000e9d560, 0xc000e9d590, 0x0, 0x0, 0x0, 0xc000e9d560, 0xc000fa3e00, 0xecfd62)
loki_1      | 	<autogenerated>:1 +0x37
loki_1      | github.com/cortexproject/cortex/pkg/ingester/client.healthCheck(0x1d937c0, 0xc000f3e870, 0x3b9aca00, 0x0, 0x0)
loki_1      | 	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ingester/client/pool.go:208 +0x178
loki_1      | github.com/cortexproject/cortex/pkg/ingester/client.(*Pool).cleanUnhealthy(0xc0000dee00)
loki_1      | 	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ingester/client/pool.go:193 +0xf5
loki_1      | github.com/cortexproject/cortex/pkg/ingester/client.(*Pool).loop(0xc0000dee00)
loki_1      | 	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ingester/client/pool.go:86 +0x182
loki_1      | created by github.com/cortexproject/cortex/pkg/ingester/client.NewPool
loki_1      | 	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ingester/client/pool.go:71 +0x11a

**Comment by arats-io** [comment]
It's working if changing the following configuration:
`
ingester_client:
  pool_config:
    health_check_ingesters: false
`
But anyway with: health_check_ingesters: true, should not kill the loki server.
