### ISSUE TITLE
Promtail: Nil pointer reference, when parsing JSON logs

### ISSUE THREAD

**Issue by thomasdraebing** [grafana/loki#1680]
**Describe the bug**
I am trying to parse JSON logs with a pipeline in JSON. The JSON maps do not all have the same set of keys, e.g. the 'exception'-key is only present in a few logs. When I know want to extract the 'exception'- key-value pair and use it later on in the pipeline, e.g. to set it as a label, Promtail panics when trying to set the label, when the key did not exist in the JSON. Promatil gives me the following exception:

```
level=debug ts=2020-02-12T14:44:36.069455Z caller=pipeline.go:91 component=file_pipeline component=pipeline msg="processing pipeline" stage=0 name=json labels="{filename=\"/tmp/logs/log.json\", job=\"gerrit_error\"}" time=2020-02-12T15:44:36.06937+01:00 entry="{\"name\":\"test1\"}"
level=debug ts=2020-02-12T14:44:36.069974Z caller=pipeline.go:91 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=labels labels="{filename=\"/tmp/logs/log.json\", job=\"gerrit_error\"}" time=2020-02-12T15:44:36.06937+01:00 entry="{\"name\":\"test1\"}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x1a4beb0]

goroutine 259 [running]:
github.com/grafana/loki/pkg/logentry/stages.(*labelStage).Process(0xc00042fda0, 0xc0004eb710, 0xc0004eb740, 0xc0000ce6a0, 0xc000596370)
	/src/loki/pkg/logentry/stages/labels.go:71 +0x230
github.com/grafana/loki/pkg/logentry/stages.(*Pipeline).Process(0xc00009de80, 0xc0004eb710, 0xc0004eb740, 0xc0000ce6a0, 0xc000596370)
	/src/loki/pkg/logentry/stages/pipeline.go:93 +0x213
github.com/grafana/loki/pkg/logentry/stages.(*Pipeline).Wrap.func1(0xc0004eb710, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x0, 0xffffffffffffffff)
	/src/loki/pkg/logentry/stages/pipeline.go:113 +0x101
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc00042fde0, 0xc0004eb710, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x203000, 0xc0004eb6e0)
	/src/loki/pkg/promtail/api/types.go:19 +0x65
github.com/grafana/loki/pkg/promtail/api.AddLabelsMiddleware.func1.1(0xc0004eb6e0, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x0, 0x0)
	/src/loki/pkg/promtail/api/types.go:40 +0xa3
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc0002460a0, 0xc0004eb6e0, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0xc0006e3d98, 0x0)
	/src/loki/pkg/promtail/api/types.go:19 +0x65
github.com/grafana/loki/pkg/promtail/api.AddLabelsMiddleware.func1.1(0xc0004eb6b0, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x2fd8700, 0xc0004eb6b0)
	/src/loki/pkg/promtail/api/types.go:40 +0xa3
github.com/grafana/loki/pkg/promtail/api.EntryHandlerFunc.Handle(0xc000246300, 0xc0004eb6b0, 0xbf8921b504228090, 0x12c5bb147, 0x48be9e0, 0xc000584020, 0x10, 0x0, 0x0)
	/src/loki/pkg/promtail/api/types.go:19 +0x65
github.com/grafana/loki/pkg/promtail/targets.(*tailer).run(0xc0000c2720)
	/src/loki/pkg/promtail/targets/tailer.go:109 +0x47d
created by github.com/grafana/loki/pkg/promtail/targets.newTailer
	/src/loki/pkg/promtail/targets/tailer.go:74 +0x493
```

**To Reproduce**
1. Have a json log file:

```
{"name":"test1"}
{"name":"test2", "exception":"foo"}
```

2. Have a Promtail pipeline like:

```
  - json:
      expressions:
        name:
        exception:
  - labels:
      exception:
```

3. Start Promtail (1.3.0) to tail 'log.json'

**Expected behavior**
I would expect Promtail to skip non-existing key-value pairs in logs (maybe printing a warning). Thus, in the example above, I would get the label `exception` for the second, but not the first log entry, or at least have the label for the first entry set to `"nil"` or something similar.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: binary

**Screenshots, Promtail config, or terminal output**
see description above.

**Comment by adityacs** [comment]
@thomasdraebing Could you please confirm this error without using `DEBUG` mode? You should not get this error if you are not using `DEBUG` mode.

**Comment by thomasdraebing** [comment]
@adityacs that indeed works and promtail sends the logs to loki as expected. However, with debug-logging activated, promtail crashes with the above mentioned exception. So the nil pointer is probably happening, when the debug log message is created, I would guess.

**Comment by thomasdraebing** [comment]
AH, I just saw your pull request. Quick work. Note, that this does not only happen, when trying to set labels, but at least also when trying to use the template stage.

**Comment by adityacs** [comment]
@thomasdraebing Yeah, you are right. Will look into it
