### ISSUE TITLE
ingestion rate limit exceeded 

### ISSUE THREAD

**Issue by rndmh3ro** [grafana/loki#1923]
**Describe the bug**

I'm getting the following lines in loki when sending logs from promtail (using static_config to scrape logfiles):

``` 
level=warn ts=2020-04-09T09:15:05.866134665Z caller=client.go:242 component=client host=172.29.95.195:3100 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): ingestion rate limit (8388608 bytes) exceeded while adding 311 lines for a total size of 102169 bytes"
```

I don't quiet understand this line or is it misleading? 

It says "adding 311 lines for a **total** size of 102169 bytes".  But the total size of 102169 bytes is less than the ingestion limit of 8388608 bytes.
Or does it mean that it tries to store 311 * 102169 = ‭31.774.559‬ bytes of data, thus exceeding the ingestion rate limit?

**To Reproduce**
1. Started Loki v1.0.4
2. Started Promtail v1.0.4
3. let promtail parse a huge logfile

**Expected behavior**
I'd like to understand what this error exactly means.

And also how to avoid it. :)

**Environment:**
 - Infrastructure: bare-metal

**Screenshots, Promtail config, or terminal output**
Loki limits config:
```
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 8
```

Promtail `loki-batch-size` is set to default.

**Comment by owen-d** [comment]
The message is describing which request triggered the rate limiter. Likely this is because previous batches sent from promtail consumed the remainder of the ingestion budget. If you aren't seeing these regularly, it's ok - promtail is designed to handle backoffs and continue ingestion. If these messages are common, increase the `ingestion_rate_mb` and/or the `ingestion_burst_size` config :)

https://github.com/grafana/loki/tree/master/docs/configuration#limits_config

**Comment by rndmh3ro** [comment]
I had this problem fairly often during my tests and the initial setup if promtail. Probably because it was indexing all these huge system-logfiles at the same time.
However increasing the `ingestion_burst_size` to 16mb seems to have fixed even these problems.

Thanks for your help!

**Comment by smhhoseinee** [comment]
I added following  config :
```
limits_config:
  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 1024
```
again logstash shows the same error and stops sending log to loki: 
```
error_inspect=>"#<StandardError: #<Net::HTTPTooManyRequests:0x3d8fee58>>", :error=>#<StandardError: #<Net::HTTPTooManyRequests:0x3d8fee58>>} 
```

**Comment by yakob-aleksandrovich** [comment]
`TooManyRequests` sounds a bit like the issue here: https://github.com/grafana/loki/issues/4613. Try with the following config changes
```
query_range:
  split_queries_by_interval: 0
  parallelise_shardable_queries: false

querier:
  max_concurrent: 2048

frontend:
  max_outstanding_per_tenant: 4096
  compress_responses: true
```

If I were you, I would bring the ingestion rate and size down to something below the 100. Your  current settings allow for 1GB of data per query. That sounds a bit too much...

**Comment by LinTechSo** [comment]
Hi, same issue. I had this problem during my storage migration from filesystem to minio s3 in loki 2.4.2 

got ```
vector_core::stream::driver: Service call failed. error=ServerError { code: 429 } request_id=5020
``` error from my log shipper  

any updates ?

**Comment by yakob-aleksandrovich** [comment]
Hi @LinTechSo, 

I have never seen this specific message, but `code 429` hints at the fact that this is the same root cause.
Can I assume that you never had this issue when you were running on a local filesystem?
From my own experience, interacting with S3 (AWS or Minio) introduces a lag issue. Writing and reading from local filesystem is very fast, but using S3 on the backend slows things down considerably. This speed issue *might* affect the 'too many requests' issue, as it will take longer to release connections for re-use.

From your post, I don't know if you are still reading experiencing these issues. If you do, you might want to introduce a 'holdoff' mechanism in your migration script. Basically, give Loki now and then some time to breathe: wait a couple of seconds before sending the next batch of data.
There is also the possibility of setting up Loki instances, so that the load can be spread out. But I have no experience with that.

**Comment by LinTechSo** [comment]
thanks, @yakob-aleksandrovich . would you please explain more what should I do?
how can I tell Loki to wait a couple of seconds before sending the next batch of data?

**Comment by yakob-aleksandrovich** [comment]
Depending on how you feed your data into Loki, this is possible or not.
I'm running a custom Python script, feeding logs into Loki. In this script, I've implemented a sleep(1).

**Comment by fengxsong** [comment]
When this happened to me, I checked the `ingester`'s logs. It tells that some logs like "Maximum byte rate per second per stream", then I've increased settings for `limits_config. per_stream_rate_limit` and `limits_config.per_stream_rate_limit_burst` . Problem solved:)

**Comment by rmn-lux** [comment]
My experimental config, which seemed to help get rid of the 429 code. Might come in handy.

```   limits_config:
      retention_period: 72h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      # for big logs tune
      per_stream_rate_limit: 512M
      per_stream_rate_limit_burst: 1024M
      cardinality_limit: 200000
      ingestion_burst_size_mb: 1000
      ingestion_rate_mb: 10000
      max_entries_limit_per_query: 1000000
      max_label_value_length: 20480
      max_label_name_length: 10240
      max_label_names_per_series: 300
```

**Comment by dellnoantechnp** [comment]
promtail inspect logs:
```log
[inspect: regex stage]: 
{stages.Entry}.Extracted["LEVEL"]:
	+: ERROR
{stages.Entry}.Extracted["msg"]:
	+: [com.alibaba.nacos.client.naming.updater] [com.alibaba.nacos.client.naming] [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:607)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
  at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
  at sun.net.www.http.HttpClient.New(HttpClient.java:339)
  at sun.net.www.http.HttpClient.New(HttpClient.java:357)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
  at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
  at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:410)
  at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
  at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
  at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
  at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
  at com.alibaba.nacos.client.naming.core.HostReactor.run(HostReactor.java:315)
  at java.util.concurrent.Executors.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor.access01(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:293)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
{stages.Entry}.Extracted["time"]:
	+: 2022-Dec-28 02:23:34.380
[inspect: labels stage]: 
{stages.Entry}.Entry.Labels:
	-: {category="logback", filename="/data/panda/logs/stdout-c.log", namespace="default", nodename="k8s02.example.local", pod="nginx-deployment-68f9c6c8bc-kshms", type="file"}
	+: {LEVEL="ERROR", category="logback", filename="/data/panda/logs/stdout-c.log", namespace="default", nodename="k8s02.example.local", pod="nginx-deployment-68f9c6c8bc-kshms", time="2022-Dec-28 02:23:34.380", type="file"}
[inspect: timestamp stage]: 
{stages.Entry}.Entry.Entry.Timestamp:
	-: 2022-12-28 02:24:54.915108034 +0000 UTC
	+: 2022-12-28 02:23:34.38 +0000 UTC
[inspect: output stage]: 
{stages.Entry}.Entry.Entry.Line:
	-: 2022-Dec-28 02:23:34.380 ERROR [com.alibaba.nacos.client.naming.updater] [com.alibaba.nacos.client.naming] [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:607)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
  at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
  at sun.net.www.http.HttpClient.New(HttpClient.java:339)
  at sun.net.www.http.HttpClient.New(HttpClient.java:357)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
  at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
  at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:410)
  at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
  at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
  at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
  at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
  at com.alibaba.nacos.client.naming.core.HostReactor.run(HostReactor.java:315)
  at java.util.concurrent.Executors.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor.access01(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:293)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
	+: [com.alibaba.nacos.client.naming.updater] [com.alibaba.nacos.client.naming] [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:607)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
  at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
  at sun.net.www.http.HttpClient.New(HttpClient.java:339)
  at sun.net.www.http.HttpClient.New(HttpClient.java:357)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
  at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
  at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:410)
  at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
  at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
  at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
  at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
  at com.alibaba.nacos.client.naming.core.HostReactor.run(HostReactor.java:315)
  at java.util.concurrent.Executors.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor.access01(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:293)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
level=warn ts=2022-12-28T02:24:55.990027989Z caller=client.go:369 component=client host=grafana-loki-gateway.loki.svc.cluster.local msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased"
level=warn ts=2022-12-28T02:24:56.951209257Z caller=client.go:369 component=client host=grafana-loki-gateway.loki.svc.cluster.local msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased"
```

but we have only  6 labels, is [category, filename, namespace, nodename, pod, type].

loki  limits_config:
```yaml
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
      per_stream_rate_limit: 512M
      cardinality_limit: 200000
      ingestion_burst_size_mb: 1000
      ingestion_rate_mb: 10000
      max_entries_limit_per_query: 1000000
      max_global_streams_per_user: 10000
      max_streams_per_user: 0
      max_label_value_length: 20480
      max_label_name_length: 10240
      max_label_names_per_series: 300
```

ingester logs:
```log
level=debug ts=2022-12-28T02:24:55.633793873Z caller=checkpoint.go:380 msg="writing series" size="1.0 kB"
level=debug ts=2022-12-28T02:24:55.661034141Z caller=checkpoint.go:380 msg="writing series" size="619 B"
level=debug ts=2022-12-28T02:24:55.687601056Z caller=checkpoint.go:380 msg="writing series" size="897 B"
level=debug ts=2022-12-28T02:24:55.714444529Z caller=checkpoint.go:380 msg="writing series" size="1.1 kB"
level=debug ts=2022-12-28T02:24:55.741900389Z caller=checkpoint.go:380 msg="writing series" size="40 kB"
level=debug ts=2022-12-28T02:24:55.768251644Z caller=checkpoint.go:380 msg="writing series" size="640 B"
level=debug ts=2022-12-28T02:24:55.795876509Z caller=checkpoint.go:380 msg="writing series" size="1.4 kB"
level=debug ts=2022-12-28T02:24:55.823166069Z caller=checkpoint.go:380 msg="writing series" size="722 B"
level=debug ts=2022-12-28T02:24:55.850118493Z caller=checkpoint.go:380 msg="writing series" size="963 B"
level=debug ts=2022-12-28T02:24:55.859310887Z caller=grpc_logging.go:46 method=/logproto.Pusher/Push duration=11.595949ms msg="gRPC (success)"
level=debug ts=2022-12-28T02:24:55.877263515Z caller=checkpoint.go:380 msg="writing series" size="630 B"
level=debug ts=2022-12-28T02:24:55.903718849Z caller=checkpoint.go:380 msg="writing series" size="1.5 kB"
level=debug ts=2022-12-28T02:24:55.931045495Z caller=checkpoint.go:380 msg="writing series" size="732 B"
level=debug ts=2022-12-28T02:24:55.958393222Z caller=checkpoint.go:380 msg="writing series" size="1.9 kB"
level=warn ts=2022-12-28T02:24:55.975787108Z caller=grpc_logging.go:43 method=/logproto.Pusher/Push duration=364.389µs err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased" msg=gRPC
level=debug ts=2022-12-28T02:24:55.985207795Z caller=checkpoint.go:380 msg="writing series" size="33 kB"
level=warn ts=2022-12-28T02:24:55.989664147Z caller=grpc_logging.go:43 method=/logproto.Pusher/Push duration=147.473µs err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased" msg=gRPC
level=debug ts=2022-12-28T02:24:56.012768592Z caller=checkpoint.go:380 msg="writing series" size="136 kB"
level=debug ts=2022-12-28T02:24:56.039442188Z caller=checkpoint.go:380 msg="writing series" size="1.2 kB"
level=debug ts=2022-12-28T02:24:56.065680219Z caller=checkpoint.go:380 msg="writing series" size="3.5 kB"
level=debug ts=2022-12-28T02:24:56.09313445Z caller=checkpoint.go:380 msg="writing series" size="2.9 kB"
level=debug ts=2022-12-28T02:24:56.105528395Z caller=grpc_logging.go:46 method=/logproto.Pusher/Push duration=143.685µs msg="gRPC (success)"
.......
level=debug ts=2022-12-28T02:24:56.687535913Z caller=checkpoint.go:380 msg="writing series" size="747 B"
level=debug ts=2022-12-28T02:24:56.714759918Z caller=checkpoint.go:380 msg="writing series" size="1.0 kB"
level=debug ts=2022-12-28T02:24:56.742064861Z caller=checkpoint.go:380 msg="writing series" size="2.0 kB"
level=debug ts=2022-12-28T02:24:56.746666461Z caller=grpc_logging.go:46 method=/logproto.Pusher/Push duration=154.915µs msg="gRPC (success)"
level=debug ts=2022-12-28T02:24:56.768361199Z caller=checkpoint.go:380 msg="writing series" size="1.3 kB"
level=debug ts=2022-12-28T02:24:56.796098662Z caller=checkpoint.go:380 msg="writing series" size="1.4 kB"
level=debug ts=2022-12-28T02:24:56.822239203Z caller=checkpoint.go:380 msg="writing series" size="993 B"
level=debug ts=2022-12-28T02:24:56.849595809Z caller=checkpoint.go:380 msg="writing series" size="1.4 kB"
level=debug ts=2022-12-28T02:24:56.876830763Z caller=checkpoint.go:380 msg="writing series" size="1.4 kB"
level=debug ts=2022-12-28T02:24:56.904213504Z caller=checkpoint.go:380 msg="writing series" size="976 B"
level=debug ts=2022-12-28T02:24:56.930416884Z caller=checkpoint.go:380 msg="writing series" size="1.3 kB"
level=warn ts=2022-12-28T02:24:56.935190924Z caller=grpc_logging.go:43 method=/logproto.Pusher/Push duration=552.025µs err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased" msg=gRPC
level=warn ts=2022-12-28T02:24:56.950550179Z caller=grpc_logging.go:43 method=/logproto.Pusher/Push duration=157.81µs err="rpc error: code = Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased" msg=gRPC
level=debug ts=2022-12-28T02:24:56.957842766Z caller=checkpoint.go:380 msg="writing series" size="2.6 kB"
level=debug ts=2022-12-28T02:24:56.984865328Z caller=checkpoint.go:380 msg="writing series" size="1.0 kB"
level=debug ts=2022-12-28T02:24:56.986317006Z caller=grpc_logging.go:46 method=/logproto.Pusher/Push duration=5.702182ms msg="gRPC (success)"
level=debug ts=2022-12-28T02:24:57.012381115Z caller=checkpoint.go:380 msg="writing series" size="1.4 kB"
level=debug ts=2022-12-28T02:24:57.038666696Z caller=checkpoint.go:380 msg="writing series" size="1.1 kB"
level=debug ts=2022-12-28T02:24:57.066123197Z caller=checkpoint.go:380 msg="writing series" size="1.4 kB"
level=debug ts=2022-12-28T02:24:57.092718764Z caller=checkpoint.go:380 msg="writing series" size="8.9 kB"
level=debug ts=2022-12-28T02:24:57.11988957Z caller=checkpoint.go:380 msg="writing series" size="1.4 kB"
level=debug ts=2022-12-28T02:24:57.147200234Z caller=checkpoint.go:380 msg="writing series" size="627 B"
level=debug ts=2022-12-28T02:24:57.174550674Z caller=checkpoint.go:380 msg="writing series" size="1.1 kB"
level=debug ts=2022-12-28T02:24:57.201353523Z caller=checkpoint.go:380 msg="writing series" size="1.7 kB"
.....
```

My total log size less than 150G  during 30 days.

Why  return   "429 Maximum active stream limit exceeded, reduce the number of active streams"  ?
