### ISSUE TITLE
Panic on ingester shutdown

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#258]
```
level=info ts=2019-01-31T10:30:16.957132331Z caller=lifecycler.go:441 msg="changing ingester state from" old_state=ACTIVE new_state=LEAVING
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xc34cec]

goroutine 7396 [running]:
github.com/grafana/loki/vendor/cloud.google.com/go/storage.(*Writer).open.func1(0xc0002af440, 0xc00058f040, 0xc0001f0bd0, 0xc00386a8c0, 0x1, 0x1)
	/go/src/github.com/grafana/loki/vendor/cloud.google.com/go/storage/writer.go:120 +0xfc
created by github.com/grafana/loki/vendor/cloud.google.com/go/storage.(*Writer).open
	/go/src/github.com/grafana/loki/vendor/cloud.google.com/go/storage/writer.go:110 +0x496
```

**Comment by tomwilkie** [comment]
Duep of #105
