### ISSUE TITLE
LogCLI/API cannot retrieve log value when pushed via API

### ISSUE THREAD

**Issue by AlbertasG** [grafana/loki#287]
Loki and LogCLI build from commit: 776c37e93f5626d14cbc244d2394d1d0f2c63dca

I`ve tried using API example specified in https://github.com/grafana/loki/blob/master/docs/api.md

I see  new labels being created and returned via API

_root@localhost # date
Tue Feb  5 17:13:45 CET 2019
root@localhost # curl -XPOST -H "Content-type: application/json" -d '{
  "streams": [
    {
      "labels": "{foo=\"test\"}",
      "entries": [{ "ts": "2019-02-05T17:12:06.801064-04:00", "line": "bazzzzzzz" }]
    }
  ]
}' 'http://localhost:3100/api/prom/push'
root@localhost  #./logcli labels foo --addr="http://localhost:3100"
http://localhost:3100/api/prom/label/foo/values
bar
test_

Querying the same labels gives empty result

_root@localhost #  ./logcli query '{foo="test"}' --addr="http://localhost:3100"
http://localhost:3100/api/prom/query?query=%7Bfoo%3D%22test%22%7D&limit=30&start=1549379656914860020&end=1549383256914860020&direction=BACKWARD&regexp=
root@localhost #_

Debug for the same queries

[Loki-debug.txt](https://github.com/grafana/loki/files/2832939/Loki-debug.txt)

Labels and Query requests both are 200 as seen from Logs.
Anyone with similar issues?

**Comment by davkal** [comment]
Can confirm. There seems to be something odd with consuming that timestamp. If I redo the steps with line's timestamp ending on `-04:00` I get the following when querying:
```
2019/02/11 14:19:17 http: panic serving [::1]:59748: runtime error: invalid memory address or nil pointer dereference
goroutine 401 [running]:
net/http.(*conn).serve.func1(0xc00094c280)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1746 +0xd0
panic(0x1ccba00, 0x2a60d50)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:513 +0x1b9
github.com/grafana/loki/pkg/iter.(*queryClientIterator).Labels(0xc00002d940, 0x200d480, 0xc00002d940)
	/Users/david/go/src/github.com/grafana/loki/pkg/iter/iterator.go:279 +0x2a
github.com/grafana/loki/pkg/iter.NewHeapIterator(0xc00097dff0, 0x1, 0x1, 0x1, 0xc00097db90, 0x1)
	/Users/david/go/src/github.com/grafana/loki/pkg/iter/iterator.go:123 +0x122
github.com/grafana/loki/pkg/querier.(*Querier).Query(0xc0001e7d40, 0x200b0c0, 0xc000b54a80, 0xc0009aa7e0, 0x0, 0x0, 0x0)
	/Users/david/go/src/github.com/grafana/loki/pkg/querier/querier.go:106 +0x1ea
github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler(0xc0001e7d40, 0x200a740, 0xc0009197c0, 0xc00093b100)
	/Users/david/go/src/github.com/grafana/loki/pkg/querier/http.go:100 +0x537
github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler-fm(0x200a740, 0xc0009197c0, 0xc00093b100)
	/Users/david/go/src/github.com/grafana/loki/pkg/loki/modules.go:145 +0x48
net/http.HandlerFunc.ServeHTTP(0xc000151490, 0x200a740, 0xc0009197c0, 0xc00093b100)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
github.com/grafana/loki/pkg/loki.glob..func1.1(0x200a740, 0xc0009197c0, 0xc00093b000)
	/Users/david/go/src/github.com/grafana/loki/pkg/loki/fake_auth.go:18 +0x13b
net/http.HandlerFunc.ServeHTTP(0xc00014b0e0, 0x200a740, 0xc0009197c0, 0xc00093b000)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
net/http.Handler.ServeHTTP-fm(0x200a740, 0xc0009197c0, 0xc00093b000)
	/Users/david/go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:133 +0x4d
github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x2007180, 0xc000919760, 0xc00093af00)
	/Users/david/go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
net/http.HandlerFunc.ServeHTTP(0xc0001e7da0, 0x2007180, 0xc000919760, 0xc00093af00)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
github.com/grafana/loki/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00014ee70, 0x2007180, 0xc000919760, 0xc00093af00)
	/Users/david/go/src/github.com/grafana/loki/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2007140, 0xc00002d780, 0xc00093ad00)
	/Users/david/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:49 +0x177
net/http.HandlerFunc.ServeHTTP(0xc0000ef8f0, 0x2007140, 0xc00002d780, 0xc00093ad00)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Log.Wrap.func1(0x200a880, 0xc000b43ef0, 0xc00093ad00)
	/Users/david/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/logging.go:41 +0x1a2
net/http.HandlerFunc.ServeHTTP(0xc0000ef920, 0x200a880, 0xc000b43ef0, 0xc00093ad00)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
net/http.Handler.ServeHTTP-fm(0x200a880, 0xc000b43ef0, 0xc00093ad00)
	/Users/david/go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:133 +0x4d
github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x2009480, 0xc0009a2c40, 0xc00093ac00)
	/Users/david/go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
net/http.HandlerFunc.ServeHTTP(0xc0000ef980, 0x2009480, 0xc0009a2c40, 0xc00093ac00)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Tracer.Wrap.func2(0x2009480, 0xc0009a2c40, 0xc00093ac00)
	/Users/david/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/http_tracing.go:39 +0x8f
net/http.HandlerFunc.ServeHTTP(0xc0000ef9b0, 0x2009480, 0xc0009a2c40, 0xc00093ac00)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc000148c30, 0x2009480, 0xc0009a2c40, 0xc00093ac00)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00094c280, 0x200b000, 0xc00002d580)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2851 +0x2f5
```

However, if I use a UTC timestamp, e.g., 
```
"entries": [{ "ts": "2019-02-11T13:12:06.801064Z", "line": "bazzzzzzz" }]
```
I can query for the line without any problem:
```
./logcli --addr="http://localhost:3100/" query '{foo="test"}'
http://localhost:3100//api/prom/query?query=%7Bfoo%3D%22test%22%7D&limit=30&start=1549887303446495000&end=1549890903446495000&direction=BACKWARD&regexp=
Common labels: {foo="test"}
2019-02-11T13:12:06Z {}                                                                                                   bazzzzzzz
```

**Comment by candlerb** [comment]
The example shown works for me, with loki c9948233.

Note that the query generated by logcli contained `start=1549379656914860020` and `end=1549383256914860020`.  Those times convert to:

```
irb(main):001:0> Time.at(1549379656914860020/1e9)
=> 2019-02-05 15:14:16 +0000
irb(main):002:0> Time.at(1549383256914860020/1e9)
=> 2019-02-05 16:14:16 +0000
```

The actual timestamp of the log message is outside of that range, and therefore it's not shown.  In fact, the timestamp of the log is in the future, compared to the end time given.

So trying it again, with exactly the same message and timestamp:

```
# curl -XPOST -H "Content-type: application/json" -d '{
"streams": [
{
"labels": "{foo=\"test\"}",
"entries": [{ "ts": "2019-02-05T17:12:06.801064-04:00", "line": "bazzzzzzz" }]
}
]
}' 'http://localhost:3100/api/prom/push'
```

Adding `--since 8000h` to show logs way back:

```
# ./logcli query '{foo="test"}' --since 8000h --addr="http://localhost:3100"
http://localhost:3100/api/prom/query?query=%7Bfoo%3D%22test%22%7D&limit=30&start=1526006320336764328&end=1554806320336764328&direction=BACKWARD&regexp=
Common labels: {foo="test"}
2019-02-05T21:12:06Z {}                                                                                                   bazzzzzzz
```

You can see that loki has correctly converted the log timestamp `17:12:06.801064-04:00` to `2019-02-05T21:12:06Z` (Note: the microseconds are missing, but that's just logcli hiding them. Doing the same query with curl shows them. Maybe logcli ought to have a flag to show the full timestamp)

----

One other note for anyone else trying to reproduce this: the original post is missing the backslashes before the double quotes in the labels field.  That's probably a github markdown issue.  You can avoid this if you surround code blocks with triple backticks on a line of their own.

**Comment by daixiang0** [comment]
seems that bug fixed, i can not reproduce it now.
