### ISSUE TITLE
Division by zero when retention_period is set to 0s

### ISSUE THREAD

**Issue by paramite** [grafana/loki#2989]
**Describe the bug**
Getting panic when retention_period: 0s is set. Loki does not panic when I set it to reasonable value (multiple of chunk period in chema_config).

**To Reproduce**
1. Start containerized Loki with following configuration:

```
cat > loki-config.yaml <EOF
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: s3
  aws:
   s3: <snip>
   s3forcepathstyle: true

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
EOF
$ podman run --network=host --volume=$PWD/loki-config.yaml:/etc/loki/local-config.yaml:ro grafana/loki
```

**Expected behavior**
Run without panic or clear explanation what configuration is wrong.

**Environment:**
 - Infrastructure: baremeral
 - Deployment tool: podman/docker

**Screenshots, Promtail config, or terminal output**

```
level=info ts=2020-11-25T13:26:49.119112689Z caller=module_service.go:58 msg=initialising module=ring                                                                       
level=info ts=2020-11-25T13:26:49.119160435Z caller=lifecycler.go:518 msg="not loading tokens from file, tokens file path is empty"                                         
level=info ts=2020-11-25T13:26:49.119215468Z caller=lifecycler.go:547 msg="instance not found in ring, adding with no tokens" ring=ingester                                 
level=info ts=2020-11-25T13:26:49.11920227Z caller=client.go:242 msg="value is nil" key=collectors/ring index=1                                                             
level=info ts=2020-11-25T13:26:49.119246939Z caller=module_service.go:58 msg=initialising module=distributor                                                                
level=info ts=2020-11-25T13:26:49.119275469Z caller=module_service.go:58 msg=initialising module=ingester-querier                                                           
level=info ts=2020-11-25T13:26:49.119300639Z caller=module_service.go:58 msg=initialising module=ruler                                                                      
level=info ts=2020-11-25T13:26:49.119315486Z caller=ruler.go:400 msg="ruler up and running"                                                                                 
level=info ts=2020-11-25T13:26:49.119363501Z caller=lifecycler.go:394 msg="auto-joining cluster after timeout" ring=ingester                                                
level=info ts=2020-11-25T13:26:49.119359219Z caller=loki.go:227 msg="Loki started"
panic: runtime error: integer divide by zero

goroutine 513 [running]:
github.com/cortexproject/cortex/pkg/chunk.(*PeriodicTableConfig).periodicTables(0xc00076b680, 0x17557e7a400, 0x175ff9ef568, 0x0, 0x3e8, 0x12c, 0x0, 0x0, 0x0, 0xbb8, ...)   
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/schema_config.go:374 +0x1079                                                                             
github.com/cortexproject/cortex/pkg/chunk.(*TableManager).calculateExpectedTables(0xc0008f0a80, 0x0, 0x0, 0x30)                                                             
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/table_manager.go:407 +0xb10                                                                              
github.com/cortexproject/cortex/pkg/chunk.(*TableManager).SyncTables(0xc0008f0a80, 0x2655120, 0xc000019a10, 0x71a9799, 0x1e6f3391ffc2cb)                                    
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/table_manager.go:323 +0x69                                                                               
github.com/cortexproject/cortex/pkg/chunk.(*TableManager).loop.func1(0x2655120, 0xc000019a10, 0x17, 0xbfe7b4c6471a9799)                                                     
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/table_manager.go:216 +0x3e                                                                               
github.com/weaveworks/common/instrument.CollectedRequest(0x26550a0, 0xc0000504a0, 0x2273986, 0x17, 0x26455a0, 0xc000916018, 0x23aeba8, 0xc00076bdd8, 0x225e21d, 0xd)        
        /src/loki/vendor/github.com/weaveworks/common/instrument/instrument.go:152 +0x271                                                                                   
github.com/cortexproject/cortex/pkg/chunk.(*TableManager).loop(0xc0008f0a80, 0x2655060, 0xc000ce6640, 0x0, 0x0)                                                             
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/table_manager.go:215 +0x16a                                                                              
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc000c40bd0)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:167 +0x405                                                                      
created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1                                                                               
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:96 +0xad    
```

**Comment by paramite** [comment]
Note that avoiding "s" from the configuration value fixes the issue.

**Comment by slim-bean** [comment]
Hey @paramite thanks for reporting and updating with what you discovered!

you shouldn't have:

```
chunks:
        prefix: chunk_
```

In the schema config as Loki does not use chunk tables at all (technically it could but I can't think of any normal use case for logs where you would want this, it would be very $$$)

The divide by zero panic isn't really a great output though, I agree. However the fix for this is gonna have to be done in cortex which is the source of the stack trace. If you would like to create an issue over there to better handle this situation I think that makes sense, for now I'm going to close this here though as nobody should really be using the `chunks` config which causes the issue.
