### ISSUE TITLE
Timerange with no values results in http handler panic

### ISSUE THREAD

**Issue by negbie** [grafana/loki#315]
```
loki              | 2019/02/11 17:50:30 http: panic serving 172.22.0.8:52894: runtime error: invalid memory address or nil pointer dereference
loki              | goroutine 82793 [running]:
loki              | net/http.(*conn).serve.func1(0xc069473d60)
loki              |     /usr/local/go/src/net/http/server.go:1746 +0xd0
loki              | panic(0x10c3880, 0x1e49980)
loki              |     /usr/local/go/src/runtime/panic.go:513 +0x1b9
loki              | github.com/grafana/loki/pkg/iter.(*queryClientIterator).Labels(0xc00130fa80, 0x1404200, 0xc00130fa80)
loki              |     /go/src/github.com/grafana/loki/pkg/iter/iterator.go:279 +0x2a
loki              | github.com/grafana/loki/pkg/iter.NewHeapIterator(0xc067c03ab0, 0x1, 0x1, 0x1, 0xc04e4f2760, 0x1)
loki              |     /go/src/github.com/grafana/loki/pkg/iter/iterator.go:123 +0x122
loki              | github.com/grafana/loki/pkg/querier.(*Querier).Query(0xc000392030, 0x1401ec0, 0xc0257e13e0, 0xc00c3d26c0, 0x0, 0x0, 0x0)
loki              |     /go/src/github.com/grafana/loki/pkg/querier/querier.go:106 +0x1ea
loki              | github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler(0xc000392030, 0x1401580, 0xc06c039be0, 0xc011f59800)
loki              |     /go/src/github.com/grafana/loki/pkg/querier/http.go:100 +0x537
loki              | github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler-fm(0x1401580, 0xc06c039be0, 0xc011f59800)
loki              |     /go/src/github.com/grafana/loki/pkg/loki/modules.go:145 +0x48
loki              | net/http.HandlerFunc.ServeHTTP(0xc0000861c0, 0x1401580, 0xc06c039be0, 0xc011f59800)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | github.com/grafana/loki/pkg/loki.glob..func1.1(0x1401580, 0xc06c039be0, 0xc011f59700)
loki              |     /go/src/github.com/grafana/loki/pkg/loki/fake_auth.go:18 +0x13b
loki              | net/http.HandlerFunc.ServeHTTP(0xc00000a0e0, 0x1401580, 0xc06c039be0, 0xc011f59700)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | net/http.Handler.ServeHTTP-fm(0x1401580, 0xc06c039be0, 0xc011f59700)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:133 +0x4d
loki              | github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x13fdfc0, 0xc06c039b80, 0xc011f59600)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
loki              | net/http.HandlerFunc.ServeHTTP(0xc000392090, 0x13fdfc0, 0xc06c039b80, 0xc011f59600)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | github.com/grafana/loki/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000170d20, 0x13fdfc0, 0xc06c039b80, 0xc011f59600)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
loki              | github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x13fdf80, 0xc00130f8c0, 0xc011f59400)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:49 +0x177
loki              | net/http.HandlerFunc.ServeHTTP(0xc0004afc80, 0x13fdf80, 0xc00130f8c0, 0xc011f59400)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Log.Wrap.func1(0x14016c0, 0xc005db5b80, 0xc011f59400)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/logging.go:41 +0x1a2
loki              | net/http.HandlerFunc.ServeHTTP(0xc0004afcb0, 0x14016c0, 0xc005db5b80, 0xc011f59400)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | net/http.Handler.ServeHTTP-fm(0x14016c0, 0xc005db5b80, 0xc011f59400)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:133 +0x4d
loki              | github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x14002c0, 0xc000a1db20, 0xc011f59300)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
loki              | net/http.HandlerFunc.ServeHTTP(0xc0004afd10, 0x14002c0, 0xc000a1db20, 0xc011f59300)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Tracer.Wrap.func2(0x14002c0, 0xc000a1db20, 0xc011f59300)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/http_tracing.go:39 +0x8f
loki              | net/http.HandlerFunc.ServeHTTP(0xc0004afd40, 0x14002c0, 0xc000a1db20, 0xc011f59300)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | net/http.serverHandler.ServeHTTP(0xc000102680, 0x14002c0, 0xc000a1db20, 0xc011f59300)
loki              |     /usr/local/go/src/net/http/server.go:2741 +0xab
loki              | net/http.(*conn).serve(0xc069473d60, 0x1401e00, 0xc01945f740)
loki              |     /usr/local/go/src/net/http/server.go:1847 +0x646
loki              | created by net/http.(*Server).Serve
loki              |     /usr/local/go/src/net/http/server.go:2851 +0x2f5
loki              | 2019/02/11 17:50:30 http: panic serving 172.22.0.8:52924: runtime error: invalid memory address or nil pointer dereference
loki              | goroutine 82830 [running]:
loki              | net/http.(*conn).serve.func1(0xc005b494a0)
loki              |     /usr/local/go/src/net/http/server.go:1746 +0xd0
loki              | panic(0x10c3880, 0x1e49980)
loki              |     /usr/local/go/src/runtime/panic.go:513 +0x1b9
loki              | github.com/grafana/loki/pkg/iter.(*queryClientIterator).Labels(0xc00cdb2f00, 0x1404200, 0xc00cdb2f00)
loki              |     /go/src/github.com/grafana/loki/pkg/iter/iterator.go:279 +0x2a
loki              | github.com/grafana/loki/pkg/iter.NewHeapIterator(0xc01a206400, 0x1, 0x1, 0x1, 0xc067c03cd0, 0x1)
loki              |     /go/src/github.com/grafana/loki/pkg/iter/iterator.go:123 +0x122
loki              | github.com/grafana/loki/pkg/querier.(*Querier).Query(0xc000392030, 0x1401ec0, 0xc00e46db30, 0xc04e67cea0, 0x0, 0x0, 0x0)
loki              |     /go/src/github.com/grafana/loki/pkg/querier/querier.go:106 +0x1ea
loki              | github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler(0xc000392030, 0x1401580, 0xc024d909a0, 0xc06cc55000)
loki              |     /go/src/github.com/grafana/loki/pkg/querier/http.go:100 +0x537
loki              | github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler-fm(0x1401580, 0xc024d909a0, 0xc06cc55000)
loki              |     /go/src/github.com/grafana/loki/pkg/loki/modules.go:145 +0x48
loki              | net/http.HandlerFunc.ServeHTTP(0xc0000861c0, 0x1401580, 0xc024d909a0, 0xc06cc55000)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | github.com/grafana/loki/pkg/loki.glob..func1.1(0x1401580, 0xc024d909a0, 0xc06cc54f00)
loki              |     /go/src/github.com/grafana/loki/pkg/loki/fake_auth.go:18 +0x13b
loki              | net/http.HandlerFunc.ServeHTTP(0xc00000a0e0, 0x1401580, 0xc024d909a0, 0xc06cc54f00)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | net/http.Handler.ServeHTTP-fm(0x1401580, 0xc024d909a0, 0xc06cc54f00)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:133 +0x4d
loki              | github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x13fdfc0, 0xc024d90940, 0xc06cc54e00)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
loki              | net/http.HandlerFunc.ServeHTTP(0xc000392090, 0x13fdfc0, 0xc024d90940, 0xc06cc54e00)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | github.com/grafana/loki/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000170d20, 0x13fdfc0, 0xc024d90940, 0xc06cc54e00)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
loki              | github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x13fdf80, 0xc00cdb2d40, 0xc06cc54c00)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:49 +0x177
loki              | net/http.HandlerFunc.ServeHTTP(0xc0004afc80, 0x13fdf80, 0xc00cdb2d40, 0xc06cc54c00)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Log.Wrap.func1(0x14016c0, 0xc081f07360, 0xc06cc54c00)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/logging.go:41 +0x1a2
loki              | net/http.HandlerFunc.ServeHTTP(0xc0004afcb0, 0x14016c0, 0xc081f07360, 0xc06cc54c00)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | net/http.Handler.ServeHTTP-fm(0x14016c0, 0xc081f07360, 0xc06cc54c00)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:133 +0x4d
loki              | github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x14002c0, 0xc02271ddc0, 0xc03783e100)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
loki              | net/http.HandlerFunc.ServeHTTP(0xc0004afd10, 0x14002c0, 0xc02271ddc0, 0xc03783e100)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Tracer.Wrap.func2(0x14002c0, 0xc02271ddc0, 0xc03783e100)
loki              |     /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/http_tracing.go:39 +0x8f
loki              | net/http.HandlerFunc.ServeHTTP(0xc0004afd40, 0x14002c0, 0xc02271ddc0, 0xc03783e100)
loki              |     /usr/local/go/src/net/http/server.go:1964 +0x44
loki              | net/http.serverHandler.ServeHTTP(0xc000102680, 0x14002c0, 0xc02271ddc0, 0xc03783e100)
loki              |     /usr/local/go/src/net/http/server.go:2741 +0xab
loki              | net/http.(*conn).serve(0xc005b494a0, 0x1401e00, 0xc0283d0880)
loki              |     /usr/local/go/src/net/http/server.go:1847 +0x646
loki              | created by net/http.(*Server).Serve
loki              |     /usr/local/go/src/net/http/server.go:2851 +0x2f5
grafana           | t=2019-02-11T17:50:30+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/2/api/prom/query status=502 remote_addr=172.22.0.1 time_ms=12 size=0 referer="http://localhost:3000/explore?left=%5B%22now-3h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22heplify-server%5C%22%7D%20419C10BB8F153%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D"
grafana           | 2019/02/11 17:50:30 http: proxy error: EOF
grafana           | 2019/02/11 17:50:30 http: proxy error: EOF
grafana           | t=2019-02-11T17:50:30+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/2/api/prom/query status=502 remote_addr=172.22.0.1 time_ms=5 size=0 referer="http://localhost:3000/explore?left=%5B%22now-3h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bjob%3D%5C%22heplify-server%5C%22%7D%20419C10BB8F153%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D"
```

**Comment by tomwilkie** [comment]
Thanks @negbie - I think #341 fixes this.

**Comment by tomwilkie** [comment]
Yeah, fixed.
