### ISSUE TITLE
Promtail 'latest' crashing on Digital Ocean Kubernetes 1.18

### ISSUE THREAD

**Issue by DGollings** [grafana/loki#3289]
**Describe the bug**
Promtail 'latest' crashloops

**To Reproduce**
Install using 
`curl -fsS https://raw.githubusercontent.com/grafana/loki/master/tools/promtail.sh | sh -s (redacted) | kubectl apply --namespace=default -f  -`
as mentioned on grafana cloud page

**Expected behavior**
Not crashing

**Fix**
Downgrade manually to version 2.0.1
Might I suggest (creating and) using :stable instead of :latest in promtail.sh?

**Environment:**
`level=info ts=2021-02-04T13:31:43.81776936Z caller=main.go:110 msg="Starting Promtail" version="(version=gcplog-labels-fix-e794bd0, branch=gcplog-labels-fix, revision=e794bd0b)"`
Digital Ocean Kubernetes 1.18

**Screenshots, Promtail config, or terminal output**
```
panic: runtime error: index out of range [-1]
        panic: runtime error: index out of range [-1]

goroutine 245 [running]:
github.com/grafana/loki/pkg/logproto.encodeVarintLogproto(0xc001a8dd71, 0x74e, 0x74e, 0x1, 0x1ed, 0xc0010b3078)
        /src/loki/pkg/logproto/logproto.pb.go:4246 +0xbd
github.com/grafana/loki/pkg/logproto.(*Stream).MarshalTo(0xc00157db98, 0xc001a8dd71, 0x74e, 0x74e, 0xc0010b3188, 0xc7b46b, 0xc0010b3138)
        /src/loki/pkg/logproto/types.go:41 +0x8f
github.com/grafana/loki/pkg/logproto.(*PushRequest).MarshalToSizedBuffer(0xc000d08a00, 0xc001a48000, 0x464bf, 0x464bf, 0x101, 0xc0010b3118, 0xc0010b31a8)
        /src/loki/pkg/logproto/logproto.pb.go:3202 +0x125
github.com/grafana/loki/pkg/logproto.(*PushRequest).XXX_Marshal(0xc000d08a00, 0xc001a48000, 0x0, 0x464bf, 0xc000d08a00, 0x1, 0x0, 0x26e1fc0, 0xc000cfa5d0, 0xc000f55500)
        /src/loki/pkg/logproto/logproto.pb.go:78 +0x5b
github.com/gogo/protobuf/proto.Marshal(0x310be60, 0xc000d08a00, 0x622, 0x0, 0x0, 0x0, 0x0)
        /src/loki/vendor/github.com/gogo/protobuf/proto/table_marshal.go:2940 +0x2db
github.com/grafana/loki/pkg/promtail/client.(*batch).encode(0xc000cfa5a0, 0x2568d60, 0x7f7620ada0c0, 0x0, 0x0, 0xc0010b3320, 0x41924f)
        /src/loki/pkg/promtail/client/batch.go:76 +0x49
github.com/grafana/loki/pkg/promtail/client.(*client).sendBatch(0xc0009c1cc0, 0x0, 0x0, 0xc000cfa5a0)
        /src/loki/pkg/promtail/client/client.go:274 +0x45
github.com/grafana/loki/pkg/promtail/client.(*client).run.func1(0xc0010b3da0, 0xc0009c1cc0)
        /src/loki/pkg/promtail/client/client.go:222 +0xab
panic(0x29a16a0, 0xc000991ce0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/grafana/loki/pkg/logproto.encodeVarintLogproto(0xc001a45cf6, 0x7c9, 0x7c9, 0x1, 0x176, 0xc0010b3800)
        /src/loki/pkg/logproto/logproto.pb.go:4246 +0xbd
github.com/grafana/loki/pkg/logproto.(*Stream).MarshalTo(0xc00157d798, 0xc001a45cf6, 0x7c9, 0x7c9, 0x48000, 0xc7b46b, 0xc0010b38c0)
        /src/loki/pkg/logproto/types.go:41 +0x8f
github.com/grafana/loki/pkg/logproto.(*PushRequest).MarshalToSizedBuffer(0xc000d089e0, 0xc001a00000, 0x464bf, 0x464bf, 0x101, 0xc0010b38a0, 0xc0010b3930)
        /src/loki/pkg/logproto/logproto.pb.go:3202 +0x125
github.com/grafana/loki/pkg/logproto.(*PushRequest).XXX_Marshal(0xc000d089e0, 0xc001a00000, 0x0, 0x464bf, 0xc000d08900, 0x1, 0x0, 0x26e1fc0, 0xc000cfa5d0, 0xc000f55500)
        /src/loki/pkg/logproto/logproto.pb.go:78 +0x5b
github.com/gogo/protobuf/proto.Marshal(0x310be60, 0xc000d089e0, 0x622, 0xc0010b3a18, 0x48d19c, 0x429ffa0, 0xc000c08800)
        /src/loki/vendor/github.com/gogo/protobuf/proto/table_marshal.go:2940 +0x2db
github.com/grafana/loki/pkg/promtail/client.(*batch).encode(0xc000cfa5a0, 0xc0010b3a98, 0x4f9aeb, 0xc0000385b0, 0xc00016b400, 0x12d, 0xc0019f0500)
        /src/loki/pkg/promtail/client/batch.go:76 +0x49
github.com/grafana/loki/pkg/promtail/client.(*client).sendBatch(0xc0009c1cc0, 0x0, 0x0, 0xc000cfa5a0)
        /src/loki/pkg/promtail/client/client.go:274 +0x45
github.com/grafana/loki/pkg/promtail/client.(*client).run(0xc0009c1cc0)
        /src/loki/pkg/promtail/client/client.go:262 +0x6b7
created by github.com/grafana/loki/pkg/promtail/client.New
        /src/loki/pkg/promtail/client/client.go:198 +0x4b2
        ```

**Comment by DGollings** [comment]
np, thanks :)

**Comment by slim-bean** [comment]
Thanks for this issue @DGollings , we are also going to look to update that script to use a release tag and not `latest` to avoid anything like this for anyone in the future.
