### ISSUE TITLE
Query {cluster=""} results in 502

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#330]

**Comment by tomwilkie** [comment]
I wonder if its this:

```
2019/02/18 13:51:51 http: panic serving 10.56.1.55:54828: runtime error: invalid memory address or nil pointer dereference
goroutine 479706 [running]:
net/http.(*conn).serve.func1(0xc0001a0f00)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x10c3880, 0x1e49980)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/grafana/loki/pkg/iter.(*queryClientIterator).Labels(0xc00025a1c0, 0x1404200, 0xc00025a240)
	/go/src/github.com/grafana/loki/pkg/iter/iterator.go:279 +0x2a
github.com/grafana/loki/pkg/iter.NewHeapIterator(0xc0010ee960, 0x3, 0x3, 0x1, 0xc002bd8570, 0x3)
	/go/src/github.com/grafana/loki/pkg/iter/iterator.go:123 +0x122
github.com/grafana/loki/pkg/querier.(*Querier).Query(0xc00094ee70, 0x1401ec0, 0xc000a022d0, 0xc000a49c20, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/loki/pkg/querier/querier.go:106 +0x1ea
github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler(0xc00094ee70, 0x1401580, 0xc0005e0b40, 0xc0005b6300)
	/go/src/github.com/grafana/loki/pkg/querier/http.go:100 +0x537
github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler-fm(0x1401580, 0xc0005e0b40, 0xc0005b6300)
	/go/src/github.com/grafana/loki/pkg/loki/modules.go:145 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0009e4410, 0x1401580, 0xc0005e0b40, 0xc0005b6300)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.glob..func1.1(0x1401580, 0xc0005e0b40, 0xc0005b6200)
	/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/http_auth.go:17 +0x122
net/http.HandlerFunc.ServeHTTP(0xc0008a6b20, 0x1401580, 0xc0005e0b40, 0xc0005b6200)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.Handler.ServeHTTP-fm(0x1401580, 0xc0005e0b40, 0xc0005b6200)
	/go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:133 +0x4d
github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x13fdfc0, 0xc0005e0ae0, 0xc0005b6100)
	/go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
net/http.HandlerFunc.ServeHTTP(0xc00094eed0, 0x13fdfc0, 0xc0005e0ae0, 0xc0005b6100)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/grafana/loki/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000156310, 0x13fdfc0, 0xc0005e0ae0, 0xc0005b6100)
	/go/src/github.com/grafana/loki/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x13fdf80, 0xc001d7d340, 0xc0001f5f00)
	/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:49 +0x177
net/http.HandlerFunc.ServeHTTP(0xc00094eb70, 0x13fdf80, 0xc001d7d340, 0xc0001f5f00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Log.Wrap.func1(0x14016c0, 0xc000616af0, 0xc0001f5f00)
	/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/logging.go:41 +0x1a2
net/http.HandlerFunc.ServeHTTP(0xc00094eba0, 0x14016c0, 0xc000616af0, 0xc0001f5f00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.Handler.ServeHTTP-fm(0x14016c0, 0xc000616af0, 0xc0001f5f00)
	/go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:133 +0x4d
github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x14002c0, 0xc000208700, 0xc0001f5e00)
	/go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
net/http.HandlerFunc.ServeHTTP(0xc00094ec00, 0x14002c0, 0xc000208700, 0xc0001f5e00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Tracer.Wrap.func2(0x14002c0, 0xc000208700, 0xc0001f5e00)
	/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/http_tracing.go:39 +0x8f
net/http.HandlerFunc.ServeHTTP(0xc00094ec30, 0x14002c0, 0xc000208700, 0xc0001f5e00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc00039a270, 0x14002c0, 0xc000208700, 0xc0001f5e00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0001a0f00, 0x1401e00, 0xc001d7d280)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by tomwilkie** [comment]
Which would mean #341 fixes this too.

**Comment by tomwilkie** [comment]
Dupe of #315
