### ISSUE TITLE
#<NoMethodError: undefined method `append' for #<Array:0x4637b86a>>

### ISSUE THREAD

**Issue by pmanno** [grafana/loki#3349]
**Describe the bug**
Enabling loki output plugin crashes logstash UDP listener.

**To Reproduce**
added following block to output in logstash config
  loki {
    url => "http://<loki_host>:3100/loki/api/v1/push"
    message_field => "message"
    tenant_id => "tenant"
  }

**Expected behavior**
Logs appear in loki

**Environment:**
logstash_version: 6.2.4

**Screenshots, Promtail config, or terminal output**
[2021-02-17T14:47:46,313][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `append' for #<Array:0x4637b86a>>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-loki-1.0.3/lib/logstash/outputs/loki/batch.rb:25:in `add'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-loki-1.0.3/lib/logstash/outputs/loki.rb:190:in `add_entry_to_batch'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-loki-1.0.3/lib/logstash/outputs/loki.rb:99:in `block in max_batch_size'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-loki-1.0.3/lib/logstash/outputs/loki.rb:98:in `block in max_batch_size'", "org/jruby/RubyKernel.java:1292:in `loop'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-loki-1.0.3/lib/logstash/outputs/loki.rb:90:in `max_batch_size'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-loki-1.0.3/lib/logstash/outputs/loki.rb:86:in `block in register'"]}

**Comment by pmanno** [comment]
Updating Logstash to v 7.11.0 seems to have fixed this.
