### ISSUE TITLE
Promtail on arm (raspberry pi 3B) built against journald frequently crashes with SIGABRT: "runtime/cgo: pthread_create failed: Resource temporarily unavailable"

### ISSUE THREAD

**Issue by growse** [grafana/loki#3406]
**Describe the bug**
Promtail v2.1.0 built for arm with golang 1.16 against libsystemd-dev running on a raspberry pi 3 crashes periodically with a `SIGABRT` and the error `runtime/cgo: pthread_create failed: Resource temporarily unavailable`.

This is built-from-source binary, as the official arm releases are not built with journald support. The makefile for building this is here: https://github.com/growse/promtail-package/blob/master/GNUmakefile - but I think I use similar (if not the same) build options as the official binaries.

Initially, I thought this was a memory constraint issue, but looking at the other processes shows that there should be memory available, and the swap space is completely unused.

**To Reproduce**
1. Start promtail v2.1.0 as built per above
2. Observe panic.

**Expected behavior**
Not to panic....?

**Environment:**
 - Bare metal, raspberry pi 3B, rootfs is on NFS.
 - Raspbian buster, up to date
 - 2GB of swap configured on a loopback
 - Installed from Deb file that I created, available at https://apttoo.growse.com/pool/main/p/promtail/promtail_2.1.0-47_armhf.deb

**Screenshots, Promtail config, or terminal output**
Promtail output:
```
Mar 01 13:42:06 pbxbot systemd[1]: Started Loki Promtail Agent.
Mar 01 13:42:08 pbxbot promtail[765]: level=info ts=2021-03-01T13:42:08.403237115Z caller=server.go:225 http=[::]:39497 grpc=[::]:43013 msg="server listening on addresses"
Mar 01 13:42:08 pbxbot promtail[765]: level=info ts=2021-03-01T13:42:08.407812683Z caller=main.go:110 msg="Starting Promtail" version="(version=2.1.0, branch=HEAD, revision=1b79df3)"
Mar 01 13:42:08 pbxbot promtail[765]: runtime/cgo: pthread_create failed: Resource temporarily unavailable
Mar 01 13:42:08 pbxbot promtail[765]: runtime/cgo: pthread_create failed: Resource temporarily unavailable
Mar 01 13:42:08 pbxbot promtail[765]: SIGABRT: abort
Mar 01 13:42:08 pbxbot promtail[765]: PC=0x76d6af24 m=6 sigcode=4294967290
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 0 [idle]:
Mar 01 13:42:08 pbxbot promtail[765]: runtime: unknown pc 0x76d6af24
Mar 01 13:42:08 pbxbot promtail[765]: stack: frame={sp:0x644fea08, fp:0x0} stack=[0x63cff214,0x644fee14)
Mar 01 13:42:08 pbxbot promtail[765]: 644fe988:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe998:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9a8:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9b8:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9c8:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9d8:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9e8:  00000000  00000006  00000000  03fb2348
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9f8:  0405e900  644fea8c  76f1d968  76d6aea8
Mar 01 13:42:08 pbxbot promtail[765]: 644fea08: <00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea18:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea28:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea38:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea48:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea58:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea68:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea78:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: runtime: unknown pc 0x76d6af24
Mar 01 13:42:08 pbxbot promtail[765]: stack: frame={sp:0x644fea08, fp:0x0} stack=[0x63cff214,0x644fee14)
Mar 01 13:42:08 pbxbot promtail[765]: 644fe988:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe998:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9a8:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9b8:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9c8:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9d8:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9e8:  00000000  00000006  00000000  03fb2348
Mar 01 13:42:08 pbxbot promtail[765]: 644fe9f8:  0405e900  644fea8c  76f1d968  76d6aea8
Mar 01 13:42:08 pbxbot promtail[765]: 644fea08: <00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea18:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea28:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea38:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea48:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea58:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea68:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: 644fea78:  00000000  00000000  00000000  00000000
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 1 [chan receive]:
Mar 01 13:42:08 pbxbot promtail[765]: github.com/weaveworks/common/server.(*Server).Run(0x4483b00, 0x0, 0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/server/server.go:402 +0x11c
Mar 01 13:42:08 pbxbot promtail[765]: github.com/grafana/loki/pkg/promtail.(*Promtail).Run(0x44817a0, 0x4914040, 0x4)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/pkg/promtail/promtail.go:98 +0x7c
Mar 01 13:42:08 pbxbot promtail[765]: main.main()
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/cmd/promtail/main.go:113 +0x40c
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 4 [chan receive]:
Mar 01 13:42:08 pbxbot promtail[765]: k8s.io/klog.(*loggingT).flushDaemon(0x2ce7888)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/k8s.io/klog/klog.go:1010 +0x70
Mar 01 13:42:08 pbxbot promtail[765]: created by k8s.io/klog.init.0
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/k8s.io/klog/klog.go:411 +0xf8
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 157 [chan receive]:
Mar 01 13:42:08 pbxbot promtail[765]: go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0x445dd20)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x2ec
Mar 01 13:42:08 pbxbot promtail[765]: created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x68
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 46 [select]:
Mar 01 13:42:08 pbxbot promtail[765]: go.opencensus.io/stats/view.(*worker).start(0x4474c60)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/go.opencensus.io/stats/view/worker.go:276 +0xa0
Mar 01 13:42:08 pbxbot promtail[765]: created by go.opencensus.io/stats/view.init.0
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/go.opencensus.io/stats/view/worker.go:34 +0x58
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 47 [chan receive]:
Mar 01 13:42:08 pbxbot promtail[765]: k8s.io/klog/v2.(*loggingT).flushDaemon(0x2ce7908)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/k8s.io/klog/v2/klog.go:1131 +0x70
Mar 01 13:42:08 pbxbot promtail[765]: created by k8s.io/klog/v2.init.0
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/k8s.io/klog/v2/klog.go:416 +0xf8
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 265 [runnable]:
Mar 01 13:42:08 pbxbot promtail[765]: github.com/grafana/loki/pkg/promtail/client.(*client).run(0x4484c60)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/pkg/promtail/client/client.go:201 +0x170
Mar 01 13:42:08 pbxbot promtail[765]: created by github.com/grafana/loki/pkg/promtail/client.New
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/pkg/promtail/client/client.go:170 +0x2e0
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 195 [chan receive]:
Mar 01 13:42:08 pbxbot promtail[765]: go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0x447f0b0)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x2ec
Mar 01 13:42:08 pbxbot promtail[765]: created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x68
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 198 [chan receive]:
Mar 01 13:42:08 pbxbot promtail[765]: go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0x447f1d0)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x2ec
Mar 01 13:42:08 pbxbot promtail[765]: created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x68
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 266 [select]:
Mar 01 13:42:08 pbxbot promtail[765]: github.com/grafana/loki/pkg/promtail/positions.(*positions).run(0x4481830)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/pkg/promtail/positions/positions.go:153 +0xcc
Mar 01 13:42:08 pbxbot promtail[765]: created by github.com/grafana/loki/pkg/promtail/positions.New
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/pkg/promtail/positions/positions.go:95 +0xf8
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 277 [running]:
Mar 01 13:42:08 pbxbot promtail[765]:         goroutine running on other thread; stack unavailable
Mar 01 13:42:08 pbxbot promtail[765]: created by github.com/weaveworks/common/server.(*Server).Run
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/server/server.go:361 +0x4c
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 251 [running]:
Mar 01 13:42:08 pbxbot promtail[765]:         goroutine running on other thread; stack unavailable
Mar 01 13:42:08 pbxbot promtail[765]: created by github.com/grafana/loki/pkg/promtail/targets/journal.journalTargetWithReader
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/pkg/promtail/targets/journal/journaltarget.go:182 +0x2fc
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 278 [IO wait]:
Mar 01 13:42:08 pbxbot promtail[765]: internal/poll.runtime_pollWait(0x6584ddd0, 0x72, 0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/netpoll.go:222 +0x44
Mar 01 13:42:08 pbxbot promtail[765]: internal/poll.(*pollDesc).wait(0x413ce24, 0x72, 0x0, 0x0, 0x1b3c797)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/internal/poll/fd_poll_runtime.go:87 +0x30
Mar 01 13:42:08 pbxbot promtail[765]: internal/poll.(*pollDesc).waitRead(...)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/internal/poll/fd_poll_runtime.go:92
Mar 01 13:42:08 pbxbot promtail[765]: internal/poll.(*FD).Accept(0x413ce10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/internal/poll/fd_unix.go:401 +0x1e4
Mar 01 13:42:08 pbxbot promtail[765]: net.(*netFD).accept(0x413ce10, 0x18, 0x76cfd538, 0x18)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/net/fd_unix.go:172 +0x20
Mar 01 13:42:08 pbxbot promtail[765]: net.(*TCPListener).accept(0x400f790, 0x126958, 0x18, 0x19e9ec0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/net/tcpsock_posix.go:139 +0x20
Mar 01 13:42:08 pbxbot promtail[765]: net.(*TCPListener).Accept(0x400f790, 0x40428e8, 0x446be38, 0x18939f0, 0x2c60eb8)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/net/tcpsock.go:261 +0x54
Mar 01 13:42:08 pbxbot promtail[765]: net/http.(*Server).Serve(0x446bdd0, 0x2014c0c, 0x400f790, 0x0, 0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/net/http/server.go:2981 +0x230
Mar 01 13:42:08 pbxbot promtail[765]: github.com/weaveworks/common/server.(*Server).Run.func2(0x4483b00, 0x42abbc0)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/server/server.go:372 +0x100
Mar 01 13:42:08 pbxbot promtail[765]: created by github.com/weaveworks/common/server.(*Server).Run
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/server/server.go:369 +0x70
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 290 [syscall]:
Mar 01 13:42:08 pbxbot promtail[765]: os/signal.signal_recv(0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/sigqueue.go:168 +0x158
Mar 01 13:42:08 pbxbot promtail[765]: os/signal.loop()
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/os/signal/signal_unix.go:23 +0x14
Mar 01 13:42:08 pbxbot promtail[765]: created by os/signal.Notify.func1.1
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/os/signal/signal.go:151 +0x34
Mar 01 13:42:08 pbxbot promtail[765]: goroutine 279 [IO wait]:
Mar 01 13:42:08 pbxbot promtail[765]: internal/poll.runtime_pollWait(0x6584dd38, 0x72, 0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/netpoll.go:222 +0x44
Mar 01 13:42:08 pbxbot promtail[765]: internal/poll.(*pollDesc).wait(0x413ce74, 0x72, 0x0, 0x0, 0x1b3c797)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/internal/poll/fd_poll_runtime.go:87 +0x30
Mar 01 13:42:08 pbxbot promtail[765]: internal/poll.(*pollDesc).waitRead(...)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/internal/poll/fd_poll_runtime.go:92
Mar 01 13:42:08 pbxbot promtail[765]: internal/poll.(*FD).Accept(0x413ce60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/internal/poll/fd_unix.go:401 +0x1e4
Mar 01 13:42:08 pbxbot promtail[765]: net.(*netFD).accept(0x413ce60, 0x4121568, 0x405df90, 0x12ee0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/net/fd_unix.go:172 +0x20
Mar 01 13:42:08 pbxbot promtail[765]: net.(*TCPListener).accept(0x400f7a0, 0x0, 0x515148, 0x41db3b0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/net/tcpsock_posix.go:139 +0x20
Mar 01 13:42:08 pbxbot promtail[765]: net.(*TCPListener).Accept(0x400f7a0, 0x1, 0x1, 0x4121500, 0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /opt/hostedtoolcache/go/1.16.0/x64/src/net/tcpsock.go:261 +0x54
Mar 01 13:42:08 pbxbot promtail[765]: google.golang.org/grpc.(*Server).Serve(0x41db300, 0x2014c0c, 0x400f7a0, 0x0, 0x0)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/google.golang.org/grpc/server.go:621 +0x190
Mar 01 13:42:08 pbxbot promtail[765]: github.com/weaveworks/common/server.(*Server).Run.func3(0x4483b00, 0x42abbc0)
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/server/server.go:391 +0x30
Mar 01 13:42:08 pbxbot promtail[765]: created by github.com/weaveworks/common/server.(*Server).Run
Mar 01 13:42:08 pbxbot promtail[765]:         /home/runner/work/promtail-package/promtail-package/gopath/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/server/server.go:390 +0xf8
Mar 01 13:42:08 pbxbot promtail[765]: trap    0x0
Mar 01 13:42:08 pbxbot promtail[765]: error   0x0
Mar 01 13:42:08 pbxbot promtail[765]: oldmask 0x0
Mar 01 13:42:08 pbxbot promtail[765]: r0      0x0
Mar 01 13:42:08 pbxbot promtail[765]: r1      0x644fea0c
Mar 01 13:42:08 pbxbot promtail[765]: r2      0x0
Mar 01 13:42:08 pbxbot promtail[765]: r3      0x8
Mar 01 13:42:08 pbxbot promtail[765]: r4      0x76f1d968
Mar 01 13:42:08 pbxbot promtail[765]: r5      0x6
Mar 01 13:42:08 pbxbot promtail[765]: r6      0x644fea0c
Mar 01 13:42:08 pbxbot promtail[765]: r7      0xaf
Mar 01 13:42:08 pbxbot promtail[765]: r8      0x405e900
Mar 01 13:42:08 pbxbot promtail[765]: r9      0x644ff450
Mar 01 13:42:08 pbxbot promtail[765]: r10     0x4000b60
Mar 01 13:42:08 pbxbot promtail[765]: fp      0x2c600ec
Mar 01 13:42:08 pbxbot promtail[765]: ip      0x0
Mar 01 13:42:08 pbxbot promtail[765]: sp      0x644fea08
Mar 01 13:42:08 pbxbot promtail[765]: lr      0xffffffff
Mar 01 13:42:08 pbxbot promtail[765]: pc      0x76d6af24
Mar 01 13:42:08 pbxbot promtail[765]: cpsr    0x10
Mar 01 13:42:08 pbxbot promtail[765]: fault   0x0
Mar 01 13:42:08 pbxbot systemd[1]: promtail.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 01 13:42:08 pbxbot systemd[1]: promtail.service: Failed with result 'exit-code'.
```
Promtail.yml
```
---
server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /var/tmp/promtail-positions.yaml

client:
  url: https://loki/api/prom/push

scrape_configs:
-   job_name: journal
    journal:
        labels:
            job: systemd-journal
        path: /var/log/journal
    relabel_configs:
    -   source_labels:
        - __journal__systemd_unit
        target_label: system_unit
    -   source_labels:
        - __journal_priority
        target_label: system_priority
    -   source_labels:
        - __journal__hostname
        target_label: system_hostname
    -   source_labels:
        - __journal__transport
        target_label: system_transport
```

```
# free -m
              total        used        free      shared  buff/cache   available
Mem:            924         149         259           0         515         729
Swap:          1851           0        1851
```

**Comment by rayslava** [comment]
Just met the exactly same error on ArchLinux
Is there any solution?

**Comment by jeschkies** [comment]
We've recently started publishing promtail papers with journald support for ARM would that help?

**Comment by rayslava** [comment]
It seems that the error was a result of wrong value in `positions.yaml`, removing the file resolved the issue.
