### ISSUE TITLE
Promtail panic when it's not able to access logs 

### ISSUE THREAD

**Issue by hasonhai** [grafana/loki#345]
**Describe the bug**
When log files of some pods are not accessible, promtail panic. Promtail Pod falls into CrashLoopBackOff.

**Expected behavior**
Promtail should only print out error with the pod name that it cannot access the log instead of a panic and fail.  

**Environment:**
 - Infrastructure: Kubernetes 1.13
 - Deployment tool: helm

**Screenshots, promtail config, or terminal output**
Some promtail pod falls into CrashLoopBackOff when promtail cannot access pod's logs
```
[sonhaiha@xxxxapp471 ]$ k get po -n admin-apps | grep "loki"
loki-567f5d9b9-mj2df                                     1/1     Running            0          4d18h
loki-promtail-2wn8k                                      1/1     Running            0          4d18h
loki-promtail-fl4qw                                      1/1     Running            0          4d18h
loki-promtail-lztsp                                      0/1     CrashLoopBackOff   950        4d18h
loki-promtail-mlbj7                                      0/1     CrashLoopBackOff   938        4d18h
loki-promtail-ms8q9                                      1/1     Running            0          4d18h
loki-promtail-t2b5w                                      0/1     CrashLoopBackOff   938        4d18h
loki-promtail-vdh8h                                      1/1     Running            0          4d18h
loki-promtail-xz58j                                      1/1     Running            0          4d18h

```
Log output from promtail
```
2019/02/20 08:43:50 Seeked /var/lib/docker/containers/8fc54b2a1a1de25e8c1a79087862b8832d44f45888781320beb98ff776e369e3/8fc54b2a1a1de25e8c1a79087862b8832d44f45888781320beb98ff776e369e3-json.log - &{Offset:0 Whence:0}
level=info ts=2019-02-20T08:43:50.203183677Z caller=tailer.go:78 msg="start tailing file" path=/var/log/pods/0dd65c0c-3130-11e9-9e9f-001dd8b71f6b/loki/931.log
level=info ts=2019-02-20T08:43:50.203330077Z caller=filetargetmanager.go:170 msg="Adding target" key="{app=\"prometheus-node-exporter\", chart=\"prometheus-node-exporter-1.2.0\", container_name=\"node-exporter\", controller_revision_hash=\"6478b9d88b\", heritage=\"Tiller\", instance=\"xxxx-prometheus-prometheus-node-exporter-n9fwv\", job=\"admin-apps/prometheus-node-exporter\", jobLabel=\"node-exporter\", namespace=\"admin-apps\", pod_template_generation=\"1\", release=\"xxxx-prometheus\"}"
level=info ts=2019-02-20T08:43:50.203621876Z caller=filetargetmanager.go:170 msg="Adding target" key="{app=\"harbor\", component=\"core\", container_name=\"core\", instance=\"version-1-7-1-harbor-core-59c86b74db-l6q9w\", job=\"admin-apps/harbor\", namespace=\"admin-apps\", pod_template_hash=\"59c86b74db\", release=\"version-1-7-1\"}"
2019/02/20 08:43:50 Seeked /var/lib/docker/containers/1173c126076129cf3f6af52444571662ddb230784b6409492d7ad7d50e02b234/1173c126076129cf3f6af52444571662ddb230784b6409492d7ad7d50e02b234-json.log - &{Offset:0 Whence:0}
level=error ts=2019-02-20T08:43:50.203791176Z caller=filetarget.go:239 msg="failed to tail file, stat failed" error="stat /var/log/pods/811d0b71-2ae7-11e9-95a2-001dd8b71f61/core/6.log: no such file or directory" filename=/var/log/pods/811d0b71-2ae7-11e9-95a2-001dd8b71f61/core/6.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1746174]
 goroutine 63 [running]:
github.com/grafana/loki/pkg/promtail/targets.(*FileTarget).startTailing(0xc000366700, 0xc0009a0ce0, 0x2, 0x2)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetarget.go:241 +0x114
github.com/grafana/loki/pkg/promtail/targets.(*FileTarget).sync(0xc000366700, 0xc000366700, 0xc000ea61e0)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetarget.go:198 +0x1c1
github.com/grafana/loki/pkg/promtail/targets.NewFileTarget(0x1ec7800, 0xc000020510, 0x1ec9da0, 0xc000148f00, 0xc00021e870, 0xc000e2c5c0, 0x3d, 0xc000e14cf0, 0xc0004c7668, 0x18ad6c0, ...)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetarget.go:95 +0x1b2
github.com/grafana/loki/pkg/promtail/targets.(*syncer).newTarget(0xc0001d4ea0, 0xc000e2c5c0, 0x3d, 0xc000e14cf0, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetargetmanager.go:194 +0x83
github.com/grafana/loki/pkg/promtail/targets.(*syncer).sync(0xc0001d4ea0, 0xc0000e6c00, 0x61, 0x80)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetargetmanager.go:171 +0xae3
github.com/grafana/loki/pkg/promtail/targets.(*FileTargetManager).run(0xc0005685d0)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetargetmanager.go:98 +0xd5
created by github.com/grafana/loki/pkg/promtail/targets.NewFileTargetManager
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetargetmanager.go:89 +0x548
```
For your information, when I looked directly into the node that run promtail and lookup for the pod logs, I saw the that file is just a pointer to another file, but this file does not exist.
```
[sonhaiha@xxxxapp472 ~]$ sudo ls -lha /var/log/pods/811d0b71-2ae7-11e9-95a2-001dd8b71f61/core/6.log
lrwxrwxrwx. 1 root root 165 Feb  7 14:54 /var/log/pods/811d0b71-2ae7-11e9-95a2-001dd8b71f61/core/6.log -> /var/lib/docker/containers/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167-json.log
[sonhaiha@xxxxapp472 ~]$ sudo cat /var/lib/docker/containers/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167-json.log
cat: /var/lib/docker/containers/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167-json.log: No such file or directory
[sonhaiha@xxxxapp472 ~]$ sudo ls -lha /var/lib/docker/containers/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167-json.log
ls: cannot access /var/lib/docker/containers/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167-json.log: No such file or directory
[sonhaiha@xxxxapp472 ~]$ sudo ls -lha /var/lib/docker/containers/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167/
ls: cannot access /var/lib/docker/containers/a952b3c68f1ab610e481e548017ebb2a37b9a94ec691b56af35e4c0ba2b3d167/: No such file or directory
[sonhaiha@xxxxapp472 ~]$ sudo ls -lha /var/lib/docker/containers/
total 212K
drwx------. 44 root root  36K Feb 20 09:30 .
drwx--x--x. 15 root root 4.0K Feb  4 14:21 ..
drwx------.  4 root root 4.0K Feb  7 14:49 025feba8249903d12c439d728037539ec0d20dc57365773421559864c0df34b8
drwx------.  4 root root 4.0K Feb 12 16:21 039ddb3ed6f0d289bb5d848c558582dc61db8cda8c05b0b3b3ea49e77b9c63a6
drwx------.  4 root root 4.0K Feb  8 10:19 04d92205839e9b82020380d0140e4fc86dea37cdec3535811bcb012aa8fe037d
drwx------.  4 root root 4.0K Feb 17 00:01 0d889b49edb9b6e53403ca2b19c3a2c0a3eaec4c2c35f7d0762811da60ff898a
drwx------.  4 root root 4.0K Feb 12 10:47 0e72a0fe27aba22a324c24ae067a562671718438685721265c9a7fc7900878ba
drwx------.  4 root root 4.0K Feb 12 10:09 1173c126076129cf3f6af52444571662ddb230784b6409492d7ad7d50e02b234
drwx------.  4 root root 4.0K Feb 15 08:19 19ae2680747a42faacd5353b3a3e27474e606a01865dde17357193adc94e7ed1
drwx------.  4 root root 4.0K Feb  7 14:49 25f661e4d31ae9f0c3bb82282999ad7564c21132b3f59e60ab884da49921c1b7
drwx------.  4 root root 4.0K Feb  8 10:19 265967ae87de6b5e8908488fc36ca9d1fa849fbacee80dd32edaaaa0fb9a19c1
drwx------.  4 root root 4.0K Feb 12 17:04 2791bfe98a204f3711f7ba60a02581a09964f2b95361279f605d73e265a10c18
drwx------.  4 root root 4.0K Feb 15 08:19 30271c805f11fc0bf6c3c949bbed9d214c0ea1d9c29832d2155c914a83ce4c22
drwx------.  4 root root 4.0K Feb  7 14:55 377593a176bb20287d6b2614072422bd9d07a79329281c6691a7943287bb5e4a
drwx------.  4 root root 4.0K Feb  8 10:11 3884011c0ce1ff55d8d38a21b279d0fc585386b8fd2e2343becc6c7f629edc17
drwx------.  4 root root 4.0K Feb 12 10:47 3ba768f34c8906d0c28a76e9bad48ad9ecde8ff154b36dd633fef3ce3ac0c808
drwx------.  4 root root 4.0K Feb 17 00:01 4b112e773ce16aef88ad3d16f2e2f9d33136890839764e61f922553b4af8961e
drwx------.  4 root root 4.0K Feb  7 14:55 4de4fa0864e842ddd9ac4c1f39615e81bf9799c15e086d52c076d797c9beae41
drwx------.  4 root root 4.0K Feb  8 10:11 4f69053287a365ed60d7b1af4f5a228e8b8ba090843e39d2b8254581340ddbb3
drwx------.  4 root root 4.0K Feb 17 00:01 560c7b918a1fc09f9764bb56f487ed629860a19f0c9423dcad83c054f25b9819
drwx------.  4 root root 4.0K Feb 15 10:18 5ba6cdd62a7e09570ec84d0eaeefc8c289a3f3d8999c637c351b65d4fbf59549
drwx------.  4 root root 4.0K Feb 15 14:43 63bed8aad0d13be4e9dd718940745f5a0ec7e8ada7ab7529e0ac43c8320e7a41
drwx------.  4 root root 4.0K Feb  8 10:11 653dc68b75fe9b4a2905e874baed354e43c0e164304eea5217d9678654874d27
drwx------.  4 root root 4.0K Feb 15 10:15 67505b84bab0ea32ac1d4b5911a91a47298bb6c02845467fafae2129f4f7df5a
drwx------.  4 root root 4.0K Feb 15 10:17 71abc5f2c22375e48a11af012bee28d8a252c1fac4ff2f4c4e750520fddd45ef
drwx------.  4 root root 4.0K Feb  7 15:00 7749f5c1967578a93a67cd8a7741458351ffc195bef9c8dc9a8c34be1070fe23
drwx------.  4 root root 4.0K Feb 15 09:15 7b3d1e94bfa47448633ed50d4724422b5bb9f924488d7625fee0b3e6eaaa3869
drwx------.  4 root root 4.0K Feb  8 10:11 7d0a8365f02803a8864db97d0c98e3f197120b31a4c628b227ada60c72cd1b79
drwx------.  4 root root 4.0K Feb 15 08:19 7fa5c844e402bf7a2567eba7e00e1daeb022f0f9684b21b601aca0ce237048ab
drwx------.  4 root root 4.0K Feb  7 14:58 8f196da26c347b848025daf310e8c12c520d7888c365672e8a24d370beaae4e0
drwx------.  4 root root 4.0K Feb 15 10:15 973c6a2eb260baa1f0653699d62735a675d53babf89e3001add2a43df6ec895f
drwx------.  4 root root 4.0K Feb 17 00:00 9bcf6afb1b4cd8fc03cdffb4b4efb5669112d0502d8628742832cd4a417bbbb7
drwx------.  4 root root 4.0K Feb 12 17:04 9cb0663695a09ffd8cd97737568e5d744518d1b9acb5b6f6e3e0fc201c391224
drwx------.  4 root root 4.0K Feb  8 10:22 9fa035a43c8345cdc2397c91ae40fca5b2f215f3f74839cd3f885184c2659015
drwx------.  4 root root 4.0K Feb 20 09:30 a4d607303675b6c3377192ce73a349e86bebe9f66b47fe57ea0825bf23609455
drwx------.  4 root root 4.0K Feb  8 10:22 ae3d775271de8d718233205313313586bd3f33bd84bc4dce5d2ef383cc478e24
drwx------.  4 root root 4.0K Feb 15 08:19 b56519a525ff180590d7a17519b2d9b300dbbfb0de3fafacd7f6b77bc8558ab0
drwx------.  4 root root 4.0K Feb 17 00:00 b7bbb97a6f7a48511a4ca1de81f83875be7c80062a1b2e80a91888690db2c956
drwx------.  4 root root 4.0K Feb 12 10:47 c79dc55676d7c4d6229320cc09141c50d4da5543d73fbff0903e25108b94e66b
drwx------.  4 root root 4.0K Feb 12 10:09 cada8751ee5fd1f2fb75f402fc6b2c2b913d67121fafe465fabd14062c688f7f
drwx------.  4 root root 4.0K Feb 15 10:17 dac63da8f0c6af35f8492e9db61d9e0c5e937b098c034879eaa10a213928113a
drwx------.  4 root root 4.0K Feb  7 14:55 e2c3ffc387ee8b77afb16821b23921f43e8d663ef6bdacbe5ae4b5a815a86210
drwx------.  4 root root 4.0K Feb  8 10:19 e4f4ebe666c595edf5adba95a5ed9ddbe2d15abce4914229a2d218275d46a27a
drwx------.  4 root root 4.0K Feb 12 16:21 e8d6d0b25ebeda2690fe8a07f6e04c1b86872b7542c356c8987677f5972eda3e
```
However, I can access the log of pod through kubectl. This make me fell quite confused. If the log file point to non-existed file, kubectl should also be not possible to display the logs.

**Comment by slim-bean** [comment]
Should be fixed by #352, need to improve test coverage, see #354
