### ISSUE TITLE
ingester panic: error parsing regexp: missing argument to repetition operator: `*`

### ISSUE THREAD

**Issue by woodsaj** [grafana/loki#346]
ingester panic due bad to query..
```
panic: error parsing regexp: missing argument to repetition operator: `*`

goroutine 1737352 [running]:
github.com/grafana/loki/pkg/parser.mustNewMatcher(0x2, 0xc04313f850, 0xc, 0xc04313f82d, 0x1, 0xc03b2bb560)
	/go/src/github.com/grafana/loki/pkg/parser/parser.go:48 +0x8a
github.com/grafana/loki/pkg/parser.(*labelsParserImpl).Parse(0xc0752a5900, 0x13f4ce0, 0xc024843600, 0x0)
	pkg/parser/labels.y:47 +0x1038
github.com/grafana/loki/pkg/parser.labelsParse(0x13f4ce0, 0xc024843600, 0x42b881)
	yaccpar:153 +0x58
github.com/grafana/loki/pkg/parser.parse(0xe004, 0xc012b203c0, 0x21, 0xc007b95608, 0xc007b95640, 0xf53ec2)
	/go/src/github.com/grafana/loki/pkg/parser/parser.go:38 +0x178
github.com/grafana/loki/pkg/parser.Matchers(0xc012b203c0, 0x21, 0xc000430a48, 0x102ab01, 0xc0001a02b0, 0xc007b95690, 0xf53abf)
	/go/src/github.com/grafana/loki/pkg/parser/parser.go:14 +0x42
github.com/grafana/loki/pkg/ingester.(*instance).Query(0xc000b8c060, 0xc00c3a1da0, 0x14086a0, 0xc00d8b1450, 0x0, 0x0)
	/go/src/github.com/grafana/loki/pkg/ingester/instance.go:97 +0x4c
github.com/grafana/loki/pkg/ingester.(*Ingester).Query(0xc0001a01a0, 0xc00c3a1da0, 0x14086a0, 0xc00d8b1450, 0xc0001a01a0, 0xc000a6d740)
	/go/src/github.com/grafana/loki/pkg/ingester/ingester.go:171 +0xbe
github.com/grafana/loki/pkg/logproto._Querier_Query_Handler(0x123b2e0, 0xc0001a01a0, 0x14079e0, 0xc04ca0b800, 0xc04ca0b800, 0xc000a6d7d0)
	/go/src/github.com/grafana/loki/pkg/logproto/logproto.pb.go:961 +0x109
github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1(0x123b2e0, 0xc0001a01a0, 0x14079e0, 0xc04ca0b800, 0x1401ee0, 0xc03b2bb4a0)
	/go/src/github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:71 +0xf5
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.StreamServerUserHeaderInterceptor(0x123b2e0, 0xc0001a01a0, 0x1407200, 0xc04ca0b7e0, 0xc04ca0b780, 0xc00147c960, 0x11ba620, 0x1401e01)
	/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/grpc_auth.go:48 +0xfe
github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1(0x123b2e0, 0xc0001a01a0, 0x1407200, 0xc04ca0b7e0, 0x1401ee0, 0xc03b2bb470)
	/go/src/github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:74 +0x9c
github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-grpc.OpenTracingStreamServerInterceptor.func1(0x123b2e0, 0xc0001a01a0, 0x14073e0, 0xc01a2ad140, 0xc04ca0b780, 0xc00147c960, 0x0, 0x0)
	/go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-grpc/server.go:114 +0x336
github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1(0x123b2e0, 0xc0001a01a0, 0x14073e0, 0xc01a2ad140, 0x0, 0x0)
	/go/src/github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:74 +0x9c
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.StreamServerInstrumentInterceptor.func1(0x123b2e0, 0xc0001a01a0, 0x14073e0, 0xc01a2ad140, 0xc04ca0b780, 0xc00147c960, 0x5c6d3859, 0xc026fad647)
	/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/grpc_instrumentation.go:36 +0x9d
github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1(0x123b2e0, 0xc0001a01a0, 0x14073e0, 0xc01a2ad140, 0xc000e74000, 0xc000a6dbc8)
	/go/src/github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:74 +0x9c
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.GRPCServerLog.StreamServerInterceptor(0x140b340, 0xc0003c4580, 0x0, 0x123b2e0, 0xc0001a01a0, 0x14073e0, 0xc01a2ad140, 0xc04ca0b780, 0xc00147c960, 0xc04ca0b701, ...)
	/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/grpc_logging.go:44 +0x98
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.GRPCServerLog.StreamServerInterceptor-fm(0x123b2e0, 0xc0001a01a0, 0x14073e0, 0xc01a2ad140, 0xc04ca0b780, 0xc00147c960, 0xc000a6dc78, 0x40c4a8)
	/go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/server/server.go:131 +0x8a
github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0x123b2e0, 0xc0001a01a0, 0x14073e0, 0xc01a2ad140, 0xc04ca0b780, 0x12bb008, 0xc019540460, 0x1016260)
	/go/src/github.com/grafana/loki/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:79 +0x14d
github.com/grafana/loki/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc0000a2d80, 0x140ab60, 0xc00f2dcc00, 0xc05653f800, 0xc000b628a0, 0x1e4d200, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/loki/vendor/google.golang.org/grpc/server.go:1177 +0x488
github.com/grafana/loki/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000a2d80, 0x140ab60, 0xc00f2dcc00, 0xc05653f800, 0x0)
	/go/src/github.com/grafana/loki/vendor/google.golang.org/grpc/server.go:1249 +0xcf1
github.com/grafana/loki/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc002798340, 0xc0000a2d80, 0x140ab60, 0xc00f2dcc00, 0xc05653f800)
	/go/src/github.com/grafana/loki/vendor/google.golang.org/grpc/server.go:685 +0x9f
created by github.com/grafana/loki/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/grafana/loki/vendor/google.golang.org/grpc/server.go:683 +0xa1

```

version="(version=master-b115835, branch=master, revision=b115835)"

**Comment by daixiang0** [comment]
@woodsaj could share a query example for this?

**Comment by Kuqd** [comment]
@woodsaj this code has changed a lot since then, I can verify if this is fixed, do you recall the query you used ?

**Comment by woodsaj** [comment]
I think it was as simple as `{cluster="foo"} *`   
However, the bigger concern was that failures in the query path could lead to panics in the ingesters.  We should make sure that doesn't ever happen, eg by recovering panics on the query path.

**Comment by zyclonite** [comment]
still happens with the current builds (2 days old)

the above query from @woodsaj results only in
```
level=warn ts=2019-07-25T16:31:00.847535725Z caller=grpc_logging.go:54 method=/logproto.Querier/Query duration=72.971µs err="error parsing regexp: missing argument to repetition operator: `*`" msg="gRPC\n"
level=warn ts=2019-07-25T16:31:00.900506823Z caller=grpc_logging.go:54 method=/logproto.Querier/Query duration=284.016µs err="rpc error: code = Canceled desc = context canceled" msg="gRPC\n"
```
but the following query `{cluster=~"*"}` will end up in a panic
```
panic: error parsing regexp: missing argument to repetition operator: `*`
        /usr/local/go/src/net/http/server.go:2851 +0x2f5
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1847 +0x646
net/http.(*conn).serve(0xc003b13cc0, 0x1548d20, 0xc003e4a300)
        /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.serverHandler.ServeHTTP(0xc0004855f0, 0x1547120, 0xc00016ec40, 0xc0061ef500)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.HandlerFunc.ServeHTTP(0xc000507f20, 0x1547120, 0xc00016ec40, 0xc0061ef500)
        /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/http_tracing.go:39 +0x8f
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Tracer.Wrap.func2(0x1547120, 0xc00016ec40, 0xc0061ef500)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.HandlerFunc.ServeHTTP(0xc000507ef0, 0x1547120, 0xc00016ec40, 0xc0061ef500)
        /go/src/github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:118 +0x4af
github.com/grafana/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func4(0x1547120, 0xc00016ec40, 0xc0061ef500)
        /go/src/github.com/grafana/loki/vendor/github.com/prometheus/client_golang/prometheus/http.go:132 +0x4d
net/http.Handler.ServeHTTP-fm(0x1548560, 0xc003ea25f0, 0xc0061ef600)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.HandlerFunc.ServeHTTP(0xc000507e90, 0x1548560, 0xc003ea25f0, 0xc0061ef600)
        /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/logging.go:41 +0x1a2
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Log.Wrap.func1(0x1548560, 0xc003ea25f0, 0xc0061ef600)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.HandlerFunc.ServeHTTP(0xc000507e60, 0x1544760, 0xc003e4a4c0, 0xc0061ef600)
        /go/src/github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:49 +0x177
github.com/grafana/loki/vendor/github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x1544760, 0xc003e4a4c0, 0xc0061ef600)
        /go/src/github.com/grafana/loki/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
github.com/grafana/loki/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004f3960, 0x15447a0, 0xc0004be3e0, 0xc0061ef800)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.HandlerFunc.ServeHTTP(0xc0004bff40, 0x15447a0, 0xc0004be3e0, 0xc0061ef800)
        /go/src/github.com/grafana/loki/pkg/loki/fake_auth.go:18 +0x13b
github.com/grafana/loki/pkg/loki.glob..func1.1(0x15447a0, 0xc0004be3e0, 0xc0061ef800)
        /usr/local/go/src/net/http/server.go:1964 +0x44
net/http.HandlerFunc.ServeHTTP(0xc0004b9980, 0x15447a0, 0xc0004be3e0, 0xc0061ef900)
        /go/src/github.com/grafana/loki/pkg/loki/modules.go:145 +0x48
github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler-fm(0x15447a0, 0xc0004be3e0, 0xc0061ef900)
        /go/src/github.com/grafana/loki/pkg/querier/http.go:131 +0x1cf
github.com/grafana/loki/pkg/querier.(*Querier).QueryHandler(0xc000084de0, 0x15447a0, 0xc0004be3e0, 0xc0061ef900)
        /go/src/github.com/grafana/loki/pkg/querier/querier.go:118 +0xf3
github.com/grafana/loki/pkg/querier.(*Querier).Query(0xc000084de0, 0x1548de0, 0xc000aa1170, 0xc003f014a0, 0x0, 0x0, 0x0)
        /go/src/github.com/grafana/loki/pkg/storage/store.go:43 +0x3e
github.com/grafana/loki/pkg/storage.(*store).LazyQuery(0xc0004b9870, 0x1548de0, 0xc000aa1170, 0xc003f014a0, 0xc0011b61f0, 0x1, 0x1, 0x0)
        /go/src/github.com/grafana/loki/pkg/logql/parser.go:31 +0x1dc
github.com/grafana/loki/pkg/logql.ParseExpr(0xc003665da0, 0x2c, 0x1, 0x0, 0x100000001, 0x1)
        pkg/logql/expr.y:63 +0x10d6
github.com/grafana/loki/pkg/logql.(*exprParserImpl).Parse(0xc0008ec800, 0x153a760, 0xc000975b80, 0x0)
        /go/src/github.com/grafana/loki/pkg/logql/ast.go:126 +0x8a
github.com/grafana/loki/pkg/logql.mustNewMatcher(0x2, 0xc000b54180, 0xc, 0xc000b54156, 0x1, 0xc000aa1650)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
panic(0x11aee20, 0xc0004bea00)
        /usr/local/go/src/net/http/server.go:1746 +0xd0
net/http.(*conn).serve.func1(0xc003b13cc0)
```

**Comment by Kuqd** [comment]
I'll take a look at this.

**Comment by Kuqd** [comment]
So this will be fixed by https://github.com/grafana/loki/pull/654/files#diff-0fa3ae390d51a1a0294b3a2ba2041a9cR24 #654 I already spotted it there.

We just need to wait for it to be merged and this won't happen again.
