### ISSUE TITLE
Newlines are escaped improperly in fluentd plugin

### ISSUE THREAD

**Issue by addisonElliott** [grafana/loki#3656]
**Describe the bug**

I am using the fluentd plugin to import logs to Loki. I am having the issue where newlines are not being displayed properly. See the screenshot below.

![image](https://user-images.githubusercontent.com/1342819/116164553-8aa58600-a6bf-11eb-918d-ffaaab86a699.png)

I thought this issue was going to be fixed by this: https://github.com/grafana/grafana/pull/29541
But it wasn't.

Rather, I eventually stumbled across this new PR (https://github.com/grafana/grafana/pull/31352) describing how newlines are **incorrectly** escaped. I checked the raw data and it was incorrectly escaped. Here's the data that's being sent to Loki from Fluentd.

If I'm understanding this correctly, it should be "\n" not "\\n".

```
{
   "streams":[
      {
         "stream":{
            "host":"api.srv2.becsys.com"
         },
         "values":[
            [
               "1619477311000000000",
               "{\"level\":\"info\",\"message\":\"Watching for new controllers\"}"
            ],
            [
               "1619477312000000000",
               "{\"level\":\"warn\",\"message\":\"Failed to register webhooks for 1100177001586 Request failed with status code 404\\nError: Request failed with status code 404\\n    at createError (/home/becs/dev-becsys-live-backend/node_modules/axios/lib/core/createError.js:16:15)\\n    at settle (/home/becs/dev-becsys-live-backend/node_modules/axios/lib/core/settle.js:17:12)\\n    at IncomingMessage.handleStreamEnd (/home/becs/dev-becsys-live-backend/node_modules/axios/lib/adapters/http.js:244:11)\\n    at IncomingMessage.emit (events.js:323:22)\\n    at endReadableNT (_stream_readable.js:1204:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\\n{\\n  config: {\\n    url: '',\\n    method: 'put',\\n    data: '{\\\"event\\\":\\\"value.changed.387\\\",\\\"url\\\":\\\"",
               "\\\\""data\\\":{}}',\\n    headers: {\\n      Accept: 'application/json, text/plain, */*',\\n      'Content-Type': 'application/json;charset=utf-8',\\n      'User-Agent': 'axios/0.21.0',\\n      'Content-Length': 114\\n    },\\n    auth: {\\n      username: '',\\n      password: ''\\n    },\\n    baseURL: '',\\n    transformRequest: [ [Function: transformRequest] ],\\n    transformResponse: [ [Function: transformResponse] ],\\n    timeout: 0,\\n    adapter: [Function: httpAdapter],\\n    xsrfCookieName: 'XSRF-TOKEN',\\n    xsrfHeaderName: 'X-XSRF-TOKEN',\\n    maxContentLength: -1,\\n    maxBodyLength: -1,\\n    httpsAgent: [HttpsAgent],\\n    validateStatus: [Function: validateStatus]\\n  },\\n  isAxiosError: true,\\n  toJSON: [Function: toJSON],\\n  data: { message: 'Controller is offline' },\\n  status: 404,\\n  headers: {\\n    server: 'nginx/1.14.2',\\n    date: 'Mon, 26 Apr 2021 22:48:32 GMT',\\n    'content-type': 'application/json',\\n    'content-length': '35',\\n    connection: 'keep-alive',\\n    'access-control-allow-origin': 'null',\\n    'access-control-allow-credentials': 'true',\\n    vary: 'Origin'\\n  }\\n}\"}"
            ]
         ]
      }
   ]
}
```

**To Reproduce**

Setup a multiline source and send it to Loki via the fluentd plugin.

**Expected behavior**

The expected behavior is that newline should be sent as "\n" with a backslash and the ASCII n.

**Whats's the problem**

I traced this through and discovered that it's due to this loki-fluentd plugin.

I believe the problem is that `Yajl.dump` (i.e. the JSON stringifyer) is called twice. The two spots in the source code are linked below. The first time changes the newline to "\n" and the second time then escapes the "\" resulting in "\\n".

1. https://github.com/grafana/loki/blob/main/clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb#L277
2. https://github.com/grafana/loki/blob/main/clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb#L217

**What's the fix**

I have come up with a solution, but it's not pretty. Open to suggestions here.

After doing the double-escape, we can replace any double-slashes with a single slash.

See here: https://github.com/grafana/loki/blob/main/clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb#L217

Replace that line with:

```
        req.body = Yajl.dump(body).gsub('\\\\', '\\')
```

**Comment by addisonElliott** [comment]
My proposed fix doesn't work.

I have no idea what's going on. Maybe I'm totally misdiagnosing the issue...

**Comment by addisonElliott** [comment]
bump
