### ISSUE TITLE
Docker login plugin crashes

### ISSUE THREAD

**Issue by dan74-es** [grafana/loki#3705]
In the last couple of weeks we have experienced several crashes of the docker login plugin. Unfortunately we have not been able to find any pattern.
As an example, I attach the logs where the loki driver was started for a container but 8 minutes later, the driver panics and it is not possible to contact the plugin again. I attach also the plugin details as provided by docker.
Any help is appreciated.

**Journalctl docker service logs** 
 2021-05-05 18:00:43 | time="2021-05-05T16:00:43Z" level=info msg="level=info ts=2021-05-05T16:00:43.27073677Z caller=driver.go:77 msg=\"starting logging driver for container\" id=57515bd5afccd1164028623b7ebda88488289941c7860e587a0b583e09767456 config=\"map[loki-external-labels:container_name={{.Name}} loki-retries:5 loki-url:http://localhost:3500/loki/api/v1/push max-file:5 max-size:10m]\" file=/run/docker/logging/2a316d0affd21d87946b5084ad615829d144511527db4cb791fac3fd0bbe485d logpath=/var/log/docker/57515bd5afccd1164028623b7ebda88488289941c7860e587a0b583e09767456/json.log" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
2021-05-05 18:00:43 | time="2021-05-05T16:00:43Z" level=warning msg="file does not exist: /proc/sys/net/ipv6/conf/all/disable_ipv6 : stat /proc/sys/net/ipv6/conf/all/disable_ipv6: no such file or directory Has IPv6 been disabled in this node's kernel?"
2021-05-05 18:08:32 | time="2021-05-05T16:08:32.792904381Z" level=info msg="Container a9d61bc0e5d6494694a7162b79ef84fd8f8a849c06b6fca9f97b0f8c1564be5b failed to exit within 10 seconds of signal 15 - using the force"
2021-05-05 18:08:32 | time="2021-05-05T16:08:32.905023320Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error msg="goroutine 143581 [running]:" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error msg="panic: send on closed channel" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error msg="main.(*loki).Log(0xc000968e80, 0xc0001d4a10, 0xc000968f00, 0x0)" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error msg="\t/src/loki/cmd/docker-driver/driver.go:116 +0xa75" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error msg="created by main.(*driver).StartLogging" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error msg="\t/src/loki/cmd/docker-driver/driver.go:165 +0x4c2" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error msg="main.consumeLog(0xc0002f26c0)" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
 2021-05-05 18:08:32 | time="2021-05-05T16:08:32Z" level=error msg="\t/src/loki/cmd/docker-driver/loki.go:69 +0x2fb" plugin=cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35
 2021-05-05 18:08:33 | time="2021-05-05T16:08:33.018577114Z" level=info msg="ignoring event" module=libcontainerd namespace=plugins.moby topic=/tasks/delete type="*events.TaskDelete"
 2021-05-05 18:08:35 | time="2021-05-05T16:08:35.211077082Z" level=warning msg="Unable to connect to plugin: /run/docker/plugins/cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35/loki.sock/LogDriver.Capabilities: Post http://%2Frun%2Fdocker%2Fplugins%2Fcd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35%2Floki.sock/LogDriver.Capabilities: dial unix /run/docker/plugins/cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35/loki.sock: connect: no such file or directory, retrying in 1s"_
 

**Docker plugin details**
docker plugin ls 
ID                  NAME                DESCRIPTION           ENABLED
cd90d2781824        loki:latest         Loki Logging Driver   true

docker inspect cd90d2781824
[
    {
        "Config": {
            "Args": {
                "Description": "",
                "Name": "",
                "Settable": null,
                "Value": null
            },
            "Description": "Loki Logging Driver",
            "DockerVersion": "17.09.0-ce",
            "Documentation": "https://github.com/grafana/loki",
            "Entrypoint": [
                "/bin/docker-driver"
            ],
            "Env": [
                {
                    "Description": "Set log level to output for plugin logs",
                    "Name": "LOG_LEVEL",
                    "Settable": [
                        "value"
                    ],
                    "Value": "info"
                },
                {
                    "Description": "Activate pprof debugging endpoint for the given port.",
                    "Name": "PPROF_PORT",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                }
            ],
            "Interface": {
                "Socket": "loki.sock",
                "Types": [
                    "docker.logdriver/1.0"
                ]
            },
            "IpcHost": false,
            "Linux": {
                "AllowAllDevices": false,
                "Capabilities": null,
                "Devices": null
            },
            "Mounts": null,
            "Network": {
                "Type": "host"
            },
            "PidHost": false,
            "PropagatedMount": "",
            "User": {},
            "WorkDir": "",
            "rootfs": {
                "diff_ids": [
                    "sha256:2f45f3ef2bd7765d68f4c86b8c066113e0172275698c91b365fa1fea692cedb3"
                ],
                "type": "layers"
            }
        },
        "Enabled": true,
        "Id": "cd90d2781824ee5cc3490857b38f07c58fa8478c58c35494b396027c46b6df35",
        "Name": "loki:latest",
        "PluginReference": "docker.io/grafana/loki-docker-driver:latest",
        "Settings": {
            "Args": [],
            "Devices": [],
            "Env": [
                "LOG_LEVEL=info",
                "PPROF_PORT="
            ],
            "Mounts": []
        }
    }
]

**Comment by timdonovanuk** [comment]
Just to check, I noticed that if the host loki sits on isn't reachable, it's actually impossible to stop a container (and it gets stuck unresponsive - no workloads run in it). For example, with this defined in compose for a service:

```
      logging:
        driver: loki
        options:
          loki-url: "http://192.168.1.41:3100/loki/api/v1/push" 
```

If `192.168.1.41` for whatever reason is down, the container goes unkillable - I tried chucking everything at it, but nothing less than killing the entire docker service would stop it!

Is this the same bug or should I report this?
