### ISSUE TITLE
Image 2.2.1 fails to start

### ISSUE THREAD

**Issue by budarin** [grafana/loki#3942]
**Describe the bug**
Try to run docker container v2.2.1

**To Reproduce**
1. download config
`wget https://raw.githubusercontent.com/grafana/loki/v2.2.1/cmd/loki/loki-local-config.yaml`
2. configure docker-compose service as
```yaml
services:
    loki:
        image: grafana/loki:latest
        volumes:
            - loki_vol:/loki
            - ./docker/config/loki/loki-local-config.yaml:/etc/loki/config.yaml:ro
        command: -config.file=/etc/loki/config.yaml
```
3. try to run
4. loki service fails
5. looking at the logs
```
level=info ts=2021-07-05T10:53:02.9859515Z caller=main.go:129 msg="Starting Loki" version="(version=, branch=, revision=)"
level=info ts=2021-07-05T10:53:02.987335Z caller=server.go:239 http=[::]:3100 grpc=[::]:9096 msg="server listening on addresses"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1d6af20]

goroutine 1 [running]:
github.com/cortexproject/cortex/pkg/util/runtimeconfig.(*Manager).GetConfig(0x0, 0x0, 0x0)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/runtimeconfig/manager.go:204 +0x40
github.com/grafana/loki/pkg/loki.(*tenantLimitsFromRuntimeConfig).TenantLimits(0xc000138670, 0x0, 0x0, 0xc000267610)
        /src/loki/pkg/loki/runtime_config.go:53 +0x32
github.com/grafana/loki/pkg/validation.(*Overrides).getOverridesForUser(...)
        /src/loki/pkg/validation/limits.go:389
github.com/grafana/loki/pkg/validation.(*Overrides).IngestionRateStrategy(0xc00000c768, 0xc000267610, 0xa)
        /src/loki/pkg/validation/limits.go:216 +0x5f
github.com/grafana/loki/pkg/distributor.New(0x24a0d27, 0x6, 0x24aa70a, 0xb, 0x24b0b19, 0xe, 0x0, 0x0, 0x4a817c800, 0x0, ...)
        /src/loki/pkg/distributor/distributor.go:100 +0xe5
github.com/grafana/loki/pkg/loki.(*Loki).initDistributor(0xc000209400, 0xc0004994c0, 0xc0006188a0, 0xc000618870, 0xc000717a20)
        /src/loki/pkg/loki/modules.go:158 +0x1d2
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule(0xc000138550, 0x249d1eb, 0x3, 0xc00078b3e8, 0xc00056f2c0, 0x0, 0x28fa6a8)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103 +0x2ba
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices(0xc000138550, 0xc000018420, 0x1, 0x1, 0xc000818420, 0x292c858, 0xc000818420)
        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75 +0x105
github.com/grafana/loki/pkg/loki.(*Loki).Run(0xc000209400, 0xc000498a80, 0x4)
        /src/loki/pkg/loki/loki.go:241 +0x65
main.main()
        /src/loki/cmd/loki/main.go:131 +0x590
```

**Expected behavior**
run loki service

**Environment:**
 - docker swarm on Mac & Windows
 - docker-compose

**Comment by heikkilamarko** [comment]
Same problem here.

**Comment by abmurksi** [comment]
Same here, previous build grafana/loki:main-71889dc is running fine

**Comment by dannykopping** [comment]
Thanks for reporting this @budarin.
 `grafana/loki:latest` points to the tip of `main`, not to the latest release - apologies for the confusion.

```
~ $ docker run --rm grafana/loki:latest -version
loki, version master-46eff3c (branch: master, revision: 46eff3c1)
  build user:       root@a37bd0eed002
  build date:       2021-04-08T17:39:34Z
  go version:       go1.16.2
  platform:         linux/amd64
```

To run v2.2.1, please reference it explicitly:

```
~ $ docker run --rm grafana/loki:2.2.1 -version
loki, version 2.2.1 (branch: HEAD, revision: babea82ef)
  build user:       root@08f25141d639
  build date:       2021-04-06T00:51:57Z
  go version:       go1.15.3
  platform:         linux/amd64
```

**Comment by budarin** [comment]
only 5 times have tried to to pull image from dockerhub but got the error

```
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```

:(

**Comment by dannykopping** [comment]
I'm closing this issue in favour of #3943, which should hopefully prevent this sort of problem in the future.
If you disagree, please reopen and let's discuss.

Thanks for getting the conversation started!
