### ISSUE TITLE
Segmentation fault on Compactor (Loki docker container)

### ISSUE THREAD

**Issue by jskim20210115** [grafana/loki#3964]
**Describe the bug**
Segmentation fault on Compactor.
(Cannot launch loki docker container)

**To Reproduce**
1. docker run -p 3100:3100 grafana/loki:latest
2. Crash happens

**Expected behavior**
Should run smoothly

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: docker

**Screenshots, Promtail config, or terminal output**
```bash
$ docker run -p 3100:3100 gafana/loki:latest                                                                                 
level=info ts=2021-07-08T02:35:54.997694092Z caller=main.go:129 msg="Starting Loki" version="(version=, branch=, revision=)"                                                                        
level=info ts=2021-07-08T02:35:54.998077099Z caller=server.go:239 http=[::]:3100 grpc=[::]:9095 ms
g="server listening on addresses"                                                                 
level=info ts=2021-07-08T02:35:54.999250332Z caller=shipper_index_client.go:108 msg="starting bolt db shipper in 0 mode"                                                                             
level=info ts=2021-07-08T02:35:54.999220956Z caller=table_manager.go:171 msg="uploading tables"   
level=info ts=2021-07-08T02:35:55.00137075Z caller=mapper.go:46 msg="cleaning up mapped rules dire
ctory" path=/loki/rules-temp                                                                      
level=error ts=2021-07-08T02:35:55.001497794Z caller=mapper.go:50 msg="unable to read rules direct
ory" path=/loki/rules-temp err="open /loki/rules-temp: no such file or directory"                 
level=info ts=2021-07-08T02:35:55.004139473Z caller=module_service.go:59 msg=initialising module=m
emberlist-kv                                                                                      
level=info ts=2021-07-08T02:35:55.004125472Z caller=module_service.go:59 msg=initialising module=s
erver                                                                                             
level=info ts=2021-07-08T02:35:55.004185349Z caller=module_service.go:59 msg=initialising module=s
tore                                                                                              
level=info ts=2021-07-08T02:35:55.004255017Z caller=module_service.go:59 msg=initialising module=r
ing                                                                                               
level=info ts=2021-07-08T02:35:55.004240016Z caller=module_service.go:59 msg=initialising module=t
able-manager                                                                                      
level=info ts=2021-07-08T02:35:55.004291101Z caller=module_service.go:59 msg=initialising module=i
ngester                                                                                           
level=info ts=2021-07-08T02:35:55.004300101Z caller=module_service.go:59 msg=initialising module=c
ompactor                                                                                          
level=info ts=2021-07-08T02:35:55.004405853Z caller=lifecycler.go:529 msg="not loading tokens from
 file, tokens file path is empty"                                                                 
level=info ts=2021-07-08T02:35:55.004476646Z caller=ring.go:271 msg="ring doesn't exist in KV stor
e yet"                                                                                            
panic: runtime error: invalid memory address or nil pointer dereference                           
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c34125]                           
                                                                                                  
goroutine 72 [running]:                                                                           
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).RunCompaction.func1(0xc0
00d9a5b0, 0xc000f26e30, 0xc031b702c043e2d3, 0x3e9a68a, 0x3909f20)                                 
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:219 +0xa5                     
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).RunCompaction(0xc000d9a5
b0, 0x291d860, 0xc000538080, 0x0, 0x0)                                                            
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:258 +0x2b1                    
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop.func1()
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:153 +0x45                     
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop.func2(0xc000c04100,
 0xc000798020, 0xc000d9a5b0, 0x291d860, 0xc000538080)                                             
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:162 +0x78            
created by github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop         
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:160 +0x17b                    
```

**Comment by cyriltovena** [comment]
Fixed on main.
