### ISSUE TITLE
Promtail crashes with signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by ST-DDT** [grafana/loki#506]
**Describe the bug**

Promtail stopped working on some (4/6) of my kubernetes hosts. Crash-Loop. Restarting promtail/kubernetes/the VM does not fix the error.

**To Reproduce**

Unknown. AFAICT it expects files to be at a certain place but they aren't, but I don't have a clue, what the underlying error is.

**Expected behavior**

Promtail logs the logs into loki

**Environment:**

 - Kubernetes 1.13.1 in-house-VMs
 - Deployment tool: kubespray

**Screenshots, promtail config, or terminal output**

````txt

level=info ts=2019-04-23T13:07:28.321485308Z caller=kubernetes.go:201 component=discovery discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-04-23T13:07:28.323367856Z caller=gokit.go:36 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-04-23T13:07:28.323514025Z caller=main.go:46 msg="Starting Promtail" version="(version=master-e2d7a4f, branch=master, revision=e2d7a4f)"
level=info ts=2019-04-23T13:07:33.321489818Z caller=filetargetmanager.go:170 msg="Adding target" key="{app=\"promtail\", container_name=\"loki\", controller_revision_hash=\"588dfbbf54\", instance=\"loki-promtail-hnstt\", job=\"logging/promtail\", namespace=\"logging\", pod_template_generation=\"1\", release=\"loki\"}"
level=info ts=2019-04-23T13:07:33.323114303Z caller=tailer.go:78 msg="start tailing file" path=/var/log/pods/9d3afb8d-65c8-11e9-8837-000c29a0d751/loki/2.log
2019/04/23 13:07:33 Seeked /var/lib/docker/containers/2595b09b3a5324e6f21873a78eeaa2152795b4bf8df5e001bef5bb90bd82e641/2595b09b3a5324e6f21873a78eeaa2152795b4bf8df5e001bef5bb90bd82e641-json.log - &{Offset:0 Whence:0}
level=info ts=2019-04-23T13:07:33.323412144Z caller=tailer.go:78 msg="start tailing file" path=/var/log/pods/9d3afb8d-65c8-11e9-8837-000c29a0d751/loki/3.log
2019/04/23 13:07:33 Seeked /var/lib/docker/containers/c5f14e483a9aac3d308172a8d8a2940cfc4be4b4f67433284b2cd1c87db16985/c5f14e483a9aac3d308172a8d8a2940cfc4be4b4f67433284b2cd1c87db16985-json.log - &{Offset:0 Whence:0}
level=info ts=2019-04-23T13:07:33.324180159Z caller=filetargetmanager.go:170 msg="Adding target" key="{app=\"fluent-bit\", container_name=\"fluent-bit\", controller_revision_hash=\"78c4fc6cb4\", instance=\"efk-fluent-bit-6dxjk\", job=\"logging/fluent-bit\", namespace=\"logging\", pod_template_generation=\"1\", release=\"efk\"}"
level=error ts=2019-04-23T13:07:33.324340693Z caller=filetarget.go:239 msg="failed to tail file, stat failed" error="stat /var/log/pods/237ec500-2fa3-11e9-ae17-000c298e907e/fluent-bit/5.log: no such file or directory" filename=/var/log/pods/237ec500-2fa3-11e9-ae17-000c298e907e/fluent-bit/5.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1746174]
goroutine 106 [running]:
github.com/grafana/loki/pkg/promtail/targets.(*FileTarget).startTailing(0xc000215110, 0xc0009da880, 0x3, 0x4)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetarget.go:241 +0x114
github.com/grafana/loki/pkg/promtail/targets.(*FileTarget).sync(0xc000215110, 0xc000215110, 0xc0000a8c00)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetarget.go:198 +0x1c1
github.com/grafana/loki/pkg/promtail/targets.NewFileTarget(0x1ec7800, 0xc00038f4d0, 0x1ec9da0, 0xc00000bfa0, 0xc000180b40, 0xc000adc550, 0x43, 0xc0008aae10, 0xc0000b51e8, 0x18ad6c0, ...)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetarget.go:95 +0x1b2
github.com/grafana/loki/pkg/promtail/targets.(*syncer).newTarget(0xc000164ae0, 0xc000adc550, 0x43, 0xc0008aae10, 0x0, 0x0, 0x0)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetargetmanager.go:194 +0x83
github.com/grafana/loki/pkg/promtail/targets.(*syncer).sync(0xc000164ae0, 0xc000a18800, 0x64, 0x80)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetargetmanager.go:171 +0xae3
github.com/grafana/loki/pkg/promtail/targets.(*FileTargetManager).run(0xc0002954d0)
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetargetmanager.go:98 +0xd5
created by github.com/grafana/loki/pkg/promtail/targets.NewFileTargetManager
	/go/src/github.com/grafana/loki/pkg/promtail/targets/filetargetmanager.go:89 +0x548
````

**Comment by woodsaj** [comment]
@ST-DDT you are using a very old version of promtail.  Many bugs have been fixed since this commit (which is from mid February).    Please upgrade to a recent version.  If you are using the "grafana/promtail" image with "latest" or "master" tag, you need to make sure that you have "imagePullPolicy" set to "Always".  If you already have this set, then just delete all the promtail pods so they restart and pull the latest image.

**Comment by ST-DDT** [comment]
After updating the image, it works as expected.
Thanks.
