### ISSUE TITLE
Loki is unable to start in GKE

### ISSUE THREAD

**Issue by dakshrajopenx** [grafana/loki#5225]
We are using image version of Loki-2.0.0 in GKE. It is restarting again and again.

Chart version: loki-2.1.1

Image version: grafana/loki:2.0.0

```
level=info ts=2022-01-24T16:14:07.373580592Z caller=main.go:128 msg="Starting Loki" version="(version=2.0.0, branch=HEAD, revision=6978ee5d7)"
level=info ts=2022-01-24T16:14:07.373698104Z caller=modules.go:420 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2022-01-24T16:14:07.373932824Z caller=server.go:225 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2022-01-24T16:14:07.374624858Z caller=table_manager.go:241 msg="loading table index_19016"
unexpected fault address 0x7ffa8cf26008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7ffa8cf26008 pc=0x146df37]

goroutine 1 [running]:
runtime.throw(0x219cafe, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000e61cd0 sp=0xc000e61ca0 pc=0x434ae2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:692 +0x443 fp=0xc000e61d00 sp=0xc000e61cd0 pc=0x44b783
go.etcd.io/bbolt.(*freelist).read(0xc00050e600, 0x7ffa8cf26000)
	/src/loki/vendor/go.etcd.io/bbolt/freelist.go:265 +0x37 fp=0xc000e61db0 sp=0xc000e61d00 pc=0x146df37
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	/src/loki/vendor/go.etcd.io/bbolt/db.go:316 +0xcf fp=0xc000e61de8 sp=0xc000e61db0 pc=0x147839f
sync.(*Once).doSlow(0xc00057d368, 0xc000e61e48)
	/usr/local/go/src/sync/once.go:66 +0xec fp=0xc000e61e38 sp=0xc000e61de8 pc=0x481d8c
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
go.etcd.io/bbolt.(*DB).loadFreelist(0xc00057d200)
	/src/loki/vendor/go.etcd.io/bbolt/db.go:309 +0x6a fp=0xc000e61e68 sp=0xc000e61e38 pc=0x146922a
go.etcd.io/bbolt.Open(0xc000bebbc0, 0x37, 0x1b6, 0xc000e62050, 0x37, 0x0, 0x0)
	/src/loki/vendor/go.etcd.io/bbolt/db.go:286 +0x36a fp=0xc000e61f50 sp=0xc000e61e68 pc=0x1468cea
github.com/cortexproject/cortex/pkg/chunk/local.OpenBoltdbFile(...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go:366
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.loadBoltDBsFromDir(0xc000954300, 0x2c, 0x0, 0xc000e62110, 0x5cda3f)
	/src/loki/pkg/storage/stores/shipper/uploads/table.go:493 +0x4fe fp=0xc000e620b0 sp=0xc000e61f50 pc=0x158198e
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.LoadTable(0xc000954300, 0x2c, 0xc0009541b0, 0x24, 0x7ffa8d21e690, 0xc0006a9720, 0x7ffa8d21e668, 0xc0004cd8b0, 0x0, 0x0, ...)
	/src/loki/pkg/storage/stores/shipper/uploads/table.go:86 +0x39 fp=0xc000e62120 sp=0xc000e620b0 pc=0x157d1f9
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.(*TableManager).loadTables(0xc00091a320, 0xc0007029f0, 0x21b82d1, 0x13)
	/src/loki/pkg/storage/stores/shipper/uploads/table_manager.go:242 +0x4a5 fp=0xc000e62318 sp=0xc000e62120 pc=0x1583ae5
github.com/grafana/loki/pkg/storage/stores/shipper/uploads.NewTableManager(0xc0009541b0, 0x24, 0xc0004afde0, 0x20, 0xdf8475800, 0x61c9f36800, 0x7ffa8d21e668, 0xc0004cd8b0, 0x7ffa8d21e690, 0xc0006a9720, ...)
	/src/loki/pkg/storage/stores/shipper/uploads/table_manager.go:57 +0x26c fp=0xc000e62468 sp=0xc000e62318 pc=0x1581e2c
github.com/grafana/loki/pkg/storage/stores/shipper.(*Shipper).init(0xc000486b40, 0x2744680, 0xc0006a9560, 0x2728d00, 0xc000148730, 0x0, 0x0)
	/src/loki/pkg/storage/stores/shipper/shipper_index_client.go:130 +0x445 fp=0xc000e62580 sp=0xc000e62468 pc=0x15869a5
github.com/grafana/loki/pkg/storage/stores/shipper.NewShipper(0xc0004afde0, 0x20, 0xc0007baff0, 0xa, 0xc0004afec0, 0x1f, 0x4e94914f0000, 0x45d964b800, 0xc0007ba2b0, 0x10, ...)
	/src/loki/pkg/storage/stores/shipper/shipper_index_client.go:92 +0x13b fp=0xc000e626a8 sp=0xc000e62580 pc=0x158631b
github.com/grafana/loki/pkg/storage.RegisterCustomIndexClients.func1(0x1e29400, 0xc000474480, 0xc0007baf20, 0xe)
	/src/loki/pkg/storage/store.go:356 +0x186 fp=0xc000e63490 sp=0xc000e626a8 pc=0x1ac6ad6
github.com/cortexproject/cortex/pkg/chunk/storage.NewIndexClient(0xc0007baf20, 0xe, 0x219e158, 0x6, 0x0, 0x4000000000000000, 0x4024000000000000, 0x0, 0x0, 0x186a0, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:208 +0xb7f fp=0xc000e63740 sp=0xc000e63490 pc=0x14b0fbf
github.com/cortexproject/cortex/pkg/chunk/storage.NewStore(0x219e158, 0x6, 0x0, 0x4000000000000000, 0x4024000000000000, 0x0, 0x0, 0x186a0, 0x3ff4cccccccccccd, 0x3ff0000000000000, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:174 +0x70d fp=0xc000e642c8 sp=0xc000e63740 pc=0x14afa7d
github.com/grafana/loki/pkg/loki.(*Loki).initStore(0xc00081e000, 0x1, 0xc00069f840, 0xc000bb8150, 0xc000a88ed0)
	/src/loki/pkg/loki/modules.go:287 +0x2ad fp=0xc000e65f78 sp=0xc000e642c8 pc=0x1bd5e1d
github.com/grafana/loki/pkg/loki.(*Loki).initStore-fm(0x1e24cc0, 0xc000b7e4e0, 0x219d193, 0x5)
	/src/loki/pkg/loki/modules.go:253 +0x2a fp=0xc000e65fb0 sp=0xc000e65f78 pc=0x1bdc77a
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule(0xc000702870, 0x219a8b1, 0x3, 0xc000e660f8, 0xc000b7ea80, 0x0, 0x0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103 +0x2c6 fp=0xc000e660a8 sp=0xc000e65fb0 pc=0x158e8c6
github.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices(0xc000702870, 0xc000e662a0, 0x1, 0x1, 0xc0005304e0, 0x2753660, 0xc0005304e0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75 +0xfe fp=0xc000e661d0 sp=0xc000e660a8 pc=0x158e57e
github.com/grafana/loki/pkg/loki.(*Loki).Run(0xc00081e000, 0xc00069f180, 0x4)
	/src/loki/pkg/loki/loki.go:204 +0x8b fp=0xc000e66320 sp=0xc000e661d0 pc=0x1bd126b
main.main()
	/src/loki/cmd/loki/main.go:130 +0x566 fp=0xc000e69f88 sp=0xc000e66320 pc=0x1bdda06
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x212 fp=0xc000e69fe0 sp=0xc000e69f88 pc=0x437162
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000e69fe8 sp=0xc000e69fe0 pc=0x467811

goroutine 11 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000e2400)
	/src/loki/vendor/go.opencensus.io/stats/view/worker.go:276 +0x100
created by go.opencensus.io/stats/view.init.0
	/src/loki/vendor/go.opencensus.io/stats/view/worker.go:34 +0x68

goroutine 334 [chan receive]:
github.com/cortexproject/cortex/pkg/alertmanager.init.0.func1()
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:87 +0x55
created by github.com/cortexproject/cortex/pkg/alertmanager.init.0
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:83 +0x35

goroutine 200 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00078b4e0)
	/src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3a5
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 214 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00052c820)
	/src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3a5
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 217 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00052c9c0)
	/src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3a5
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/src/loki/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 382 [select]:
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollControllerWithTicker(0xc000a7f860, 0xc000149090)
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:144 +0xd0
github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollController(0xc000a7f860)
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:139 +0x6e
created by github.com/uber/jaeger-client-go.NewRemotelyControlledSampler
	/src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:86 +0x119

goroutine 384 [select]:
github.com/uber/jaeger-client-go/utils.(*reconnectingUDPConn).reconnectLoop(0xc0001869a0, 0x6fc23ac00)
	/src/loki/vendor/github.com/uber/jaeger-client-go/utils/reconnecting_udp_conn.go:70 +0xed
created by github.com/uber/jaeger-client-go/utils.newReconnectingUDPConn
	/src/loki/vendor/github.com/uber/jaeger-client-go/utils/reconnecting_udp_conn.go:60 +0x10f

goroutine 385 [select]:
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc000694ba0)
	/src/loki/vendor/github.com/uber/jaeger-client-go/reporter.go:296 +0x120
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	/src/loki/vendor/github.com/uber/jaeger-client-go/reporter.go:237 +0x1a0

goroutine 400 [chan receive]:
github.com/cortexproject/cortex/pkg/ring/kv/consul.(*mockKV).loop(0xc0006a8600)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/mock.go:54 +0x66
created by github.com/cortexproject/cortex/pkg/ring/kv/consul.NewInMemoryClientWithConfig
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/mock.go:37 +0xd0

goroutine 405 [select]:
github.com/cortexproject/cortex/pkg/util/services.NewTimerService.func1(0x273d900, 0xc00069f800, 0x0, 0x0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/services.go:30 +0x11d
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc000486990)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:167 +0x3f7
created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:96 +0xa8

goroutine 411 [select]:
github.com/cortexproject/cortex/pkg/chunk/local.(*BoltIndexClient).loop(0xc0004cd8b0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go:81 +0x132
created by github.com/cortexproject/cortex/pkg/chunk/local.NewBoltDBIndexClient
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go:70 +0x103
```

GKE Version: v1.17.15-gke.800

**Comment by cstyan** [comment]
Unfortunately I don't have much context around bolt db, but have you tried newer versions of loki? 2.0.0 is almost 1.5 years old. If you also had an older version of Loki running and are now trying to update to 2.0.0 there was an upgrade guide mentioned in the release notes: https://github.com/grafana/loki/releases/tag/v2.0.0

**Comment by dakshrajopenx** [comment]
We have deleted indexes inside boltdb which is getting issue in logs. We have checked that disk and go into that particular node  and delete that index folder.

```boltdb-shipper-active``` and ```boltdb-shipper-cache``` are the two folders in which we have deleted "index_19016".

**Comment by rufreakde** [comment]
> We have deleted indexes inside boltdb which is getting issue in logs. We have checked that disk and go into that particular node and delete that index folder.
> 
> `boltdb-shipper-active` and `boltdb-shipper-cache` are the two folders in which we have deleted "index_19016".

@dakshrajopenx we have a similar issue now how did you access the PV to delete these files when the loki pod that is bound to it with a PVC is failing at startup already? We also 2 indexes failing but I am not able to figure out how to delete them.

**Comment by rufreakde** [comment]
> @rufreakde To find the mount path, you could use `crictl` / `docker` from the node shell:
> 
> 1. Find the container ID
> 
> ```
> > crictl ps -a | grep loki
> 16327bca3152c       e3e722... 10 minutes ago      Running   loki
> ```
> 
>  2. Find the mount path
> 
> ```
> > crictl inspect 16327bca3152c | grep '"source": "/var/lib/kubelet'
> "source": "/var/lib/kubelet/pods/XXX/volumes/XXX/..." <-- MOUNT PATH
> ```

I mean that is fine - issue is how can you access the PV if it is bound via a PVC to a failing loki instance. Manually removing the binding?

In the end I was not able to do this because argocd would revert this temporary change in my setup.

 So I learned my lesson never use persistency from the same helm chart better split into two and reuse! This way you can undeploy loki modify the PV and redeploy rather easily. Even applying backups on PVs is much simpler this way as well.

**Comment by silviu-bsf** [comment]
> I mean that is fine - issue is how can you access the PV if it is bound via a PVC to a failing loki instance. Manually removing the binding?
> 
> In the end I was not able to do this because argocd would revert this temporary change in my setup.
> 
> So I learned my lesson never use persistency from the same helm chart better split into two and reuse! This way you can undeploy loki modify the PV and redeploy rather easily. Even applying backups on PVs is much simpler this way as well.

The PV should be mounted on the node even if the Loki container failed. So you can access the PV by logging into the node through SSH and then finding the mount point with the commands from above.
