### ISSUE TITLE
API to tail logs randomly fails with 1011 (internal server error)

### ISSUE THREAD

**Issue by vlcinsky** [grafana/loki#6417]
**Describe the bug**
Using our own websocket client as well as using logcli, we sometime succeed getting streams of log records, but in other periods fail with error:

> Error reading stream: websocket: close 1011 (internal server error): rpc error: code = Canceled desc = grpc: the client connection is closing

The requests are against Grafana Cloud.

**To Reproduce**
Our requests go against Grafana Cloud selecting log stream which has rate 685 records a minute and during our testing is alive:

```bash
export LOKI_ADDR=https://logs-prod-us-central1.grafana.net
export LOKI_USERNAME=4641
export LOKI_PASSWORD=<redacted>
```
Using **logcli** version 2.2.1 (revision babea82e):
```shell
$ logcli query --tail --timezone UTC --no-labels '{cluster_id="rdstmc-javl",service_name="modulbusrds"}'
wss://logs-prod-us-central1.grafana.net/loki/api/v1/tail?....<etc>
Error reading stream: websocket: close 1011 (internal server error): rpc error: code = Canceled desc = grpc: the client connection is closing
```
It takes around 14 seconds to get the error message.

Using our **python code** the error is the same.

The code is using library [websockets](https://pypi.org/project/websockets/) version 10.3

The code (incomplete) reads:
```python
import asyncio
import websockets
from .record import on_message
from .http import get_url_headers


async def read_messages():
    url, extra_headers = get_url_headers()
    print(f"url: {url}")
    print(f"headers: {extra_headers}")
    async with websockets.connect(url, extra_headers=extra_headers) as ws:

        while True:
            msg = await ws.recv()
            on_message(None, msg)


def main():
    asyncio.run(read_messages())
```
and the erros is the same as with logcli:
```
Traceback (most recent call last):
  File "/home/javl/devel/ttr/gitlab/personal/honza/lokitail/.venv/bin/cliasync", line 5, in <module>
    main()
  File "/home/javl/devel/ttr/gitlab/personal/honza/lokitail/lokitail/cliasync.py", line 19, in main
    asyncio.run(read_messages())
  File "/home/javl/.pyenv/versions/3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/javl/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/javl/devel/ttr/gitlab/personal/honza/lokitail/lokitail/cliasync.py", line 14, in read_messages
    msg = await ws.recv()
  File "/home/javl/devel/ttr/gitlab/personal/honza/lokitail/.venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 553, in recv
    await self.ensure_open()
  File "/home/javl/devel/ttr/gitlab/personal/honza/lokitail/.venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1011 (unexpected error) rpc error: code = Canceled desc = grpc: the client connection is closing; then sent 1011 (unexpected error) rpc error: code = Canceled desc = grpc: the client connection is closing
```
Using **Grafana Cloud Explore in Live mode**:
Initial query (for last 1 hour) shows log records, but activating Live mode does not update anything (we give up after 60 seconds).

**Expected behavior**
We shall receive latest log records as they appear in Loki with short delay (such as 5-15 seconds) and without failing to do so completely.

**Environment:**
 - Infrastructure: Grafana Cloud v9.0.0 (b5c56f637)
 - Client OS: Debian 11, Python 3.10.0, logcli 2.2.1 (revision babea82e)

**Note**
All the tools (logcli, python code, Grafana Cloud web interface) is sometime working without any problem.

**Comment by famarting** [comment]
I'm also seeing a similar behavior, I'm testing against a local loki instance deployed to a Kubernetes Kind cluste (single binary deployment mode)

I enabled debug log in the Loki stateful set and nothing obvious showed up, also looked at the logs of the loki-gateway and again nothing obvious showed up.

What could be the cause of loki giving this `1011` error code in the websockets API?

**Comment by revoltez** [comment]
having the same Issue as well, using loki helm chart, when i call `ws://loki.loki.svc.cluster.local:3100/loki/api/v1/tail?myquery` the dialing works but it fails when i start reading messages:
```
	for {
		_, message, err := c.ReadMessage()
		if err != nil {
			fmt.Printf("Failed Reading Message: %v \n", err)
			return err
		}
		fmt.Printf("Received message: %s\n", message)
	}
```
output:
```
Failed Reading Message: websocket: close 1011 (internal server error): parse error : syntax error: unexpected $end 
```

**Comment by JStickler** [comment]
Closing as stale. This issue was opened against a version of Loki that is no longer supported. If this issues still exists in more recent versions of Loki, please leave a comment and we can reopen the issue.
