### ISSUE TITLE
Loki Docker Driver crashes with "signal SIGSEGV: segmentation violation" when Loki host is not reachable

### ISSUE THREAD

**Issue by pep1** [grafana/loki#670]
First of all: thank you very much for this great Logging Driver @Kuqd 👍 

Just tried it out and found this problem:

**Describe the bug**
When having the new Loki Logging Driver installed and activated on a local Docker Daemon and the Loki host is not reachable the plugin crashes with a segmentation violation during logging.

This is a problem in a local setup using the Loki Docker container during startup when the Loki container itself is not accepting connections yet during startup and Docker wants to start sending logs from other containers.

**To Reproduce**
1. Install the Loki Logging Driver on existing Docker daemon with:
```
docker plugin install  grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
```
2. Configure the Docker daemon to use it by default. In `/etc/docker/daemon.json`:
```
{
  "log-driver": "loki",
  "log-opts": {
    "loki-url": "http://localhost:3100/api/prom/push"
  }
}
```
3. Restart the docker daemon:
```bash
service docker restart
```
4. Start a container that emits stdout logs while *not* having Loki available at `http://localhost:3100/api/prom/push` (I am assuming it end up with "Connection refused")

*Note*: this setup works fine when Loki *is* available at the specified host and port.

**Expected behavior**
The plugin should not cause a segmentation violation and gracefully recover/retry when the specified Loki host is not (yet) reachable.

**Environment:**
 - Infrastructure: bare-metal Ubuntu 18.04
 - Deployment tool: docker-compose

**Screenshots, promtail config, or terminal output**
From the Docker daemon logs:
```
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="panic: runtime error: invalid memory address or nil pointer dereference" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\tpanic: runtime error: invalid memory address or nil pointer dereference" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x549037]" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="goroutine 172 [running]:" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="github.com/grafana/loki/vendor/github.com/go-kit/kit/log.(*context).Log(0xc000667290, 0xc0006883c0, 0x6, 0x6, 0x7f80c0144158, 0xc000208c40)" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\t/go/src/github.com/grafana/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x1a7" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="github.com/grafana/loki/pkg/promtail/client.(*client).sendBatch(0xc000022120, 0xc000533e60)" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\t/go/src/github.com/grafana/loki/pkg/promtail/client/client.go:180 +0x202" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="github.com/grafana/loki/pkg/promtail/client.(*client).run.func1(0xc000022120, 0xc000533df8)" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\t/go/src/github.com/grafana/loki/pkg/promtail/client/client.go:115 +0x38" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="panic(0x16d3580, 0x2a85820)" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\t/usr/local/go/src/runtime/panic.go:513 +0x1b9" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="github.com/grafana/loki/vendor/github.com/go-kit/kit/log.(*context).Log(0xc000630c60, 0xc00063c5a0, 0x6, 0x6, 0x7f80c0144158, 0xc000208c40)" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\t/go/src/github.com/grafana/loki/vendor/github.com/go-kit/kit/log/log.go:124 +0x1a7" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="github.com/grafana/loki/pkg/promtail/client.(*client).sendBatch(0xc000022120, 0xc000296e60)" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\t/go/src/github.com/grafana/loki/pkg/promtail/client/client.go:180 +0x202" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="github.com/grafana/loki/pkg/promtail/client.(*client).run(0xc000022120)" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\t/go/src/github.com/grafana/loki/pkg/promtail/client/client.go:145 +0x249" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="created by github.com/grafana/loki/pkg/promtail/client.New" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
Jun 16 01:04:50 willi dockerd[8509]: time="2019-06-16T01:04:50Z" level=error msg="\t/go/src/github.com/grafana/loki/pkg/promtail/client/client.go:105 +0x33b" plugin=238e6039ab372c206f86717c9cf55df0d8d94c5f31c2aef9e00e8335c257507d
```
It looks like that this problem is not necessarily originated in the driver itself but in the promtrail client code here: https://github.com/grafana/loki/blob/master/pkg/promtail/client/client.go#L180. Unfortunately I am not firm in Go so I have no idea what could be the problem there.
Probably `status` or `error` is `nil` when the connection was refused? Would make sense for `status` when the server didn't even give a response.

**Comment by Kuqd** [comment]
Good catch, looking into it.

**Comment by pep1** [comment]
Excellent, thanks heaps for the quick fix 👍
