### ISSUE TITLE
Flaky test `TestDoubleRegistration`

### ISSUE THREAD

**Issue by chaudum** [grafana/loki#6759]
**Describe the bug**

The test `TestDoubleRegistration` fails every once in a while when running in CI, e.g. happened in https://drone.grafana.net/grafana/loki/14249/2/5

```
panic: Log in goroutine after TestDoubleRegistration has completed: Failed to serve: grpc: the server has been stopped

goroutine 118 [running]:
testing.(*common).logDepth(0xc000283a00, {0xc000151740, 0x32}, 0x3)
	/usr/local/go/src/testing/testing.go:887 +0x4c7
testing.(*common).log(...)
	/usr/local/go/src/testing/testing.go:869
testing.(*common).Logf(0xc000283a00, {0x10267be?, 0xc00049a858?}, {0xc00025efc0?, 0x19f2a90?, 0xc0000daf00?})
	/usr/local/go/src/testing/testing.go:920 +0x5a
github.com/grafana/loki/pkg/storage/stores/indexshipper/gatewayclient.createTestGrpcServer.func1()
	/src/loki/pkg/storage/stores/indexshipper/gatewayclient/gateway_client_test.go:103 +0x6e
created by github.com/grafana/loki/pkg/storage/stores/indexshipper/gatewayclient.createTestGrpcServer
	/src/loki/pkg/storage/stores/indexshipper/gatewayclient/gateway_client_test.go:101 +0x11b
FAIL	github.com/grafana/loki/pkg/storage/stores/indexshipper/gatewayclient	0.101s

```

Log: [logs_grafana_loki_14249_2_5.log](https://github.com/grafana/loki/files/9178660/logs_grafana_loki_14249_2_5.log)

**Expected behavior**

Test does not fail randomly.
 
**Environment:**
 - Infrastructure: Drone CI

**Comment by JStickler** [comment]
Closing as stale. This issue was opened against a version of Loki that is no longer supported. If this issues still exists in more recent versions of Loki, please leave a comment and we can reopen the issue.
