### ISSUE TITLE
-target=read: panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by Ingwersaft** [grafana/loki#7054]
**Describe the bug**
Hi!

I'm currently trying to setup a new loki cluster with the boltdb-shipper. The nodes launched with `-target=write` start without problems, but when starting the `read` nodes I receive the following error:
```
No older events at this moment. 
Retry

2022-09-05T14:28:55.886+02:00	wrote loki config: 121 config.yaml lines

2022-09-05T14:28:56.385+02:00	level=info ts=2022-09-05T12:28:56.38526896Z caller=main.go:103 msg="Starting Loki" version="(version=2.6.1, branch=HEAD, revision=6bd05c9a4)"

2022-09-05T14:28:56.386+02:00	level=info ts=2022-09-05T12:28:56.385930202Z caller=server.go:288 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"

2022-09-05T14:28:56.391+02:00	level=warn ts=2022-09-05T12:28:56.390969917Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksfifocache"

2022-09-05T14:28:56.391+02:00	level=info ts=2022-09-05T12:28:56.391621737Z caller=table_manager.go:252 msg="query readiness setup completed" duration=1.661µs distinct_users_len=0

2022-09-05T14:28:56.391+02:00	level=info ts=2022-09-05T12:28:56.391684871Z caller=shipper.go:124 msg="starting index shipper in RO mode"

2022-09-05T14:28:56.391+02:00	level=info ts=2022-09-05T12:28:56.391711033Z caller=shipper_index_client.go:79 msg="starting boltdb shipper in RO mode"

2022-09-05T14:28:56.392+02:00	level=info ts=2022-09-05T12:28:56.392236964Z caller=worker.go:112 msg="Starting querier worker using query-scheduler and scheduler ring for addresses"

2022-09-05T14:28:56.392+02:00	level=info ts=2022-09-05T12:28:56.392520647Z caller=mapper.go:46 msg="cleaning up mapped rules directory" path=/home/ubuntu/rules

2022-09-05T14:28:56.492+02:00	level=info ts=2022-09-05T12:28:56.492337023Z caller=module_service.go:82 msg=initialising module=server

2022-09-05T14:28:56.495+02:00	level=info ts=2022-09-05T12:28:56.49523445Z caller=module_service.go:82 msg=initialising module=query-frontend-tripperware

2022-09-05T14:28:56.495+02:00	level=info ts=2022-09-05T12:28:56.495403135Z caller=module_service.go:82 msg=initialising module=memberlist-kv

2022-09-05T14:28:56.495+02:00	level=info ts=2022-09-05T12:28:56.495502385Z caller=module_service.go:82 msg=initialising module=compactor

2022-09-05T14:28:56.495+02:00	level=info ts=2022-09-05T12:28:56.49567343Z caller=module_service.go:82 msg=initialising module=query-scheduler

2022-09-05T14:28:56.495+02:00	level=info ts=2022-09-05T12:28:56.495800808Z caller=module_service.go:82 msg=initialising module=ring

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.496932579Z caller=basic_lifecycler.go:261 msg="instance not found in the ring" instance=ip-10-0-26-173.eu-central-1.compute.internal ring=compactor

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497036659Z caller=basic_lifecycler_delegates.go:63 msg="not loading tokens from file, tokens file path is empty"

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497211329Z caller=ring.go:263 msg="ring doesn't exist in KV store yet"

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497295648Z caller=basic_lifecycler.go:261 msg="instance not found in the ring" instance=ip-10-0-26-173.eu-central-1.compute.internal ring=scheduler

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497354182Z caller=basic_lifecycler_delegates.go:63 msg="not loading tokens from file, tokens file path is empty"

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497316562Z caller=ring.go:263 msg="ring doesn't exist in KV store yet"

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497520956Z caller=scheduler.go:617 msg="waiting until scheduler is JOINING in the ring"

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497563697Z caller=module_service.go:82 msg=initialising module=ingester-querier

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497632675Z caller=compactor.go:307 msg="waiting until compactor is JOINING in the ring"

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497660138Z caller=module_service.go:82 msg=initialising module=store

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497676182Z caller=compactor.go:311 msg="compactor is JOINING in the ring"

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497796473Z caller=module_service.go:82 msg=initialising module=ruler

2022-09-05T14:28:56.497+02:00	level=info ts=2022-09-05T12:28:56.497859632Z caller=ruler.go:454 msg="ruler up and running"

2022-09-05T14:28:56.683+02:00	level=info ts=2022-09-05T12:28:56.683239557Z caller=scheduler.go:621 msg="scheduler is JOINING in the ring"

2022-09-05T14:28:56.785+02:00	level=info ts=2022-09-05T12:28:56.785320904Z caller=memberlist_client.go:534 msg="joined memberlist cluster" reached_nodes=5

2022-09-05T14:28:57.498+02:00	level=info ts=2022-09-05T12:28:57.498084257Z caller=compactor.go:321 msg="waiting until compactor is ACTIVE in the ring"

2022-09-05T14:28:57.674+02:00	level=info ts=2022-09-05T12:28:57.674567956Z caller=compactor.go:325 msg="compactor is ACTIVE in the ring"

2022-09-05T14:28:57.687+02:00	level=info ts=2022-09-05T12:28:57.686922474Z caller=scheduler.go:631 msg="waiting until scheduler is ACTIVE in the ring"

2022-09-05T14:28:57.827+02:00	level=info ts=2022-09-05T12:28:57.827Z caller=scheduler.go:635 msg="scheduler is ACTIVE in the ring"

2022-09-05T14:28:57.827+02:00	level=info ts=2022-09-05T12:28:57.827084249Z caller=module_service.go:82 msg=initialising module=querier

2022-09-05T14:28:57.827+02:00	level=info ts=2022-09-05T12:28:57.827145291Z caller=module_service.go:82 msg=initialising module=query-frontend

2022-09-05T14:28:57.829+02:00	panic: non-positive interval for NewTicker

2022-09-05T14:28:57.829+02:00	goroutine 457 [running]:

2022-09-05T14:28:57.829+02:00	time.NewTicker(0x9368f4)

2022-09-05T14:28:57.829+02:00	/usr/local/go/src/time/tick.go:24 +0x10f

2022-09-05T14:28:57.829+02:00	github.com/grafana/loki/pkg/util.(*ringWatcher).watchLoop(0xc000660730, {0x266e2e0, 0xc00081f9c0})

2022-09-05T14:28:57.829+02:00	/src/loki/pkg/util/ring_watcher.go:40 +0x65

2022-09-05T14:28:57.829+02:00	github.com/grafana/dskit/services.(*BasicService).main(0xc00065dcc0)

2022-09-05T14:28:57.829+02:00	/src/loki/vendor/github.com/grafana/dskit/services/basic_service.go:190 +0x1e8

2022-09-05T14:28:57.829+02:00	created by github.com/grafana/dskit/services.(*BasicService).StartAsync.func1

2022-09-05T14:28:57.829+02:00	/src/loki/vendor/github.com/grafana/dskit/services/basic_service.go:119 +0xbe
``` 

Any help would be very appreciated!

**To Reproduce**
1. Started Loki (v2.6.1) with `./loki-linux-amd64 -log.level=info -target=read -memberlist.join="dns+${GOSSIP_DNS}:7946"`

**Environment:**
 - Infrastructure: AWS Fargate
 - Deployment tool: Task definition via terraform 

**Screenshots, Promtail config, or terminal output**
My loki config:
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  http_server_idle_timeout: 600s

memberlist:
  abort_if_cluster_join_fails: true
  bind_port: 7946
  max_join_retries: 20

common:
  storage:
    s3:
      s3: s3://${S3_REGION}/${S3_BUCKET_NAME}
      endpoint: ${S3_BUCKET_ENDPOINT}
  replication_factor: 3
  persist_tokens: false
  ring:
    kvstore:
      store: "memberlist"
    instance_interface_names: [eth1]

limits_config:
  enforce_metric_name: false
  reject_old_samples: false
  reject_old_samples_max_age: 168h
  ingestion_rate_strategy: global
  max_query_lookback: 1008h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  retention_period: 1008h

schema_config:
  configs:
    - from: 2022-09-01
      store: boltdb-shipper
      object_store: s3
      schema: v12
      index:
        prefix: loki_index_
        period: 24h

ruler:
  rule_path: /home/ubuntu/rules
  storage:
    type: s3
    s3:
      s3: s3://${S3_REGION}/${S3_BUCKET_NAME}
      endpoint: ${S3_BUCKET_ENDPOINT}

storage_config:
  aws:
    s3: s3://${S3_REGION}/${S3_BUCKET_NAME}
    endpoint: ${S3_BUCKET_ENDPOINT}
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3
  hedging:
    at: "250ms"
    max_per_second: 20
    up_to: 3

query_scheduler:
  use_scheduler_ring: true

ingester:
  lifecycler:
    interface_names: [eth1]
    ring:
      kvstore:
        store: memberlist
  autoforget_unhealthy: true
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    enabled: true
    flush_on_shutdown: true

distributor:
  ring:
    kvstore:
      store: memberlist
    instance_interface_names: [eth1]

table_manager:

frontend:
  instance_interface_names: [eth1]
frontend_worker:

querier:
  query_timeout: 5m
  max_concurrent: 20
  engine:
    timeout: 5m

ingester_client:
  pool_config:
    health_check_ingesters: true

compactor:
  working_directory: /home/ubuntu/compactor
  shared_store: s3
  compaction_interval: 5m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  compactor_ring:
    kvstore:
      store: memberlist
    instance_interface_names: [ eth1 ]

analytics:
  reporting_enabled: false
```

**Comment by jk2K** [comment]
you should config `tail_max_duration`
```
querier:
  tail_max_duration: 1h
```

**Comment by JStickler** [comment]
Closing this issue as a deprecated component. This panic occurred with boltdb-shipper, which will be removed in Loki 4.0. All users must migrate to TSDB as the index store. If you were affected on an older version, the workaround was to configure `querier.tail_max_duration`. See https://grafana.com/docs/loki/latest/setup/upgrade/ for migration guidance.
