### ISSUE TITLE
Docker container crash on boot

### ISSUE THREAD

**Issue by marcotuna** [grafana/loki#714]
Hello, I am trying to run loki 0.1.0 in a docker container however it keeps crashing on boot.

`docker run grafana/loki:v0.1.0`

```
user@SRV:/home/manager# docker run grafana/loki:v0.1.0
level=info ts=2019-07-03T16:12:32.406462617Z caller=loki.go:125 msg=initialising module=server
level=info ts=2019-07-03T16:12:32.406775586Z caller=server.go:120 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-07-03T16:12:32.407069841Z caller=loki.go:125 msg=initialising module=overrides
level=info ts=2019-07-03T16:12:32.40713033Z caller=override.go:48 msg="per-tenant overides disabled"
level=info ts=2019-07-03T16:12:32.407148093Z caller=loki.go:125 msg=initialising module=table-manager
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xfa49f9]

goroutine 1 [running]:
github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage.NewTableClient(0x1351139, 0x3, 0x0, 0x4000000000000000, 0x0, 0x0, 0x0, 0x186a0, 0x3ff4cccccccccccd, 0x13991a0, ...)
	/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:160 +0x79
github.com/grafana/loki/pkg/loki.(*Loki).initTableManager(0xc0000bb800, 0xc0000a2a20, 0x7)
	/go/src/github.com/grafana/loki/pkg/loki/modules.go:193 +0xf7
github.com/grafana/loki/pkg/loki.(*Loki).initModule(0xc0000bb800, 0x7, 0x0, 0x0)
	/go/src/github.com/grafana/loki/pkg/loki/loki.go:127 +0x1be
github.com/grafana/loki/pkg/loki.(*Loki).init(0xc0000bb800, 0x8, 0xc000551378, 0x10)
	/go/src/github.com/grafana/loki/pkg/loki/loki.go:116 +0x7b
github.com/grafana/loki/pkg/loki.New(0x8, 0x1, 0x1351af9, 0x4, 0x0, 0x0, 0x50, 0x0, 0x0, 0x2387, ...)
	/go/src/github.com/grafana/loki/pkg/loki/loki.go:86 +0x15c
main.main()
	/go/src/github.com/grafana/loki/cmd/loki/main.go:60 +0x264
```

Any hints?
Thanks.

**Comment by Kuqd** [comment]
try

```
docker run grafana/loki:v0.1.0 -config.file=/etc/loki/local-config.yaml
```

No configuration is passed by default but one exist in the container.

**Comment by marcotuna** [comment]
Hello @Kuqd, it worked.
Shouldn't this error be treated?
This misleads the end user when starting a new container from stratch.

**Comment by Kuqd** [comment]
Sure the fix is easy we could default to that path.

**Comment by sh0rez** [comment]
All changes merged.. Close?
