### ISSUE TITLE
Loki keep crashing with panic: EOF

### ISSUE THREAD

**Issue by dorinand** [grafana/loki#7293]
I am running Loki for all environments (dev, stg, prd) with bolt-shipper storage on server. Recently, we encountered full disk on stg so I remove chunks from `chunks` directory based on its age. I thougth, it should be ok because when you use Loki on S3, Loki does not take care about cleanup old chunks. It looks like I was wrong. Since then, I encounter error approximately every 10 minutes:
```
2022-09-29T14:07:15.954959864Z level=info ts=2022-09-29T14:07:15.954786755Z caller=compactor.go:552 msg="compacting table" table-name=index_19250
2022-09-29T14:07:15.956526520Z level=info ts=2022-09-29T14:07:15.956328163Z caller=table.go:138 table-name=index_19250 msg="listed files" count=3
2022-09-29T14:07:15.956583760Z level=info ts=2022-09-29T14:07:15.956381689Z caller=table.go:297 table-name=index_19250 msg="starting compaction of dbs"
2022-09-29T14:07:15.956595342Z level=info ts=2022-09-29T14:07:15.956420826Z caller=table.go:307 table-name=index_19250 msg="using compactor-1663887002.gz as seed file"
2022-09-29T14:07:15.968686855Z level=info ts=2022-09-29T14:07:15.968433882Z caller=util.go:116 table-name=index_19250 file-name=compactor-1663887002.gz msg="downloaded file" total_time=11.997144ms
2022-09-29T14:07:16.010864173Z level=info ts=2022-09-29T14:07:16.010644331Z caller=util.go:116 table-name=index_19250 file-name=compactor-1663888802.gz msg="downloaded file" total_time=29.685205ms
2022-09-29T14:07:16.011175893Z panic: EOF
2022-09-29T14:07:16.011226332Z
2022-09-29T14:07:16.011254391Z goroutine 8059 [running]:
2022-09-29T14:07:16.011270408Z github.com/grafana/loki/pkg/storage/stores/shipper/util.getGzipReader({0x26301e0, 0xc006b2ac58})
2022-09-29T14:07:16.011309552Z 	/src/loki/pkg/storage/stores/shipper/util/util.go:47 +0xb1
2022-09-29T14:07:16.011325308Z github.com/grafana/loki/pkg/storage/stores/shipper/util.DownloadFileFromStorage({0xc008fa1980, 0x33}, 0x1, 0x0, {0x2629f40, 0xc006b25e00}, 0xc0067556e0)
2022-09-29T14:07:16.011346132Z 	/src/loki/pkg/storage/stores/shipper/util/util.go:105 +0x22c
2022-09-29T14:07:16.011413571Z github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*table).compactFiles.func2({0x17f8d20, 0xc00a51e8e8}, 0xc006708120)
2022-09-29T14:07:16.011437908Z 	/src/loki/pkg/storage/stores/shipper/compactor/table.go:332 +0x209
2022-09-29T14:07:16.011447161Z github.com/grafana/dskit/concurrency.ForEachJob.func1()
2022-09-29T14:07:16.011456899Z 	/src/loki/vendor/github.com/grafana/dskit/concurrency/runner.go:105 +0x8a
2022-09-29T14:07:16.011470348Z golang.org/x/sync/errgroup.(*Group).Go.func1()
2022-09-29T14:07:16.011482709Z 	/src/loki/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x67
2022-09-29T14:07:16.011496544Z created by golang.org/x/sync/errgroup.(*Group).Go
2022-09-29T14:07:16.011527202Z 	/src/loki/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x9
```

Then, Loki is shut down and starts again. It looks like compactor keeps some information about chunks and now, it cant handle missing chunks. I can see in compactor directory two directories - `retention` (this is on all environments) and `index_19250` (this is only on stg Loki). In compactor directory, there are three files:
````
compactor-1663887002.gz
compactor-1663888802.gz
compactor-1663889402.gz
````
As you can see, the last processed compactor file before crash is `compactor-1663888802.gz`, maybe it is corrupted?

This is indices directories in `chunks/index`:
````
drwxr-xr-x  2 10001 10001    4096 Sep 23 02:00 index_19250
drwxr-xr-x  2 10001 10001    4096 Sep 23 02:10 index_19251
drwxr-xr-x  2 10001 10001    4096 Sep 26 21:16 index_19252
drwxr-xr-x  2 10001 10001    4096 Sep 26 21:16 index_19253
drwxr-xr-x  2 10001 10001    4096 Sep 26 21:16 index_19254
drwxr-xr-x  2 10001 10001    4096 Sep 26 21:16 index_19255
drwxr-xr-x  2 10001 10001    4096 Sep 22 16:10 index_19256
drwxr-xr-x  2 10001 10001    4096 Sep 23 04:02 index_19257
drwxr-xr-x  2 10001 10001   20480 Sep 24 03:46 index_19258
drwxr-xr-x  2 10001 10001   24576 Sep 25 04:17 index_19259
drwxr-xr-x  2 10001 10001   20480 Sep 26 04:12 index_19260
drwxr-xr-x  2 10001 10001   20480 Sep 27 04:14 index_19261
drwxr-xr-x  2 10001 10001   20480 Sep 28 04:02 index_19262
drwxr-xr-x  2 10001 10001   20480 Sep 29 04:02 index_19263
drwxr-xr-x  2 10001 10001   12288 Sep 29 17:04 index_19264
````
I think, I can stop and delete index_19250 directory from compactor directory but I am not sure Loki can survive this steps. Can somebody help me how to solve this?

Loki is running fine, I can search and filter data, the problem is once per ten 10 min (when compactor process is running) the Loki crashes and start again.

Loki version: v2.6.1

**Comment by dorinand** [comment]
Hi @DylanGuedes , thanks for your tip. I will try it and update the state of Loki.

**Comment by dorinand** [comment]
I solved the issue with this steps:

1. Stopped Loki
2. In `compactor` directory, I removed problematic index - `index_19250`. After restart this directory with all files inside has been created again.
3. Directory `chunks/index/index_19250` contains 3 files `compactor-1663887002.gz`, `compactor-1663888802.gz` and `compactor-1663889402.gz`. The last one was suspicious - size 0B and group and owner was root. So I removed it. This steps solved it.
4. Start Loki

After this, Loki runs without problem for more than 6 hours.

**Comment by YarekTyshchenko** [comment]
Had this issue just now too. IMO Loki should handle this somehow, or at least print the filename of the offending index instead of panicking. I had to clear the whole dataset for it to start.
The logs aren't critical, but i'd still be nice to try to save them
