### ISSUE TITLE
fluentd-plugin-grafana-loki: error_class=NoMethodError error="undefined method `each' for nil:NilClass"

### ISSUE THREAD

**Issue by candlerb** [grafana/loki#749]
**Describe the bug**

fluentd-plugin-grafana-loki gives a backtrace whenever any message written to loki.  Full backtrace provided at end.

**To Reproduce**
1. Started loki (de83272b)
2. Install fluentd gem (1.6.2)
3. Install fluent-plugin-grafana-loki gem (1.0.0).  Note that local gem build is required as described in https://github.com/grafana/loki/issues/719#issuecomment-508866149
4. Configure:

```
<source>
  @type udp
  tag syslog
  port 5140
  bind 0.0.0.0
  source_address_key instance
  <parse>
    @type none
  </parse>
</source>

<match syslog.**>
  @type copy
<store>
  @type file
  path /var/log/fluent/syslog
  compress gzip
  #<format>
  #  @type single_value
  #</format>
  <buffer>
    timekey_use_utc
  </buffer>
</store>

<store>
  @type loki
  url "http://x.x.x.x:3100"
  extra_labels {"job":"syslog"}
  drop_single_key true
  flush_interval 10s
  flush_at_shutdown true
  buffer_chunk_limit 1m
</store>
</match>
```

5. Send syslog packets to port 5140

**Expected behavior**

syslogs to be delivered to loki

**Environment:**
 - Infrastructure: Ubuntu 16.04.5 lxd container inside Ubuntu 18.04.2 host
 - Deployment tool: loki built from source, fluentd installed using "gem install"

**Screenshots, promtail config, or terminal output**

```
Jul 14 19:23:47 fluentd fluentd[15731]: 2019-07-14 19:23:47 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `each' for nil:NilClass"
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-grafana-loki-1.0.0/lib/fluent/plugin/out_loki.rb:184:in `line_to_loki'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-grafana-loki-1.0.0/lib/fluent/plugin/out_loki.rb:213:in `block in chunk_to_loki'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/event.rb:323:in `each'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/event.rb:323:in `block in each'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/event.rb:322:in `each'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-grafana-loki-1.0.0/lib/fluent/plugin/out_loki.rb:210:in `chunk_to_loki'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-grafana-loki-1.0.0/lib/fluent/plugin/out_loki.rb:116:in `generic_to_loki'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-grafana-loki-1.0.0/lib/fluent/plugin/out_loki.rb:84:in `write'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/plugin/output.rb:1128:in `try_flush'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/plugin/output.rb:1434:in `flush_thread_run'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/plugin/output.rb:457:in `block (2 levels) in start'
Jul 14 19:23:47 fluentd fluentd[15731]:   2019-07-14 19:23:47 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.6.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
Jul 14 19:23:47 fluentd fluentd[15731]: 2019-07-14 19:23:47 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_536830/58da91480cb370a8382cb05ec00edd47.log
```

Subsequent messages just give:

```
Jul 14 19:23:57 fluentd fluentd[15731]: 2019-07-14 19:23:57 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `each' for nil:NilClass"
Jul 14 19:23:57 fluentd fluentd[15731]:   2019-07-14 19:23:57 +0000 [warn]: #0 suppressed same stacktrace
Jul 14 19:23:57 fluentd fluentd[15731]: 2019-07-14 19:23:57 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_536830/58da91521a9ad4f35c976a8483102e2d.log
```

**Comment by candlerb** [comment]
@remove_keys and @label_keys default to nil, and as the error says, you can't iterate over nil.  The following fixes it for me:

```
--- /var/lib/gems/2.3.0/gems/fluent-plugin-grafana-loki-1.0.0/lib/fluent/plugin/out_loki.rb.orig	2019-07-14 19:40:13.521379017 +0000
+++ /var/lib/gems/2.3.0/gems/fluent-plugin-grafana-loki-1.0.0/lib/fluent/plugin/out_loki.rb	2019-07-14 19:40:48.352519196 +0000
@@ -183,14 +183,14 @@
           # remove needless keys.
           @remove_keys.each { |v|
             record.delete(v)
-          }
+          } if @remove_keys
           # extract white listed record keys into labels.
           @label_keys.each do |k|
             if record.key?(k)
               chunk_labels[k] = record[k]
               record.delete(k)
             end
-          end
+          end if @label_keys
           line = record_to_line(record)
         else
           line = record.to_s
```

Looks like this plugin hasn't had much in the way of testing though :-(

**Comment by dawidmalina** [comment]
Good catch 👍 Can you drop a pull request with this change? I agree testing plan (strategy) for this plugin would be needed.
