### ISSUE TITLE
Promtail - failed to get the complete long log in one line

### ISSUE THREAD

**Issue by wenlinhe** [grafana/loki#7862]
**Describe the bug**
We have some log very long, such as 8000+ characters in one line in the SystemOut /logs/console.log, but Promtail can only scrape part of that, sometimes 2000+ characters, sometimes 4000+ characters. 

**To Reproduce**
1. Long logs in the SystemOut /logs/console.log
2. Check Promtail scraped logs files under /var/log/pods/xxx/xxx/0.log, noticed the long log line not scraped complely.

**Expected behavior**
The long log line should be captured in Promtail.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 Openshift v4.10
 - Deployment tool: [e.g., helm, jsonnet]
 helm.
Promtail version:
promtail, version 2.6.1 (branch: HEAD, revision: 6bd05c9a4)
  build user:       root@458047b5501a
  build date:       2022-07-18T08:48:45Z
  go version:       go1.17.9
  platform:         linux/amd64

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

For example original log line:
```
2022-12-05T10:07:35.352000000Z, ERROR, -, 498b1df0-b101-48fe-9c21-579a6b578b77, Default Executor-thread-4, 54, com.xxx.ab.openxxx.provider.opendoor.external.service.AuthenticationService, JWT authentication failed!, com.xxx.ab.huts.common.exceptions.HutsCommonException: Authorization header is empty?	at com.xxx.ab.huts.common.auth.JwtToken.verifyAuthIsBearer(JwtToken.java:65)?	at com.xxx.ab.huts.common.auth.JwtToken.getJwtValue(JwtToken.java:38)?	at com.xxx.ab.huts.common.auth.JwtAuthenticationTool.processJwt(JwtAuthenticationTool.java:78)?	at com.xxx.ab.huts.common.auth.JwtAuthenticationTool.authenticateJwt(JwtAuthenticationTool.java:70)?	at com.xxx.ab.openxxx.provider.opendoor.external.service.AuthenticationService.getAuthenticationInfo(AuthenticationService.java:69)?	at com.xxx.ab.openxxx.provider.opendoor.filters.AuthenticationFilter.filter(AuthenticationFilter.java:29)?	at org.springframeabrk.cloud.opendoor.filter.OrderedopendoorFilter.filter(OrderedopendoorFilter.java:44)?	at org.springframeabrk.cloud.opendoor.handler.FilteringWebHandler$DefaultopendoorFilterChain.lambda$filter$0(FilteringWebHandler.java:117)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)?	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)?	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)?	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282)?	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)?	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)?	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:238)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onSubscribe(MdcContextLifterConfiguration.java:56)?	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoFlatMap$FlatMapM
ain.onNext(MonoFlatMap.java:157)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282)?	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)?	at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.innerResult(MonoFilterWhen.java:202)?	at reactor.core.publisher.MonoFilterWhen$FilterWhenInner.onNext(MonoFilterWhen.java:270)?	at reactor.core.publisher.MonoFilterWhen$FilterWhenInner.onNext(MonoFilterWhen.java:238)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)?	at reactor.core.publisher.MonoFilterWhen$FilterWhenInner.onSubscribe(MonoFilterWhen.java:259)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onSubscribe(MdcContextLifterConfiguration.java:56)?	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onNext(MonoFilterWhen.java:159)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)?	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)?	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152)?	at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onSubscribe(MonoFilterWhen.java:112)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onSubscribe(MdcContextLifterConfiguration.java:56)?	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122)?	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:451)?	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:98)?	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:44)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration.java:52)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.runWithMdcContext(MdcContextLifterConfiguration.java:87)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onNext(MdcContextLifterConfiguration.java:52)?	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)?	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)?	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.request(FluxDematerialize.java:127)?	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:236)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onSubscribe(MdcContextLifterConfiguration.java:56)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onSubscribe(MdcContextLifterConfiguration.java:56)?	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onSubscribe(FluxDematerialize.java:77)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onSubscribe(MdcContextLifterConfiguration.java:56)?	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)?	at reactor.core.publisher.FluxIterable.s
ubscribe(FluxIterable.java:87)?	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)?	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:451)?	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.onSubscribe(MdcContextLifterConfiguration.java:56)?	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)?	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)?	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)?	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at org.springframeabrk.http.server.reactive.ServletHttpHandlerAdapter.service(ServletHttpHandlerAdapter.java:198)?	at com.xxx.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)?	at com.xxx.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)?	at com.xxx.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)?	at com.xxx.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1227)?	at com.xxx.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1011)?	at com.xxx.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)?	at com.xxx.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:85)?	at com.xxx.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)?	at com.xxx.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)?	at com.xxx.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1239)?	at com.xxx.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:468)?	at com.xxx.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:427)?	at com.xxx.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)?	at com.xxx.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)?	at com.xxx.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)?	at com.xxx.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)?	at com.xxx.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)?	at com.xxx.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)?	at com.xxx.ws.tcpchannel.internal.abrkQueueManager.requestComplete(abrkQueueManager.java:514)?	at com.xxx.ws.tcpchannel.internal.abrkQueueManager.attemptIO(abrkQueueManager.java:584)?	at com.xxx.ws.tcpchannel.internal.abrkQueueManager.abrkerRun(abrkQueueManager.java:968)?	at com.xxx.ws.tcpchannel.internal.abrkQueueManager$abrker.run(abrkQueueManager.java:1057)?	at com.xxx.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)?	at java.base/java.util.concurrent.ThreadPoolExecutor.runabrker(ThreadPoolExecutor.java:1136)?	at java.base/java.util.concurrent.ThreadPoolExecutor$abrker.run(ThreadPoolExecutor.java:635)?	at java.base/java.lang.Thread.run(Thread.java:858)?
```
I can only get part of it in below:
```
2022-12-05T10:07:35.352000000Z, ERROR, -, 498b1df0-b101-48fe-9c21-579a6b578b77, Default Executor-thread-4, 54, com.xxx.ab.openxxx.provider.opendoor.external.service.AuthenticationService, JWT authentication failed!, com.xxx.ab.huts.common.exceptions.HutsCommonException: Authorization header is empty?	at com.xxx.ab.huts.common.auth.JwtToken.verifyAuthIsBearer(JwtToken.java:65)?	at com.xxx.ab.huts.common.auth.JwtToken.getJwtValue(JwtToken.java:38)?	at com.xxx.ab.huts.common.auth.JwtAuthenticationTool.processJwt(JwtAuthenticationTool.java:78)?	at com.xxx.ab.huts.common.auth.JwtAuthenticationTool.authenticateJwt(JwtAuthenticationTool.java:70)?	at com.xxx.ab.openxxx.provider.opendoor.external.service.AuthenticationService.getAuthenticationInfo(AuthenticationService.java:69)?	at com.xxx.ab.openxxx.provider.opendoor.filters.AuthenticationFilter.filter(AuthenticationFilter.java:29)?	at org.springframeabrk.cloud.opendoor.filter.OrderedopendoorFilter.filter(OrderedopendoorFilter.java:44)?	at org.springframeabrk.cloud.opendoor.handler.FilteringWebHandler$DefaultopendoorFilterChain.lambda$filter$0(FilteringWebHandler.java:117)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)?	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)?	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)?	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)?	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)?	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)?	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)?	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)?	at com.xxx.ab.openxxx.provider.opendoor.MdcContextLifterConfiguration$MdcContextLifter.lambda$onNext$0(MdcContextLifterConfiguration
```

The Promtail config here is:
```

scrape_configs:
  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
  - job_name: kubernetes-pods
    pipeline_stages:
      - multiline:
          firstline: '^\{'
          max_wait_time: 10s
      - replace:
          expression: '([\n])'
          replace: ''  
      - cri: {}
      - static_labels:
         cluster: xxxx
         region: xxxx
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
```

**Comment by JStickler** [comment]
Promtail is end of life (EOL) as of  March 2, 2026.  No future support or updates will be provided. All future feature development will occur in [Grafana Alloy](https://github.com/grafana/alloy).
