### ISSUE TITLE
loki crahses on start with SIGBUS without log output

### ISSUE THREAD

**Issue by evilscientress** [grafana/loki#8074]
I have a minimal bare metal setup of loki, single node.
After an error where the node ran out of storage space loki crashes on start, before any log output, so I can't trace it down to a corrupted chunk or index. I tried to narrow it down by monitoring file operations with s-trace, but loki crashes before any chunk or index file is opened.  To rule out other errors I temporally pointed the config to a new storage folder, then loki starts again.

loki -version: (2.7.1 apt package from apt.grafana.com)
```
loki, version HEAD-e0af1cc (branch: HEAD, revision: e0af1cc8a)
  build user:       root@5004faa13e2e
  build date:       2022-12-09T19:23:40Z
  go version:       go1.19.2
  platform:         linux/amd64
```

This is the console output, cropped after the first goroutine:
```
loki -config.file /etc/loki/config.yml -log.level=debug
unexpected fault address 0x7f308cb0f008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f308cb0f008 pc=0x197ad71]

goroutine 1 [running]:
runtime.throw({0x235a721?, 0x7f30b4405a68?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc000c0ca00 sp=0xc000c0c9d0 pc=0x43a09d
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:832 +0x125 fp=0xc000c0ca50 sp=0xc000c0ca00 pc=0x4508c5
go.etcd.io/bbolt.(*elemRef).isLeaf(...)
        /drone/src/vendor/go.etcd.io/bbolt/cursor.go:387
go.etcd.io/bbolt.(*Cursor).first(0xc000c0cb60)
        /drone/src/vendor/go.etcd.io/bbolt/cursor.go:170 +0x51 fp=0xc000c0cab0 sp=0xc000c0ca50 pc=0x197ad71
go.etcd.io/bbolt.(*Cursor).First(0xc000c0cb60)
        /drone/src/vendor/go.etcd.io/bbolt/cursor.go:36 +0x11a fp=0xc000c0cb30 sp=0xc000c0cab0 pc=0x197a5da
go.etcd.io/bbolt.(*Bucket).ForEach(0xc00059a478, 0xc000c0cba0)
        /drone/src/vendor/go.etcd.io/bbolt/bucket.go:389 +0x70 fp=0xc000c0cb90 sp=0xc000c0cb30 pc=0x1978030
go.etcd.io/bbolt.(*Tx).ForEach(0xc000683620?, 0xc000c0cbe8?)
        /drone/src/vendor/go.etcd.io/bbolt/tx.go:128 +0x49 fp=0xc000c0cbc8 sp=0xc000c0cb90 pc=0x1987be9
github.com/grafana/loki/pkg/storage/stores/shipper/index.loadBoltDBsFromDir.func1(0xc000c0cc20?)
        /drone/src/pkg/storage/stores/shipper/index/table.go:382 +0x39 fp=0xc000c0cbf8 sp=0xc000c0cbc8 pc=0x1ba5679
go.etcd.io/bbolt.(*DB).View(0xc0000c8100?, 0xc000c0cd78)
        /drone/src/vendor/go.etcd.io/bbolt/db.go:772 +0x82 fp=0xc000c0cc60 sp=0xc000c0cbf8 pc=0x197e6c2
github.com/grafana/loki/pkg/storage/stores/shipper/index.loadBoltDBsFromDir({0xc000d24ba0, 0x2f}, 0xc000764c40)
        /drone/src/pkg/storage/stores/shipper/index/table.go:381 +0x65b fp=0xc000c0cde8 sp=0xc000c0cc60 pc=0x1ba521b
github.com/grafana/loki/pkg/storage/stores/shipper/index.LoadTable({0xc000d24ba0, 0x2f}, {0xc000506fe0, 0x1e}, {0x7f308cc0cda0, 0xc0006863c0}, 0x0?, 0x0?)
        /drone/src/pkg/storage/stores/shipper/index/table.go:75 +0x46 fp=0xc000c0ce40 sp=0xc000c0cde8 pc=0x1ba1b86
github.com/grafana/loki/pkg/storage/stores/shipper/index.(*TableManager).loadTables(0xc000955cb0)
        /drone/src/pkg/storage/stores/shipper/index/table_manager.go:226 +0x675 fp=0xc000c0d038 sp=0xc000c0ce40 pc=0x1ba7275
github.com/grafana/loki/pkg/storage/stores/shipper/index.NewTableManager({{0xc000506fe0, 0x1e}, {0xc000d24720, 0x23}, 0x1176592e000, 0x0}, {0x7f308cc0cda0, 0xc0006863c0}, {0x2856cc0, 0xc0006de180})
        /drone/src/pkg/storage/stores/shipper/index/table_manager.go:65 +0x24b fp=0xc000c0d160 sp=0xc000c0d038 pc=0x1ba596b
github.com/grafana/loki/pkg/storage/stores/shipper.(*indexClient).init(0xc000747a00, {0x2867678, 0xc0005ece20}, {0x7f308cc0c428, 0xc0005da2e8}, 0x7f30b4405a68?, {0xc0006da5b8, 0x1, 0x1}, {0x2856cc0, ...})
        /drone/src/pkg/storage/stores/shipper/shipper_index_client.go:104 +0x2ef fp=0xc000c0d558 sp=0xc000c0d160 pc=0x1ba822f
github.com/grafana/loki/pkg/storage/stores/shipper.NewShipper({{{0xc000d24720, 0x23}, {0xc0007490f0, 0xa}, {0x235c405, 0x6}, {0xc000d24750, 0x22}, 0x4e94914f0000, 0x45d964b800, ...}, ...}, ...)
        /drone/src/pkg/storage/stores/shipper/shipper_index_client.go:73 +0x1b7 fp=0xc000c0d810 sp=0xc000c0d558 pc=0x1ba7cf7
github.com/grafana/loki/pkg/storage.NewIndexClient({_, _}, {{{{0x0}, 0x4000000000000000, 0x4024000000000000, {{...}, 0x186a0, 0x3ff4cccccccccccd, 0x3ff0000000000000, {...}, ...}, ...}, ...}, ...}, ...)
        /drone/src/pkg/storage/factory.go:190 +0xa13 fp=0xc000c0e850 sp=0xc000c0d810 pc=0x1be5473
github.com/grafana/loki/pkg/storage.(*store).storeForPeriod(0xc000bf8000, {{0x17557e7a400}, {0xc0000d5c40, 0xe}, {0xc0000d5c70, 0xa}, {0xc0000d5c88, 0x3}, {{0xc0000d5ca0, 0x6}, ...}, ...}, ...)
        /drone/src/pkg/storage/store.go:268 +0xd46 fp=0xc000c11398 sp=0xc000c0e850 pc=0x1bebb06
github.com/grafana/loki/pkg/storage.(*store).init(0xc000bf8000)
        /drone/src/pkg/storage/store.go:164 +0x39d fp=0xc000c115b8 sp=0xc000c11398 pc=0x1bea77d
github.com/grafana/loki/pkg/storage.NewStore({{{{0x0}, 0x4000000000000000, 0x4024000000000000, {{...}, 0x186a0, 0x3ff4cccccccccccd, 0x3ff0000000000000, {...}, {...}, {...}, ...}, ...}, ...}, ...}, ...)
        /drone/src/pkg/storage/store.go:147 +0xa3b fp=0xc000c11a20 sp=0xc000c115b8 pc=0x1bea27b
github.com/grafana/loki/pkg/loki.(*Loki).initStore(0xc00056c000)
        /drone/src/pkg/loki/modules.go:632 +0x5b4 fp=0xc000c13b78 sp=0xc000c11a20 pc=0x1d67814
github.com/grafana/loki/pkg/loki.(*Loki).initStore-fm()
        <autogenerated>:1 +0x26 fp=0xc000c13b90 sp=0xc000c13b78 pc=0x1d70c26
github.com/grafana/dskit/modules.(*Manager).initModule(0xc0000bbd70, {0x2358900, 0x3}, 0x1?, 0xc00087a180?)
        /drone/src/vendor/github.com/grafana/dskit/modules/modules.go:120 +0x224 fp=0xc000c13c98 sp=0xc000c13b90 pc=0x1a5aa44
github.com/grafana/dskit/modules.(*Manager).InitModuleServices(0x83fab4?, {0xc00061e380, 0x1, 0xc000502840?})
        /drone/src/vendor/github.com/grafana/dskit/modules/modules.go:92 +0x10c fp=0xc000c13db8 sp=0xc000c13c98 pc=0x1a5a7ac
github.com/grafana/loki/pkg/loki.(*Loki).Run(0xc00056c000, {0xc0005e7c40?})
        /drone/src/pkg/loki/loki.go:363 +0x56 fp=0xc000c13f48 sp=0xc000c13db8 pc=0x1d5cdf6
main.main()
        /drone/src/cmd/loki/main.go:105 +0xdb5 fp=0xc000c17f80 sp=0xc000c13f48 pc=0x1d72ef5
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000c17fe0 sp=0xc000c17f80 pc=0x43c8f2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000c17fe8 sp=0xc000c17fe0 pc=0x46e441
```
Full Version can be found here: https://gist.github.com/evilscientress/295a1fa9182b0d614c644a2848ba4334

My config file:
```.yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: debug

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 256

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
    alertmanager_url: http://localhost:9093
```

I don't have experience with debugging go applications, so I can't pinpoint the error myself.

**Comment by dannykopping** [comment]
Looks like someone ran into a similar issue with Prometheus: https://github.com/prometheus/prometheus/issues/9923

I'm not convinced this is a bug necessarily, but we could certainly add a check before whatever is encountering this error throws a fatal, as well as some better error messaging around what to look for.

**Comment by evilscientress** [comment]
In the linked issue the problem was fixed with increasing storage space, but here that is not the case. There currently is 25GB of free space for loki, yet loki doesn't start anymore.

**Comment by dannykopping** [comment]
Can you please send the result of `df -h /<your-path>` please? You may have run out of inodes.

**Comment by dannykopping** [comment]
Are you sure that `/var/lib` is a subdir of `/`, and not a separate mount?

**Comment by dannykopping** [comment]
Without further details about your system, I'm not sure what else it could be. The OS is generating this `SIGBUS` error which Loki is just relaying, so I'm going to close this since it's not a Loki bug.

We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by piec** [comment]
Hi,
I have just had the same issue after having a full PVC (volume).
As the data was trashable I tried to remove the `boltdb-shipper-*` dirs and it solved the issue.
I also kept all of my logs apparently (in chunks?).

I'm not sure what the impact of removing the dirs is.

**Comment by yariksheptykin** [comment]
Thanks @piec , you saved our log data. I also encountered SIGBUS error when the volume in kubernetes (via PVC) run full. After successfully expanding the volume to a higher capacity, the loki container still would not start. Deleting all boltdb-shipper-* on the volume solved the issue, got the container booted and the log data persisted.
