### ISSUE TITLE
Flaky integration test timeout

### ISSUE THREAD

**Issue by bboreham** [grafana/loki#8076]
**Describe the bug**
CI tests failed on unrelated change: https://drone.grafana.net/grafana/loki/18547/3/5
By looking at Drone logs in Loki I count similar 25 timeouts in the last 7 days, out of ~100 builds. Seems like a high percentage.

Ref #8072 

**To Reproduce**
See title.

**Expected behavior**
A given test either always passes or always fails.

**Environment:**
CI

**Screenshots, Promtail config, or terminal output**
```
time="2023-01-05T18:21:06Z" level=info msg="server listening on addresses" grpc="[::]:41535" http="[::]:39819"
time="2023-01-05T18:21:06Z" level=info msg="server listening on addresses" grpc="[::]:41475" http="[::]:45191"
...
panic: test timed out after 10m0s

goroutine 8551 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00035b380, {0x2446259?, 0x52eb25?}, 0x24cfdf0)
	/usr/local/go/src/testing/testing.go:1494 +0x37a
testing.runTests.func1(0xc00035b380?)
	/usr/local/go/src/testing/testing.go:1846 +0x6e
testing.tRunner(0xc00035b380, 0xc0009bfca0)
	/usr/local/go/src/testing/testing.go:1446 +0x10b
testing.runTests(0xc0007d7180?, {0x3b0a1a0, 0x7, 0x7}, {0x7fbc32c485b8?, 0x40?, 0x3b30c80?})
	/usr/local/go/src/testing/testing.go:1844 +0x456
testing.(*M).Run(0xc0007d7180)
	/usr/local/go/src/testing/testing.go:1726 +0x5d9
main.main()
	_testmain.go:107 +0x255

goroutine 8103 [select, 9 minutes]:
github.com/grafana/loki/integration/cluster.(*Component).run(0xc0031c8780)
	/src/loki/integration/cluster/cluster.go:405 +0x419
github.com/grafana/loki/integration/cluster.(*Cluster).Run(0x21850e0?)
	/src/loki/integration/cluster/cluster.go:178 +0x4c
github.com/grafana/loki/integration.TestSimpleScalable_Legacy_IngestQuery(0xc00132f6c0)
	/src/loki/integration/loki_simple_scalable_test.go:32 +0x319
testing.tRunner(0xc00132f6c0, 0x24cfdf0)
	/usr/local/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x35f
...
```

**Comment by Segflow** [comment]
The flaky test named here, TestSimpleScalable_Legacy_IngestQuery, no longer exists: the Simple Scalable Deployment targets and their integration tests were removed in #21481, and Loki CI has moved off Drone.
