### ISSUE TITLE
Panic in `pkg/storage/stores/shipper.(*indexClient).BatchWrite`

### ISSUE THREAD

**Issue by chaudum** [grafana/loki#8190]
**Describe the bug**

The BatchWrite function of the index client fails in certain circumstances with the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1c39d38]
```

**To Reproduce**

1. Run the integration tests multiple times, like so `go test -count=100 -v ./integration/...`
1. The code eventually panics

**Expected behavior**

Tests should pass and there is no panic in the flush code, no matter how often the tests are run.

**Screenshots, Promtail config, or terminal output**

```
=== RUN   TestMicroServicesDeleteRequest
time="2023-01-18T10:45:22+01:00" level=info msg="server listening on addresses" grpc="[::]:40375" http="[::]:39453"
level=debug component=compactor msg="readiness probe" code=503
level=debug component=compactor msg="readiness probe" code=200
time="2023-01-18T10:45:22+01:00" level=info msg="server listening on addresses" grpc="[::]:38999" http="[::]:38583"
level=debug component=distributor msg="readiness probe" code=200
time="2023-01-18T10:45:22+01:00" level=info msg="server listening on addresses" grpc="[::]:36375" http="[::]:39903"
level=debug component=ingester msg="readiness probe" code=200
time="2023-01-18T10:45:23+01:00" level=info msg="server listening on addresses" grpc="[::]:37029" http="[::]:45387"
level=debug component=query-scheduler msg="readiness probe" code=200
time="2023-01-18T10:45:23+01:00" level=info msg="server listening on addresses" grpc="[::]:33911" http="[::]:33205"
level=debug component=query-frontend msg="readiness probe" code=200
time="2023-01-18T10:45:23+01:00" level=info msg="server listening on addresses" grpc="[::]:32893" http="[::]:46853"
level=debug component=querier msg="readiness probe" code=200
=== RUN   TestMicroServicesDeleteRequest/ingest-logs-store
=== RUN   TestMicroServicesDeleteRequest/ingest-logs-ingester
=== RUN   TestMicroServicesDeleteRequest/query
=== RUN   TestMicroServicesDeleteRequest/flush-logs-and-restart-ingester-querier
time="2023-01-18T10:45:23+01:00" level=info msg="=== Handler.Stop()'d ==="
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1c39d38]

goroutine 22635 [running]:
github.com/grafana/loki/pkg/storage/stores/shipper.(*indexClient).BatchWrite.func1({0x294f800?, 0xc00248e540?})
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/shipper/shipper_index_client.go:159 +0x38
github.com/weaveworks/common/instrument.CollectedRequest({0x294f800, 0xc00248e420}, {0x2415064, 0x5}, {0x294a430, 0xc002cf5020}, 0x42?, 0xc0024d70a0)
	/home/christian/sandbox/grafana/loki/vendor/github.com/weaveworks/common/instrument/instrument.go:167 +0x27a
github.com/grafana/loki/pkg/storage/stores/shipper.(*indexClient).BatchWrite(0xc001807600, {0x294f800, 0xc00248e420}, {0x29410c8, 0xc002cf5018})
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/shipper/shipper_index_client.go:158 +0xec
github.com/grafana/loki/pkg/storage/stores/series.(*indexReaderWriter).IndexChunk(0xc0028a5d80, {0x294f800, 0xc00248e420}, {{0x7b3ab125ed65d917, {0xc003b1e5f0, 0xc}, 0x185c41ba2ec, 0x185c444d5cd, 0x7bf00b6}, {0xc00193a140, ...}, ...})
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_index_store.go:91 +0xd6
github.com/grafana/loki/pkg/storage/stores/index.monitoredReaderWriter.IndexChunk.func1({0x294f800?, 0xc00248e420?})
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/index/index.go:122 +0x7f
github.com/weaveworks/common/instrument.CollectedRequest({0x294f800, 0xc00248e210}, {0x2421361, 0xb}, {0x294a430, 0xc002cf5010}, 0x0?, 0xc0024d7408)
	/home/christian/sandbox/grafana/loki/vendor/github.com/weaveworks/common/instrument/instrument.go:167 +0x27a
github.com/grafana/loki/pkg/storage/stores/index.monitoredReaderWriter.IndexChunk({{0x295e630?, 0xc0028a5d80?}, 0xc0037ea348?}, {0x294f800, 0xc00248e210}, {{0x7b3ab125ed65d917, {0xc003b1e5f0, 0xc}, 0x185c41ba2ec, 0x185c444d5cd, ...}, ...})
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/index/index.go:121 +0x14a
github.com/grafana/loki/pkg/storage/stores.(*Writer).PutOne(0xc0035354f0, {0x294f7c8?, 0xc00189a000?}, 0x185c41ba2ec, 0x185c444d5cd, {{0x7b3ab125ed65d917, {0xc003b1e5f0, 0xc}, 0x185c41ba2ec, 0x185c444d5cd, ...}, ...})
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/series_store_write.go:100 +0x406
github.com/grafana/loki/pkg/storage/stores.compositeStore.Put.func1({0x294f7c8?, 0xc00189a000?}, 0xc003d7d2d0?, 0xc004304e80?, {0x29654b8?, 0xc0019c30e0?})
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/composite_store.go:74 +0x86
github.com/grafana/loki/pkg/storage/stores.compositeStore.forStores({{0xc00509d548?, 0x1a93187?, 0x296bf60?}}, {0x294f7c8, 0xc00189a000}, 0x185c41ba2ec, 0x185c444d5cd, 0xc0024d7a30)
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/composite_store.go:241 +0x266
github.com/grafana/loki/pkg/storage/stores.compositeStore.Put({{0xc00509d548?, 0xc0ea0dcce94e1d65?, 0xc3c84c1d3?}}, {0x294f7c8, 0xc00189a000}, {0xc001cc7000?, 0x1, 0xc000580400?})
	/home/christian/sandbox/grafana/loki/pkg/storage/stores/composite_store.go:73 +0x135
github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunk(0xc0010a0580, {0x294f7c8, 0xc00189a000}, 0xc001cc6f80)
	/home/christian/sandbox/grafana/loki/pkg/ingester/flush.go:366 +0xc3
github.com/grafana/loki/pkg/ingester.(*Ingester).flushChunks(0xc0010a0580, {0x294f7c8, 0xc00189a000}, 0x7b3ab125ed65d917, {0xc005425700, 0x1, 0x1}, {0xc002cf4fc8, 0x1, 0x1}, ...)
	/home/christian/sandbox/grafana/loki/pkg/ingester/flush.go:308 +0x68f
github.com/grafana/loki/pkg/ingester.(*Ingester).flushUserSeries(0xc0010a0580, {0xc003b1e5f0, 0xc}, 0xc002d93e00?, 0x1)
	/home/christian/sandbox/grafana/loki/pkg/ingester/flush.go:173 +0x4fc
github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop(0xc0010a0580, 0x17)
	/home/christian/sandbox/grafana/loki/pkg/ingester/flush.go:142 +0xe5
created by github.com/grafana/loki/pkg/ingester.(*Ingester).InitFlushQueues
	/home/christian/sandbox/grafana/loki/pkg/ingester/flush.go:47 +0x45
FAIL	github.com/grafana/loki/integration	52.574s
?   	github.com/grafana/loki/integration/client	[no test files]
?   	github.com/grafana/loki/integration/cluster	[no test files]
FAIL
```

**Comment by JStickler** [comment]
Closing this issue as fixed due to the removal of the BoltDB storage backend. The BoltDB shipper index client (and its `BatchWrite` function) was fully removed in #21637. All current versions of Loki use TSDB-based indexing, which does not share this code path.
