### ISSUE TITLE
Error while sending Batch to Loki (http://localhost:3100/loki/api/v1/push)

### ISSUE THREAD

**Issue by ai-mine-max** [grafana/loki#8677]
I have distributed spring boot 3 project which is similar to the following example:
```
https://github.com/marcingrzejszczak/observability-boot-blog-post/blob/main/RUNNING.adoc
```
When I run the example above or my application with a similar configuration for Prometheus, Grafana, Loki, tempo, etc.., 
I get the following error:
```
7:52:18,094 |-ERROR in com.github.loki4j.client.pipeline.DefaultPipeline@15f54aaf - Error while sending Batch #6102e03aa1d (14,025 bytes) to Loki (http://localhost:3100/loki/api/v1/push) java.net.ConnectException
        at java.net.ConnectException
        at      at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
        at      at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
        at      at com.github.loki4j.client.http.JavaHttpClient.send(JavaHttpClient.java:68)
        at      at com.github.loki4j.client.pipeline.DefaultPipeline.sendBatch(DefaultPipeline.java:263)
        at      at com.github.loki4j.client.pipeline.DefaultPipeline.sendStep(DefaultPipeline.java:249)
        at      at com.github.loki4j.client.pipeline.DefaultPipeline.runSendLoop(DefaultPipeline.java:183)
        at      at com.github.loki4j.client.pipeline.DefaultPipeline.lambda$start$2(DefaultPipeline.java:108)
        at      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at      at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException
        at      at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Unknown Source)
        at      at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source)
        at      at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source)
        at      at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source)
        at      at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
        at      at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
        at      at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at      ... 3 common frames omitted
Caused by: java.nio.channels.ClosedChannelException
        at      at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(Unknown Source)
        at      at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(Unknown Source)
        at      at java.base/sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
        at      at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(Unknown Source)
        at      at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at      ... 10 common frames omitted

```
Any help will be appreciated.

**Comment by cstyan** [comment]
hi @ai-mine-max, the [grafana community slack](https://slack.grafana.com/) is a better place for help and usage related questions
