### ISSUE TITLE
the releationship between compactor and loki read

### ISSUE THREAD

**Issue by btdan** [grafana/loki#9845]
Hello, I deply the loki  in four hosts and Each host has one loki as write and one loki as read
That is to say. On each host, I deply one loki in mode target=write and deply one loki in mode target=read.
And then there are 4 loki target=write and 4 loki target=read for these 4 hosts. All of the loki process is listed in the field of memberlist as join_members.
For a period, they work well. But sometimes later, The loki read process is canceled，that is to say , all the 4 loki target=read is stoped.
The log just as follows:
---------- log   begin ----------------
level=info ts=2023-07-01T09:32:32.324577122Z caller=util.go:116 table-name=netflow_19537 file-name=w72-1688022859772773461-1688035500.gz msg="downloaded file" total_time=324.783139ms
level=info ts=2023-07-01T09:32:32.333015395Z caller=util.go:136 msg="compressing the file" src=/data/netflow-8-208/loki/boltdb-shipper-compactor/netflow_19537/1688203951 dest=/data/netflow-8-208/loki/boltdb-shipper-compactor/netflow_19537/1688203951.gz
level=info ts=2023-07-01T09:32:32.399156638Z caller=index_set.go:281 table-name=netflow_19537 msg="removing source db files from storage" count=66
level=info ts=2023-07-01T09:32:43.473413112Z caller=compactor.go:557 msg="finished compacting table" table-name=netflow_19537
level=info ts=2023-07-01T09:32:43.473510655Z caller=compactor.go:552 msg="compacting table" table-name=netflow_19531
level=info ts=2023-07-01T09:32:43.473575659Z caller=table.go:138 table-name=netflow_19531 msg="listed files" count=21
level=info ts=2023-07-01T09:32:43.473607794Z caller=table.go:297 table-name=netflow_19531 msg="starting compaction of dbs"
level=info ts=2023-07-01T09:32:43.473635923Z caller=table.go:307 table-name=netflow_19531 msg="using compactor-1687548911.gz as seed file"
level=info ts=2023-07-01T09:32:43.59712135Z caller=util.go:116 table-name=netflow_19531 file-name=compactor-1687548911.gz msg="downloaded file" total_time=123.460238ms
**panic: gzip: invalid header**

goroutine 7487 [running]:
github.com/grafana/loki/pkg/storage/stores/shipper/util.getGzipReader({0x2631860, 0xc0036d2100})
        /src/loki/pkg/storage/stores/shipper/util/util.go:41 +0xbc
github.com/grafana/loki/pkg/storage/stores/shipper/util.DownloadFileFromStorage({0xc009e15570, 0x65}, 0x1, 0x0, {0x262b8e0, 0xc00aab87d0}, 0xc0030fcee0)
        /src/loki/pkg/storage/stores/shipper/util/util.go:105 +0x22c
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*table).compactFiles.func2({0xc00308e320, 0x0}, 0x0)
        /src/loki/pkg/storage/stores/shipper/compactor/table.go:332 +0x209
github.com/grafana/dskit/concurrency.ForEachJob.func1()
        /src/loki/vendor/github.com/grafana/dskit/concurrency/runner.go:105 +0x8a
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /src/loki/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /src/loki/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x92

----------log  end -------------------

According the log above, I think this is caused by compactor.
Because I write the  configuration about compactor in the configuration file of loki read, just as follows:
-------- loki target=read  compactor configuration begin ---------------
schema_config:
  configs:
  - from: 2022-09-26
    store: boltdb-shipper
    object_store: iharbor
    schema: v11
    index:
      prefix: netflow_
      period: 24h

storage_config:
  boltdb_shipper:
      active_index_directory: /aiops/diskMonitor/loki/boltdb-shipper-active
      cache_location: /aiops/diskMonitor/loki/boltdb-shipper-cache
      cache_ttl: 168h # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: iharbor
  iharbor:
      bucket_name: diskmonitor-log
      endpoint: ad.addd.com
      token: 21867fcc1935e124ee
      insecure: false
  index_queries_cache_config:
    redis:
      endpoint: 192.168.1.46:50510
      expiration: 240h

compactor:
  working_directory: /aiops/diskMonitor/loki/boltdb-shipper-compactor
  shared_store: iharbor
  compaction_interval: 5m

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 128
  ingestion_burst_size_mb: 256
  per_stream_rate_limit: 20MB
  per_stream_rate_limit_burst: 100MB
  max_entries_limit_per_query: 5000000
  split_queries_by_interval: 1m
  max_query_parallelism: 100

chunk_store_config:
  max_look_back_period: 0
  chunk_cache_config:
    redis:
      endpoint: 192.168.1.46:50510
      expiration: 240h
  write_dedupe_cache_config:
   redis:
      endpoint: 192.168.1.46:50510
      expiration: 240h

-------- loki target=read  compactor configuration end ---------------

Therefor, there are for compactor because there is on compacotr for each loki target=read process.
But according the document of loki , there should only one compactor .
I delete the content about compactor  ,which just as follows:
------ compactor begin -------------
compactor:
  working_directory: /aiops/diskMonitor/loki/boltdb-shipper-compactor
  shared_store: iharbor
  compaction_interval: 5m
----- compactor end --------------

But if the lines above is deleted, I can not run  loki in the mode  target=read. and get the error messages as follows:
--------- log begin -------------
success new iharbor object client
mkdir : no such file or directory
error initialising module: compactor
github.com/grafana/dskit/modules.(*Manager).initModule
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92
github.com/grafana/loki/pkg/loki.(*Loki).Run
        /src/loki/pkg/loki/loki.go:341
main.main
        /src/loki/cmd/loki/main.go:105
runtime.main
        /usr/local/go/src/runtime/proc.go:255
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1581
level=error ts=2023-07-02T07:13:56.005899852Z caller=log.go:103 msg="error running loki" err="mkdir : no such file or directory\nerror initialising module: compactor\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:341\nmain.main\n\t/src/loki/cmd/loki/main.go:105\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"

--------- log end ------------

How to solve this problem?
All in all, I want to run the loki in more than one process as target=read. How to configure compactor in this mode?
Thanks very much.
Best wishes.

**Comment by Segflow** [comment]
Closing because of staleness
