### ISSUE TITLE
panic: gzip: invalid header

### ISSUE THREAD

**Issue by btdan** [grafana/loki#9846]
I run loki(version 2.6.1)  in target=read and target=write mode.
But the process of loki target=read panic and get the logs as follows:
--------- Log begin -----------------

ts=2023-07-02T08:56:18.403990457Z caller=spanlogger.go:80 level=info msg="index list cache built" duration=256.148552ms
level=info ts=2023-07-02T08:56:18.404124826Z caller=compactor.go:552 msg="compacting table" table-name=netflow_19539
level=info ts=2023-07-02T08:56:18.40435926Z caller=table.go:138 table-name=netflow_19539 msg="listed files" count=1
level=info ts=2023-07-02T08:56:18.404463883Z caller=compactor.go:557 msg="finished compacting table" table-name=netflow_19539
level=info ts=2023-07-02T08:56:18.40450602Z caller=compactor.go:552 msg="compacting table" table-name=netflow_19531
level=info ts=2023-07-02T08:56:18.404544332Z caller=table.go:138 table-name=netflow_19531 msg="listed files" count=21
level=info ts=2023-07-02T08:56:18.404564939Z caller=table.go:297 table-name=netflow_19531 msg="starting compaction of dbs"
level=info ts=2023-07-02T08:56:18.404623866Z caller=table.go:307 table-name=netflow_19531 msg="using compactor-1687548911.gz as seed file"
level=info ts=2023-07-02T08:56:18.46752197Z caller=util.go:116 table-name=netflow_19531 file-name=compactor-1687548911.gz msg="downloaded file" total_time=62.864301ms
level=info ts=2023-07-02T08:56:18.524643778Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687561200.gz msg="downloaded file" total_time=56.327442ms
level=info ts=2023-07-02T08:56:18.532803196Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687553100.gz msg="downloaded file" total_time=64.186337ms
level=info ts=2023-07-02T08:56:18.53977106Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687558500.gz msg="downloaded file" total_time=71.254044ms
level=info ts=2023-07-02T08:56:18.540017265Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687554900.gz msg="downloaded file" total_time=71.410896ms
level=info ts=2023-07-02T08:56:18.540816238Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687560300.gz msg="downloaded file" total_time=72.481506ms
level=info ts=2023-07-02T08:56:18.541110677Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687554000.gz msg="downloaded file" total_time=72.465941ms
level=info ts=2023-07-02T08:56:18.541862455Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687557600.gz msg="downloaded file" total_time=73.424396ms
level=info ts=2023-07-02T08:56:18.541988697Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687550400.gz msg="downloaded file" total_time=73.475773ms
level=info ts=2023-07-02T08:56:18.54220403Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687559400.gz msg="downloaded file" total_time=73.864007ms
level=info ts=2023-07-02T08:56:18.542506933Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687551300.gz msg="downloaded file" total_time=73.872143ms
level=info ts=2023-07-02T08:56:18.542993756Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687564800.gz msg="downloaded file" total_time=74.691922ms
level=info ts=2023-07-02T08:56:18.543172563Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687563900.gz msg="downloaded file" total_time=74.63919ms
level=info ts=2023-07-02T08:56:18.543515886Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687555800.gz msg="downloaded file" total_time=74.896492ms
level=info ts=2023-07-02T08:56:18.543662919Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687556700.gz msg="downloaded file" total_time=75.094818ms
level=info ts=2023-07-02T08:56:18.546070209Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687563000.gz msg="downloaded file" total_time=77.490597ms
level=info ts=2023-07-02T08:56:18.54638318Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687552200.gz msg="downloaded file" total_time=77.919732ms
level=info ts=2023-07-02T08:56:18.549097155Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687548600.gz msg="downloaded file" total_time=80.578194ms
level=info ts=2023-07-02T08:56:18.551681803Z caller=util.go:116 table-name=netflow_19531 file-name=w73-1681710601571637090-1687549500.gz msg="downloaded file" total_time=83.042012ms
panic: gzip: invalid header

goroutine 11182 [running]:
github.com/grafana/loki/pkg/storage/stores/shipper/util.getGzipReader({0x2631860, 0xc000abc200})
        /src/loki/pkg/storage/stores/shipper/util/util.go:41 +0xbc
github.com/grafana/loki/pkg/storage/stores/shipper/util.DownloadFileFromStorage({0xc000d82850, 0x65}, 0x1, 0x0, {0x262b8e0, 0xc000a82280}, 0xc002c626e0)
        /src/loki/pkg/storage/stores/shipper/util/util.go:105 +0x22c
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*table).compactFiles.func2({0xc002c62748, 0xc00000fd78}, 0x0)
        /src/loki/pkg/storage/stores/shipper/compactor/table.go:332 +0x209
github.com/grafana/dskit/concurrency.ForEachJob.func1()
        /src/loki/vendor/github.com/grafana/dskit/concurrency/runner.go:105 +0x8a
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /src/loki/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /src/loki/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x92

----------log end -------------------
According the logs above, we can see it is caused by compactor.
And then I go to the directory about compactor, and find the file named w73-1681710601571637090-1687549500.gz. However ,the file is 0 bytes. Just as follows:
-----------Command begin ------------

-rw-r--r-- 1 root root 524288 Jul  2 16:56 compactor-1687548911.gz
-rw-r--r-- 1 root root      0 Jul  2 16:56 w73-1681710601571637090-1687547700.gz
-rw-r--r-- 1 root root  32768 Jul  2 16:56 w73-1681710601571637090-1687549500.gz
-rw-r--r-- 1 root root  32768 Jul  2 16:56 w73-1681710601571637090-1687550400.gz
-rw-r--r-- 1 root root  32768 Jul  2 16:56 w73-1681710601571637090-1687552200.gz

-----------Command end ------------
If I delete the file w73-1681710601571637090-1687547700.gz and run loki in target=read mode again, loki can run again.
But it panic again after a period.
I don't know the reason and how to solve this problem.
Can you help me ?
Thanks very much.
Best Wishes to you.

**Comment by btdan** [comment]
By the way. I have 4 hosts, and run 1 process of loki target=read on each hosts.
Each loki  target=read has the same configuration about compactor.
And I can find  directory about compactor on each hosts.

**Comment by Segflow** [comment]
Closing as fixed and as a duplicate of #9845.
